CHANGELOG.md, protected/humhub/modules/user/widgets/PeopleFilterPicker.php
=> Hide data of disabled users on picker filters on "People" page

protected/humhub/modules/stream/tests/codeception/acceptance/StreamCest.php
https://github.com/humhub/humhub/runs/7233180225?check_suite_focus=true
=> Fix test for slow server

CHANGELOG.md, composer.json, composer.lock, protected/humhub/modules/notification/Events.php
Issue: https://github.com/humhub/humhub/issues/5813
=> Fix deprecated null value for hour param in `mktime()`

.gitattributes
=> Add .gitattributes, exclude tests from archive

CHANGELOG.md, protected/humhub/modules/stream/models/filters/DateStreamFilter.php
Issue: https://github.com/humhub/team_tasks/issues/242
=> Fix format date to mysql on date stream filter

CHANGELOG.md, protected/humhub/modules/user/Events.php
Issue: https://github.com/humhub/humhub/issues/5830
=> Fix cron job of search index rebuilding

protected/humhub/modules/stream/tests/codeception/_support/AcceptanceTester.php, protected/humhub/modules/stream/tests/codeception/acceptance/StreamCest.php
Issue: https://github.com/humhub/humhub/issues/5834
=> Fix date filter test

protected/humhub/modules/stream/tests/codeception/acceptance/StreamCest.php
Try to fix https://github.com/humhub/humhub/runs/7836330146?check_suite_focus=true#step:18:1389
(Previous fix worked well here https://github.com/humhub/humhub/pull/5836)
=> Fix stream date filter

CHANGELOG.md, protected/humhub/modules/stream/models/filters/StreamQueryFilter.php, protected/humhub/modules/ui/filter/models/Filter.php
Issue: https://github.com/humhub/mail/issues/268
=> Fix unknown `streamQuery` on load `Filter`

CHANGELOG.md, protected/humhub/components/Application.php, protected/humhub/components/console/Application.php
=> Improved PHP Min Version Check

CHANGELOG-DEV.md, protected/humhub/modules/space/modules/manage/controllers/MemberController.php, protected/humhub/modules/space/modules/manage/jobs/RemoveAllMembersFromSpaceJob.php, protected/humhub/modules/space/modules/manage/views/member/index.php, protected/humhub/modules/space/modules/manage/widgets/MemberHeaderControlsMenu.php
https://github.com/humhub/humhub/issues/5808
=> Enh #5808:Add a menu to remove all members of a space

CHANGELOG-DEV.md, protected/humhub/modules/space/widgets/Members.php, protected/humhub/modules/space/widgets/SpaceFollowers.php, protected/humhub/modules/space/widgets/views/members.php, protected/humhub/modules/space/widgets/views/spaceFollowers.php
Issue: https://github.com/humhub/humhub/issues/5841
=> Possibility to show Members/Followers as list from Space about page

protected/humhub/modules/user/models/forms/AccountSettings.php
Issue: https://github.com/humhub/team_tasks/issues/246
=> Fix updating of user visibility

CHANGELOG.md, protected/humhub/components/i18n/I18N.php, protected/humhub/modules/admin/models/forms/ApproveUserForm.php, protected/humhub/modules/user/controllers/AccountController.php, protected/humhub/modules/user/models/User.php, protected/humhub/modules/user/models/forms/Registration.php, protected/humhub/tests/codeception/fixtures/data/setting.php
Issue: https://github.com/humhub/humhub/issues/5854
=> Don't validate user language on approve

CHANGELOG.md, protected/humhub/components/UrlManager.php, protected/humhub/libs/DynamicConfig.php, protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextEmailHtmlConverterTest.php, protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextHtmlConverterTest.php, protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextMarkdownConverterTest.php, protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextPlaintextConverterTest.php, protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextShortTextConverterTest.php, protected/humhub/modules/user/tests/codeception/unit/ApproveUserFormTest.php, protected/humhub/modules/web/tests/codeception/acceptance/NonceCest.php, protected/humhub/tests/codeception/config/dynamic.php, protected/humhub/tests/codeception/fixtures/data/setting.php
Issue: https://github.com/humhub/team_tasks/issues/250
=> Use Base URL from general settings for all absolute URLs

protected/humhub/components/UrlManager.php
Issue: https://github.com/humhub/team_tasks/issues/250#issuecomment-1250037846
=> Use domain path(folder) from the current request

CHANGELOG.md, protected/humhub/modules/user/models/User.php
=> Fixed non string value in User Model email attribute

CHANGELOG-DEV.md, protected/humhub/modules/user/migrations/m220919_104234_auth_key.php, protected/humhub/modules/user/models/Password.php, protected/humhub/modules/user/models/User.php
Issue: https://github.com/humhub/team_tasks/issues/249
=> Invalidate active sessions after password changing

CHANGELOG.md, protected/humhub/components/OnlineModule.php, protected/humhub/modules/admin/widgets/ModuleControls.php
Issue: https://github.com/humhub/humhub/issues/5874
=> Fix adding licence key after removing it from marketplace

CHANGELOG.md, protected/humhub/modules/stream/resources/js/humhub.stream.Stream.js, protected/humhub/modules/user/widgets/StreamViewer.php
Issue: https://github.com/humhub/team_tasks/issues/253
=> Fix wrong empty profile stream message

CHANGELOG-DEV.md, protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub/issues/5820
=> Selftest for base URL

CHANGELOG-DEV.md, protected/humhub/modules/user/widgets/PeopleFilters.php
Issue: https://github.com/humhub/team_tasks/issues/255
=> Improve select2 width on people filters

CHANGELOG-DEV.md, protected/humhub/modules/search/controllers/MentioningController.php, protected/humhub/modules/user/components/ActiveQueryUser.php, protected/humhub/modules/user/components/PeopleQuery.php
Issue: https://github.com/humhub/mail/pull/273#discussion_r1003492181
=> New filter ActiveQueryUser->available()

CHANGELOG.md, protected/humhub/modules/ldap/components/ZendLdap.php
Issue: https://github.com/humhub/humhub/issues/5909
=> Fix optional parameter on ldap user searching

.htaccess.dist, CHANGELOG_DEV.md
=> Custom route definitions for well-known paths

CHANGELOG-DEV.md, protected/humhub/modules/user/views/must-change-password/index.php
Issue: https://github.com/humhub/humhub/issues/5811
=> Don't require current password if not exists on force change password

CHANGELOG-DEV.md, protected/humhub/components/Request.php, protected/humhub/config/common.php, protected/humhub/config/web.php, protected/humhub/libs/CookieBuilder.php, protected/humhub/modules/user/components/Session.php
=> Auto secure cookie on SSL

CHANGELOG-DEV.md, protected/humhub/config/common.php, protected/humhub/modules/tour/Module.php, protected/humhub/modules/tour/controllers/TourController.php
=> Moved Tour Param to Module

CHANGELOG.md, protected/humhub/modules/space/behaviors/SpaceModelMembership.php
=> Allow empty space invite with empty originator

protected/humhub/modules/installer/libs/InitialData.php, protected/humhub/modules/user/models/Profile.php
=> Profile Refactor

CHANGELOG-DEV.md, protected/humhub/modules/content/widgets/WallCreateContentMenu.php, protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php
Issue: https://github.com/humhub/humhub/issues/5929
=> Add property `createMode` for wall stream entry widget

protected/humhub/modules/user/models/User.php
Issue: https://github.com/humhub/humhub/issues/5949
=> Fix failed updater for the field `user:auth_key`

protected/humhub/modules/space/controllers/MembershipController.php, protected/humhub/modules/space/widgets/SpaceDirectoryIcons.php, protected/humhub/modules/space/widgets/views/spaceDirectoryIcons.php
=> Fix #5958: Fixed members list in Space overview

CHANGELOG.md, protected/humhub/models/forms/CropProfileImage.php
Issue: https://github.com/humhub/humhub/issues/5960
=> Fix cropping of space banner

CHANGELOG.md, protected/humhub/components/i18n/ModuleMessageSource.php
Issue: https://github.com/humhub/humhub/issues/5966
=> Fix invalid message pattern without initialized source language

protected/humhub/components/Module.php
**The PR fulfils these requirements:**
Please let me know if I should consider/fix something in my code or where I should add this to a change log. Thank you!
=> Actually cache $_moduleInfo

protected/humhub/modules/space/controllers/MembershipController.php
Fix "403 forbidden" restriction on user searching in picker
=> Fix user searching in picker

CHANGELOG.md, protected/humhub/modules/user/components/User.php
Issue: https://github.com/humhub/humhub/issues/5996
=> Fix param type in strpos() on PHP 8.1

protected/humhub/modules/user/models/fieldtype/Birthday.php
Issue: https://github.com/humhub/humhub/issues/5997
=> Fix null param value on PHP 8.1

static/less/base.less, static/less/button.less, static/less/comment.less, static/less/datepicker.less, static/less/form.less, static/less/loader.less, static/less/login.less, static/less/mentioning.less, static/less/mixins.less, static/less/modal.less, static/less/panel.less, static/less/popover.less, static/less/progress.less, static/less/richtext.less, static/less/stream.less, static/less/tooltip.less, static/less/topbar.less, static/less/user-feedback.less
Remove old prefixes as they are useless.
Not removed are working prefixes:
- mobile.less -> not standardized 
- ms login
=> Remove old prefixes

CHANGELOG.md, protected/humhub/modules/space/widgets/views/spaceDirectoryIcons.php
Issue: https://github.com/humhub/humhub/issues/6007
=> Fix number of space members

CHANGELOG-DEV.md, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/user/models/User.php
Issue: https://github.com/humhub/humhub/issues/6017
=> Hide Password Tab in administration for LDAP users

CHANGELOG.md, protected/humhub/compat/HForm.php, protected/humhub/modules/admin/controllers/UserProfileController.php, protected/humhub/modules/user/models/fieldtype/BaseType.php, protected/humhub/modules/user/models/fieldtype/BaseTypeVirtual.php, protected/humhub/modules/user/models/fieldtype/Birthday.php, protected/humhub/modules/user/models/fieldtype/Checkbox.php, protected/humhub/modules/user/models/fieldtype/CheckboxList.php, protected/humhub/modules/user/models/fieldtype/CountrySelect.php, protected/humhub/modules/user/models/fieldtype/Date.php, protected/humhub/modules/user/models/fieldtype/DateTime.php, protected/humhub/modules/user/models/fieldtype/MarkdownEditor.php, protected/humhub/modules/user/models/fieldtype/Select.php, protected/humhub/modules/user/models/fieldtype/TextArea.php, protected/humhub/modules/user/tests/codeception/_support/AcceptanceTester.php, protected/humhub/modules/user/tests/codeception/acceptance/ProfileCest.php
Issue: https://github.com/humhub/humhub/issues/6018
=> Fix option "Editable" of the profile fields

CHANGELOG-DEV.md, protected/humhub/modules/user/grid/DisplayNameColumn.php
https://github.com/humhub/humhub/issues/6031
=> On users list grid, show Auth mode badge only for sys admins #6031

CHANGELOG.md, README.md, protected/humhub/modules/content/components/AbstractActiveQueryContentContainer.php, protected/humhub/modules/content/components/ContentContainerController.php, protected/humhub/modules/content/models/ContentContainer.php, protected/humhub/modules/space/components/ActiveQuerySpace.php, protected/humhub/modules/user/components/ActiveQueryUser.php, protected/humhub/modules/user/tests/codeception/acceptance/InvisibleUserCest.php
Issue: https://github.com/humhub/team_tasks/issues/269
=> View own invisible profile

CHANGELOG-DEV.md, protected/humhub/config/common.php, protected/humhub/config/i18n.php
=> Added Estonian language

protected/humhub/modules/user/components/ActiveQueryUser.php
Bug related to the PR https://github.com/humhub/humhub/pull/6012
=> Fix user visibility filter for guest

CHANGELOG.md, protected/humhub/modules/space/widgets/SpaceDirectoryIcons.php, protected/humhub/modules/space/widgets/views/spaceDirectoryIcons.php
Issue: https://github.com/humhub/humhub/issues/6026
=> Fix visibility members counter for guests

CHANGELOG.md, protected/humhub/modules/space/tests/codeception/acceptance.suite.yml, protected/humhub/modules/user/models/UserFilter.php, protected/humhub/modules/user/models/UserPicker.php, protected/humhub/modules/user/widgets/UserPicker.php
Issue: https://github.com/humhub/humhub/issues/6030
=> Use all searchable profile fields in UserPicker searching

CHANGELOG.md, protected/humhub/modules/content/components/ContentContainerController.php, protected/humhub/modules/user/tests/codeception/acceptance/InvisibleUserCest.php
Issue: https://github.com/humhub/humhub/issues/6027
=> Fix private user visibility by guest

CHANGELOG.md, protected/humhub/modules/search/libs/SearchResultSet.php
Issue: https://github.com/humhub/team_tasks/issues/270
=> Fix search of obsolete cached objects

CHANGELOG.md, protected/humhub/modules/space/behaviors/SpaceModelMembership.php, protected/humhub/modules/space/models/Space.php
Issue: https://github.com/humhub/humhub/issues/6051
=> Fix visibility of "NEW UPDATES AVAILABLE!" for space creator

CHANGELOG.md, protected/humhub/modules/notification/controllers/OverviewController.php, protected/humhub/modules/notification/models/forms/FilterForm.php
Issue: https://github.com/humhub/humhub/issues/6054
=> Fix pagination after filter notifications

protected/humhub/modules/topic/messages/uk/permissions.php
=> Ukrainian translation for topic module.

protected/humhub/modules/space/messages/uk/permissions.php
=> Ukrainian translation for space module.

protected/humhub/messages/uk/error.php
=> Ukrainian translation for a core module.

CHANGELOG-DEV.md, protected/humhub/modules/marketplace/widgets/ModuleUpdateActionButtons.php
Fix Changelog Link with new Marketplace URL #6022
=> Fix Changelog Link with new Marketplace URL #6022

CHANGELOG-DEV.md, protected/humhub/modules/content/resources/js/humhub.content.form.js
Issue: https://github.com/humhub/humhub/issues/6077
=> Always display content tabs

protected/humhub/modules/admin/controllers/PendingRegistrationsController.php, protected/humhub/modules/admin/models/PendingRegistrationSearch.php, protected/humhub/modules/admin/widgets/views/pending-registrations.php, protected/humhub/modules/space/models/forms/InviteForm.php, protected/humhub/modules/user/controllers/RegistrationController.php, protected/humhub/modules/user/models/Invite.php, protected/humhub/modules/user/models/User.php, protected/humhub/modules/user/models/forms/Invite.php, protected/humhub/modules/user/views/registration/byLink.php
Fix for https://github.com/humhub/humhub/issues/5699
=> Fix for Allow users to invite by link #5699

CHANGELOG-DEV.md, protected/humhub/modules/content/components/ActiveQueryContent.php, protected/humhub/modules/content/models/Content.php, protected/humhub/modules/stream/models/filters/ContentContainerStreamFilter.php, protected/humhub/modules/user/models/User.php, protected/humhub/modules/user/stream/filters/IncludeAllContributionsFilter.php
https://github.com/humhub/humhub/issues/5263
=> 5263 allow other groups to view all content

protected/humhub/modules/notification/resources/js/humhub.notification.js, static/js/humhub/humhub.core.js
=> Also handle mail module notification in page title

CHANGELOG.md, protected/humhub/modules/admin/views/setting/oembed_edit.php
Issue: https://github.com/humhub/humhub/issues/6103
=> Fix null passing to parse_str()

CHANGELOG.md, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/admin/models/forms/UserEditForm.php
Issue: https://github.com/humhub/humhub/issues/6104
=> Fix update user with not existing group

CHANGELOG.md, protected/humhub/modules/admin/controllers/SettingController.php
Issue: https://github.com/humhub/humhub/issues/6108
=> Fix log time in the `date()` function

protected/humhub/modules/activity/models/Activity.php, protected/humhub/modules/comment/tests/codeception/unit/CommentTest.php, protected/humhub/modules/content/components/ContentActiveRecord.php, protected/humhub/modules/content/models/Content.php
=> Always use SoftDelete for all ContentActiveRecord

CHANGELOG-DEV.md, protected/humhub/libs/SelfTest.php
=> Added Pretty URL Self Test

CHANGELOG.md, protected/humhub/modules/content/controllers/ContentController.php, protected/humhub/modules/content/models/forms/AdminDeleteContentForm.php, protected/humhub/modules/content/resources/js/humhub.content.js
Issue: https://github.com/humhub/team_tasks/issues/277
=> Fix deleting a content with empty reason

CHANGELOG-DEV.md, protected/humhub/modules/notification/views/user/notification.php, protected/humhub/modules/notification/widgets/UserInfoWidget.php
=> Added UserInfoWidget for User Notification Settings

protected/humhub/modules/space/models/AdvancedSettings.php, protected/humhub/modules/space/modules/manage/controllers/DefaultController.php, protected/humhub/modules/space/modules/manage/views/default/advanced.php
Issue: https://github.com/humhub/humhub/issues/6129, https://github.com/humhub/wording/issues/116
=> Update wording for space advanced settings

protected/humhub/modules/content/Events.php, protected/humhub/modules/content/Module.php, protected/humhub/modules/content/config.php
Issue: https://github.com/humhub/team_tasks/issues/286#issuecomment-1448714583
=> Publish scheduled content each 10 minutes

protected/humhub/modules/content/views/content/scheduleOptions.php
Issue: https://github.com/humhub/team_tasks/issues/286#issuecomment-1450147847
=> Wording for scheduled options

CHANGELOG.md, protected/humhub/modules/admin/models/forms/DesignSettingsForm.php, protected/humhub/modules/admin/models/forms/FileSettingsForm.php, protected/humhub/modules/admin/views/setting/file.php, protected/humhub/modules/search/controllers/SearchController.php, protected/humhub/modules/search/engine/Search.php, protected/humhub/modules/search/models/forms/SearchForm.php
Issue: https://github.com/humhub/humhub/issues/6142
=> Fix saving empty values in admin settings

CHANGELOG.md, protected/humhub/modules/user/components/PeopleQuery.php
Issue: https://github.com/humhub/humhub-internal/issues/8
=> Fix duplicate people cards on sort

CHANGELOG.md, protected/humhub/modules/user/components/PeopleQuery.php
Issue: https://github.com/humhub/humhub-internal/issues/4
=> Hide invisible users on People page

static/less/humhub.less
Issue: https://github.com/humhub/documentation/pull/70
=> Fix @prev-directory

CHANGELOG.md, protected/humhub/modules/content/models/ContentContainerTagRelation.php
Issue: https://github.com/humhub/humhub/issues/6152
=> Avoid duplicate container(Space/User) tags on save

CHANGELOG-DEV.md, protected/humhub/libs/SelfTest.php
=> eth #6123: Requirement Checker proc_open

protected/humhub/modules/space/widgets/SpaceDirectoryIcons.php
Issue: https://github.com/humhub/humhub-internal/issues/7#issuecomment-1463872759
=> Count all active and non-invisible members for guests on space directory

static/less/humhub.less
- [x ] Feature
- [x ] No
https://github.com/humhub/humhub/pull/6153#issuecomment-1468155219
=> Add @prev-select2

CHANGELOG-DEV.md, protected/humhub/modules/ui/form/widgets/views/markdownModals.php, protected/humhub/widgets/views/markdownFieldModals.php
https://github.com/humhub/humhub/issues/6100
=> Fix #6100: Broken area reference in some modal boxes

CHANGELOG-DEV.md, protected/humhub/widgets/GlobalConfirmModal.php
https://github.com/humhub/humhub/issues/6099
=> Fix #6099: Empty buttons in GlobalConfirmModal footer

CHANGELOG-DEV.md, protected/humhub/modules/admin/views/user/list.php, protected/humhub/modules/admin/widgets/views/pending-registrations.php
=> Enh #6171: Make email in user administration and user approval clickable

CHANGELOG-DEV.md, protected/humhub/modules/user/views/people/index.php
Issue: https://github.com/humhub/humhub/issues/5681
=> People: Add Group Description

CHANGELOG-DEV.md, protected/humhub/modules/user/controllers/RegistrationController.php
https://github.com/humhub/humhub/issues/6202
=> 6202 invite by link not possible if invited by email

CHANGELOG-DEV.md, protected/humhub/modules/user/models/fieldtype/BaseTypeVirtual.php, protected/humhub/modules/user/models/fieldtype/Birthday.php, protected/humhub/modules/user/models/fieldtype/CheckboxList.php, protected/humhub/modules/user/models/fieldtype/CountrySelect.php, protected/humhub/modules/user/models/fieldtype/Date.php, protected/humhub/modules/user/models/fieldtype/DateTime.php, protected/humhub/modules/user/models/fieldtype/MarkdownEditor.php, protected/humhub/modules/user/models/fieldtype/Select.php, protected/humhub/modules/user/models/fieldtype/TextArea.php
Issue: https://github.com/humhub/humhub/issues/5718#issuecomment-1487320074
=> Fix profile field "Country" to use js plugin Select2

CHANGELOG-DEV.md, protected/humhub/modules/activity/helpers/ActivityHelper.php, protected/humhub/modules/content/Events.php, protected/humhub/modules/content/components/ContentActiveRecord.php, protected/humhub/modules/content/events/ContentEvent.php, protected/humhub/modules/content/interfaces/SoftDeletable.php, protected/humhub/modules/content/models/Content.php, protected/humhub/modules/content/models/forms/AdminDeleteContentForm.php, protected/humhub/modules/content/tests/codeception/unit/ContentTagTest.php, protected/humhub/modules/search/libs/SearchHelper.php
Issue: https://github.com/humhub/humhub-internal/issues/22
=> Improve SoftDelete implementation

CHANGELOG.md, protected/humhub/modules/installer/controllers/IndexController.php, protected/humhub/modules/installer/controllers/SetupController.php, protected/humhub/modules/ldap/authclient/LdapAuth.php, protected/humhub/modules/tour/Module.php, protected/humhub/modules/ui/filter/models/Filter.php
=> Fixed Saas Handling in Installer

CHANGELOG-DEV.md, protected/humhub/modules/admin/widgets/AdminMenu.php
=> Fix #6216: Spaces icon in admin menu

CHANGELOG-DEV.md, protected/humhub/components/Migration.php
The following PR allows to 
- log Errors and Exceptions happening during a migration to the log facilities
- log messages get the category 'migration'
- Feature
- No
- Enh #6236
- Changelog was modified
=> Feature log migrations

protected/humhub/modules/user/controllers/AuthController.php, protected/humhub/modules/user/controllers/RegistrationController.php, protected/humhub/modules/user/helpers/AuthHelper.php, protected/humhub/modules/user/services/AuthClientService.php
Changes and corrections are necessary for correct authorization using the auth-linkedin module if the user is not yet registered.
=> Minor AuthClient Helper & -Service Cleanups 

CHANGELOG.md, protected/humhub/modules/content/components/ActiveQueryContent.php
Issue: https://github.com/humhub/sharebetween/issues/28#issuecomment-1517901312
=> Fix emulate execution on check readable content

CHANGELOG-DEV.md, protected/humhub/components/ModuleManager.php
- Refactor
- Should not
- No New/updated tests are included
- Changelog was modified
See #6195
=> Add types to properties of ModuleManager

CHANGELOG-DEV.md, protected/humhub/components/Migration.php
- Add parameter and return types
- Add/improve PhpDoc
- Add new functions
- safeAddForeignKeyToUserTable()
- safeAddForeignKeyUpdatedBy()
- safeAddForeignKeyCreatedBy()
- integerReferenceKey()
- timestampWithoutAutoUpdate()
=> Improve migration class

CHANGELOG.md, protected/humhub/modules/activity/helpers/ActivityHelper.php, protected/humhub/modules/activity/tests/codeception/unit/DeleteActivityTest.php, protected/humhub/modules/content/components/ContentActiveRecord.php, protected/humhub/modules/content/models/Content.php
Issue: https://github.com/humhub/humhub-internal/issues/31#issuecomment-1521461397
=> Updated activities to same state as parent record

CHANGELOG.md, protected/humhub/components/ActiveRecord.php, protected/humhub/modules/stream/actions/LegacyStreamTrait.php, protected/humhub/modules/user/models/Group.php, protected/humhub/modules/user/models/Password.php
Issue: https://github.com/humhub/calendar/issues/370#issuecomment-1527291594
=> Fix date format for columns `created_at` and `updated_at`

protected/humhub/modules/ui/form/widgets/ContentHiddenCheckbox.php, protected/humhub/modules/ui/form/widgets/ContentVisibilitySelect.php
=> Fix broken HMTL in widgets

CHANGELOG-DEV.md, protected/humhub/components/SettingActiveRecord.php, protected/humhub/components/SettingsManager.php, protected/humhub/libs/BaseSettingsManager.php, protected/humhub/models/Setting.php, protected/humhub/modules/content/components/ContentContainerSettingsManager.php, protected/humhub/modules/content/models/ContentContainerSetting.php
- Bugfix
- No
Happy to get feedback and make adjustments, if required.
=> Clear Module Settings Cache after deleting settings from database

CHANGELOG.md, protected/humhub/modules/activity/Events.php, protected/humhub/modules/content/Events.php, protected/humhub/modules/post/Events.php
Issue: https://github.com/humhub/humhub-internal/issues/40#issuecomment-1529858671
=> Hard delete content records on integrity check

protected/humhub/modules/comment/messages/hu/base.php
- [X ] Other, please describe:
- [X ] No
Missing language strings
=> Missing Hungarian strings

CHANGELOG-DEV.md, protected/humhub/modules/notification/resources/js/humhub.notification.js
=> Fix #44: Mail Module Indicator Problem

CHANGELOG-DEV.md, protected/humhub/modules/content/models/Content.php
Issue: https://github.com/humhub/rest/issues/120
=> Fix ambiguous space sort order column

CHANGELOG.md, protected/humhub/modules/content/jobs/PurgeDeletedContents.php
Issue: https://github.com/humhub/humhub/issues/6293
=> Delete content from DB completely on purge content by cron job

CHANGELOG.md, protected/humhub/modules/activity/stream/ActivityStreamQuery.php
=> Fix Activity Loading Speed

CHANGELOG-DEV.md, protected/humhub/modules/file/converter/PreviewImage.php, protected/humhub/modules/file/widgets/FilePreview.php, protected/humhub/modules/file/widgets/ShowFiles.php, protected/humhub/modules/file/widgets/views/showFiles.php
=> Enh #49: File Converter Logging Issue

CHANGELOG-DEV.md, protected/humhub/modules/content/models/forms/ScheduleOptionsForm.php, protected/humhub/modules/content/resources/js/humhub.content.form.js, protected/humhub/modules/content/views/content/scheduleOptions.php, protected/humhub/modules/content/widgets/views/wallCreateContentFormFooter.php
Issue: https://github.com/humhub/humhub/issues/6304
=> Update button title on creating of not published content

CHANGELOG.md, protected/humhub/modules/stream/models/filters/PinnedContentStreamFilter.php
Issue: https://github.com/humhub/humhub/issues/6262
=> Fix visibility of deleted content

CHANGELOG-DEV.md, protected/humhub/modules/user/models/Password.php
https://github.com/humhub/humhub/issues/6300
=> Fix error when calling setPassword

CHANGELOG.md, protected/humhub/modules/file/models/FileUpload.php
Issue: https://github.com/humhub/cfiles/issues/179
=> Fix file uploading

CHANGELOG.md, protected/humhub/modules/installer/controllers/ConfigController.php
Issue: https://github.com/humhub/humhub/issues/6333
=> Fix installation

CHANGELOG.md, protected/humhub/modules/stream/resources/js/humhub.stream.StreamEntry.js
Issue: https://github.com/humhub/humhub-internal/issues/59
=> Fix updating of post on wall stream

CHANGELOG-DEV.md, protected/humhub/modules/user/widgets/PeopleFilterPicker.php
https://github.com/humhub/humhub/issues/5788
=> People: Country Filter, Limit Results

CHANGELOG-DEV.md, protected/humhub/modules/user/grid/BaseColumn.php
=> Added SqlDataProvider support for ImageColumn and DisplayNameColumn

CHANGELOG-DEV.md, protected/humhub/modules/activity/jobs/SendMailSummary.php, protected/humhub/modules/content/jobs/PurgeDeletedContents.php, protected/humhub/modules/live/jobs/DatabaseCleanup.php, protected/humhub/modules/marketplace/jobs/ModuleCleanupsJob.php, protected/humhub/modules/notification/jobs/SendBulkNotification.php, protected/humhub/modules/queue/LongRunningActiveJob.php, protected/humhub/modules/search/jobs/RebuildIndex.php, protected/humhub/modules/space/jobs/AddUsersToSpaceJob.php, protected/humhub/modules/space/modules/manage/jobs/ChangeContentVisibilityJob.php, protected/humhub/modules/space/modules/manage/jobs/RemoveAllMembersFromSpaceJob.php, protected/humhub/modules/user/jobs/DeleteUser.php
For comment https://github.com/humhub/humhub/issues/6209#issuecomment-1566241193
=> use the new LongRunningActiveJob for more jobs

CHANGELOG.md, protected/humhub/modules/content/services/ContentStateService.php, protected/humhub/modules/content/widgets/WallCreateContentForm.php
Related ro issue: https://github.com/humhub/sharebetween/issues/37
=> Use integer format for Content columns "visibility" and "state" right after creating

protected/humhub/modules/user/models/forms/AccountRecoverPassword.php, protected/humhub/modules/user/tests/codeception/acceptance/PasswordRecoveryCest.php, protected/humhub/modules/user/views/password-recovery/index_modal.php
Issue: https://github.com/humhub/humhub-internal/issues/64
=> Display error on wrong captch of password recovery modal form

CHANGELOG-DEV.md, protected/humhub/modules/user/models/fieldtype/MarkdownEditor.php
Issue: https://github.com/humhub/humhub-internal/issues/55
=> Fix initialization of account profile field type "Markdown"

CHANGELOG-DEV.md, protected/humhub/modules/installer/controllers/SetupController.php
https://github.com/humhub/humhub-internal/issues/69
=> The installer should clear all caches early

protected/humhub/modules/activity/tests/codeception/functional/ActivityLinkCest.php, protected/humhub/modules/user/tests/codeception/acceptance/AccountCest.php, protected/humhub/modules/user/tests/codeception/acceptance/ChangeEmailCest.php, protected/humhub/modules/user/tests/codeception/acceptance/ProfileCest.php, protected/humhub/modules/user/widgets/AccountMenu.php, protected/humhub/modules/user/widgets/AccountProfileMenu.php, protected/humhub/modules/user/widgets/AccountTopMenu.php
Issue: https://github.com/humhub/wording/issues/129
=> Update wording of account menu

CHANGELOG-DEV.md, MIGRATE-DEV.md, protected/humhub/config/web.php, protected/humhub/modules/web/security/models/SecuritySettings.php
Issue: https://github.com/humhub/humhub-internal/issues/66
=> Enable nonce in config web header

CHANGELOG.md, protected/humhub/modules/dashboard/stream/filters/DashboardMemberStreamFilter.php
Issue: https://github.com/humhub/custom-pages/issues/283
=> Fix visibility of global content on dashboard for registered users

CHANGELOG-DEV.md, protected/humhub/modules/user/controllers/AuthController.php, protected/humhub/modules/user/models/Invite.php, protected/humhub/modules/user/models/User.php
Issue: https://github.com/humhub/humhub/issues/6409
=> Enh #6409: Redirect to the invited space after registration

CHANGELOG-DEV.md, protected/humhub/modules/user/controllers/AuthController.php, protected/humhub/modules/user/controllers/RegistrationController.php, protected/humhub/modules/user/services/LinkRegistrationService.php
Issue: https://github.com/humhub/humhub/issues/6411
=> Enh #6411: Make invite by link from a space work for registered users

protected/humhub/components/behaviors/PolymorphicRelation.php, protected/humhub/modules/content/components/ContentActiveRecord.php, protected/humhub/modules/content/models/Content.php, protected/humhub/modules/content/models/ContentContainer.php, protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php, protected/humhub/modules/content/widgets/stream/views/wallStreamEntryBodyLayout.php, protected/humhub/modules/file/components/FileManager.php, protected/humhub/modules/like/models/Like.php, protected/humhub/modules/stream/models/StreamQuery.php, protected/humhub/modules/user/models/User.php
https://github.com/humhub/humhub-internal/issues/24
=> Performance improvements part 2

CHANGELOG-DEV.md, protected/humhub/components/console/Application.php, protected/humhub/libs/LogoImage.php
Issue: https://github.com/humhub/humhub/issues/6386
=> Fix absolute base URL in console commands

CHANGELOG-DEV.md, protected/humhub/modules/user/controllers/AuthController.php
Issue: https://github.com/humhub/humhub-internal/issues/81
=> Fix login from modal window

CHANGELOG-DEV.md, protected/humhub/modules/space/behaviors/SpaceModelMembership.php, protected/humhub/modules/space/widgets/SpaceDirectoryIcons.php
Issue: https://github.com/humhub/humhub/issues/6415
=> Fix caching keys on space directory

CHANGELOG-DEV.md, protected/humhub/libs/Html.php, protected/humhub/modules/space/modules/manage/views/security/permissions.php, protected/humhub/modules/user/widgets/PermisionGridModuleFilter.php
Issue: https://github.com/humhub/humhub-internal/issues/83
=> Fix width of select2 dropdown inputs

CHANGELOG-DEV.md, protected/humhub/modules/space/notifications/ApprovalRequest.php, protected/humhub/modules/space/tests/codeception/acceptance/RequestMembershipCest.php
=> Link notification for pending space approval to manage page

CHANGELOG-DEV.md, protected/humhub/modules/user/models/Profile.php
https://github.com/humhub/humhub/issues/6403
=> Translation for custom profile field is served from wrong file

protected/humhub/modules/admin/widgets/InstalledModuleControls.php, protected/humhub/modules/marketplace/services/FilterService.php, protected/humhub/modules/marketplace/widgets/ModuleFilters.php
Issue: https://github.com/humhub/humhub-internal/issues/87#issuecomment-1636099212
=> Allow to filter marketplace by module ID

CHANGELOG-DEV.md, MIGRATE-DEV.md, protected/humhub/modules/content/controllers/ContentController.php, protected/humhub/modules/content/models/Content.php
Issue: https://github.com/humhub/humhub/issues/6383
=> Remove permission verifying from archive methods

CHANGELOG-DEV.md, protected/humhub/modules/stream/resources/js/humhub.stream.wall.js, protected/humhub/modules/stream/widgets/WallStreamFilterNavigation.php, protected/humhub/modules/stream/widgets/views/wallStreamFilterNavigation.php, protected/humhub/modules/ui/filter/resources/js/humhub.ui.filter.js, protected/humhub/modules/ui/filter/widgets/FilterNavigation.php
Issue: https://github.com/humhub/humhub/issues/6439
=> Add collapsible filter state in URL

CHANGELOG-DEV.md, protected/humhub/modules/admin/models/GroupSearch.php, protected/humhub/modules/user/widgets/PeopleFilters.php
Issue: https://github.com/humhub/humhub/issues/6440
=> Sort user groups by `group.sort_order` and alphabetically

CHANGELOG-DEV.md, protected/humhub/modules/user/views/account/delete.php
Issue https://github.com/humhub/humhub/issues/6454
=> Enh #6454: Account deletion confirmation

CHANGELOG.md, protected/humhub/modules/content/models/Content.php, protected/humhub/modules/content/services/ContentStateService.php
Issue: https://github.com/humhub/humhub/issues/6433#issuecomment-1645523043
=> Avoid duplicate activities on save published content

protected/humhub/modules/content/resources/js/humhub.ui.richtext.prosemirror.js
=> Fix #113: Header anchors lost

protected/humhub/modules/marketplace/widgets/MarketplaceLink.php
Issue: https://github.com/humhub/humhub/issues/6468
=> Fix marketplace link when no URL rewriting

protected/humhub/modules/marketplace/views/browse/index.php
Issue: https://github.com/humhub/humhub-internal/issues/80
=> Info text for Marketplace page

CHANGELOG-DEV.md, protected/humhub/components/SettingsManager.php, protected/humhub/modules/admin/models/forms/MailingSettingsForm.php, protected/humhub/tests/codeception/unit/components/SettingsManagerTest.php
Issue: https://github.com/humhub/humhub-internal/issues/95
=> Implement conditions for `fixed-settings` in config

CHANGELOG-DEV.md, protected/humhub/modules/user/services/IsOnlineService.php, protected/humhub/modules/user/widgets/Image.php, protected/humhub/modules/user/widgets/views/accountTopMenu.php, static/less/topbar.less, themes/HumHub/css/theme.css
Issue https://github.com/humhub/humhub-internal/issues/68
=> Enh #68: Online Indicator Position

static/js/humhub/humhub.client.js, static/js/humhub/humhub.ui.modal.js
Bug created in the PR https://github.com/humhub/humhub/pull/6494, because form data is not posted after submit a form from modal window.
=> Fix submit form in modal window

CHANGELOG.md, protected/humhub/modules/file/models/File.php
Issue: https://github.com/humhub/humhub-internal/issues/96#issuecomment-1668538517
=> Never delete original file on store new version

protected/humhub/config/web.php
=> Remove PHP 7.3 version check in config

CHANGELOG.md, protected/humhub/modules/space/widgets/MembershipButton.php, protected/humhub/modules/space/widgets/views/membershipButton.php, protected/humhub/modules/space/widgets/views/profileHeaderControls.php
Issue: https://github.com/humhub/humhub/issues/6507
=> Reload page after accepting of invite in Space header

CHANGELOG-DEV.md, protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
=> Convert assert* and db* methods to `static`, in line with general usage pattern

CHANGELOG-DEV.md
fix missing entry
- Fix #6451
number)
=> Fix: CHANGELOG-DEV.md

CHANGELOG-DEV.md, protected/humhub/modules/content/models/Content.php
Issue: https://github.com/humhub/humhub/issues/6337
=> Update `created_at` after first publishing of content record

CHANGELOG.md, protected/humhub/modules/space/models/AdvancedSettings.php
https://github.com/humhub/humhub/issues/6435
=> Cannot change Homepage of space in PHP 8.x

CHANGELOG.md, protected/humhub/compat/HForm.php
Issue: https://github.com/humhub/team_tasks/issues/309
=> Fix overriding of loaded value with default value on HForm

CHANGELOG.md, protected/humhub/modules/ui/commands/ThemeController.php
Issue: https://github.com/humhub/humhub/issues/6556
=> Fix command `theme/switch`

CHANGELOG.md, protected/humhub/modules/admin/widgets/Modules.php
Issue: https://github.com/humhub/humhub/issues/6557
=> Fix not initialized groups array on the module administration

CHANGELOG-DEV.md, protected/humhub/components/Module.php, protected/humhub/models/ModuleEnabled.php
=> Enh: perfomance improvements

CHANGELOG-DEV.md, protected/humhub/components/Migration.php
=> Fix: Migration's transaction with invalid savepoint

protected/humhub/modules/content/components/ContentContainerActiveRecord.php, protected/humhub/modules/content/models/ContentContainer.php, protected/humhub/modules/space/models/Space.php, protected/humhub/modules/user/models/User.php
For the following classes ...
- `ContentContainer`
- `ContentContainerActiveRecord`
- `Space`
- `User`
... fix some annotated properties and return types by ...
- correcting types
- removing redundancies (based on inheritance)
- adding missing properties
- Bugfix
###Does this PR introduce a breaking change?
- No
=> Fix: contentcontainer related property annotations

CHANGELOG-DEV.md, protected/humhub/modules/space/widgets/HeaderCounterSet.php
Issue https://github.com/humhub/humhub/issues/6572
=> Fix #6572: Posts count in space should be only for published content

composer.lock
Issue: https://github.com/humhub/humhub-internal/issues/106
=> Revert "Updated Composer Dependencies"

protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/admin/models/forms/UserEditForm.php, protected/humhub/modules/user/models/User.php
Fix small wrong using of user scenarios during review the PR https://github.com/humhub/rest/pull/140
=> Fix using of user scenarios

CHANGELOG.md, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/admin/models/forms/UserEditForm.php, protected/humhub/modules/user/components/User.php, protected/humhub/modules/user/models/GroupUser.php, protected/humhub/modules/user/models/Profile.php, protected/humhub/modules/user/models/User.php, protected/humhub/modules/user/services/AuthClientUserService.php
Issue: https://github.com/humhub/rest/pull/140#discussion_r1330402345
=> Refactor user edit form in backoffice

protected/humhub/modules/admin/models/forms/StatisticSettingsForm.php
https://github.com/humhub/team_tasks/issues/314
=> Hint for setting "HTML tracking code"

CHANGELOG-DEV.md, protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub/issues/6585
=> Exclude database views on self checking

protected/humhub/modules/file/models/File.php
This PR contains code cleanup and code optimizations that are common to the new file column PRs:
- #6591
- #6592
- #6593
- #6594
- Code style update
- No
=> Enh: `file` fields: code cleanup and optimization

CHANGELOG-DEV.md, protected/humhub/modules/file/migrations/m230618_135511_file_add_state_column.php, protected/humhub/modules/file/models/File.php
Adds `state` field to `File` table/model.
- Feature
- No
Depends on/includes:
- #6590
=> Enh: `file` fields: `state`

CHANGELOG-DEV.md, protected/humhub/modules/file/migrations/m230618_135509_file_add_category_column.php, protected/humhub/modules/file/models/File.php
Adds `category` field to `File` table/model.
- Feature
- No
Depends on/includes:
- #6590
=> Enh: `file` fields: `category`

CHANGELOG.md, protected/humhub/modules/content/widgets/richtext/AbstractRichTextEditor.php
Issue: https://github.com/humhub/humhub/issues/6596
=> Fix duplicate error and hint for RichText editor with defined form

CHANGELOG.md, protected/humhub/modules/file/actions/DownloadAction.php
Issue: https://github.com/humhub/humhub/issues/6595
=> Fix mimetype of converted preview svg file to png after uploading

protected/humhub/tests/codeception/_support/HumHubHelperTrait.php
- there was a method gone missing in #6588 
- also adding some documentation
=> Hotfix: backport assert events

CHANGELOG-DEV.md, protected/humhub/config/__autocomplete.php, protected/humhub/exceptions/InvalidArgumentExceptionTrait.php, protected/humhub/libs/StdClass.php, protected/humhub/libs/StdClassConfig.php, protected/humhub/libs/StdClassConfigurable.php, protected/humhub/modules/file/libs/Metadata.php, protected/humhub/modules/file/migrations/m230618_135510_file_add_metadata_column.php, protected/humhub/modules/file/models/File.php, protected/humhub/modules/file/tests/codeception/unit/MetadataTest.php, protected/humhub/tests/codeception/unit/libs/StdClassTest.php
Adds `metadata` field to `File` table/model.
- Feature
- No
Depends on/includes:
- #6590
=> Enh: `file` fields: `metadata`

CHANGELOG-DEV.md, protected/humhub/modules/marketplace/widgets/Settings.php
Issue: https://github.com/humhub/humhub-internal/issues/110
=> Add a link to "Module Administration" from Marketplace

CHANGELOG-DEV.md, protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub-internal/issues/116
=> Add self test check: "Mobile App - Push Service"

CHANGELOG.md, protected/humhub/modules/space/resources/js/humhub.space.chooser.js
Issue: https://github.com/humhub/humhub-internal/issues/115
=> Fix visibility of new message counter on space chooser

CHANGELOG-DEV.md, protected/humhub/modules/content/migrations/m231024_062218_content_was_published.php, protected/humhub/modules/content/models/Content.php, protected/humhub/modules/content/services/ContentStateService.php
Issue: https://github.com/humhub/news/issues/67#issuecomment-1775259496
=> Content state flag "was published"

CHANGELOG.md, protected/humhub/modules/dashboard/stream/DashboardStreamQuery.php, protected/humhub/modules/stream/models/ContentContainerStreamQuery.php, protected/humhub/modules/stream/models/StreamQuery.php, protected/humhub/modules/stream/tests/codeception/unit/StreamQueryTest.php, protected/humhub/modules/user/stream/ProfileStreamQuery.php
Issue: https://github.com/humhub/news/issues/68#issuecomment-1777414961
=> Fix visibility of top sorted stream entries on dashboard from external filters

protected/humhub/modules/admin/components/Controller.php
Issue: https://github.com/humhub/humhub-internal/issues/113#issuecomment-1780908909
=> Fix visibility of the admin method `Controller::getAccessRules()`

CHANGELOG-DEV.md, protected/humhub/modules/user/components/PermissionManager.php
Issue: https://github.com/humhub/wiki/issues/297
=> Refresh cache after set a permission

CHANGELOG.md, protected/humhub/modules/file/resources/js/humhub.file.js
Issue: https://github.com/humhub/mail/issues/357
=> File dropdown not visible at the bottom of the page

CHANGELOG.md, protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextEmailHtmlConverterTest.php, protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextHtmlConverterTest.php, protected/humhub/modules/content/widgets/richtext/converter/BaseRichTextConverter.php, protected/humhub/modules/content/widgets/richtext/converter/RichTextToEmailHtmlConverter.php, protected/humhub/modules/content/widgets/richtext/converter/RichTextToHtmlConverter.php, protected/humhub/modules/content/widgets/richtext/extensions/link/LinkParserBlock.php
Issue: https://github.com/humhub/humhub/issues/6639
=> Apply image inline styles in email message

CHANGELOG.md, protected/humhub/modules/tour/views/tour/welcome.php
Issue: https://github.com/humhub/humhub/issues/6649
=> Fix birthday format on welcome page

.htaccess.dist, CHANGELOG-DEV.md
Issue: https://github.com/humhub/humhub/issues/6650
=> Enh #6650: Add assets GZIP compression with Apache

CHANGELOG.md, protected/humhub/modules/tour/controllers/TourController.php, protected/humhub/modules/tour/views/tour/welcome.php
Issue: https://github.com/humhub/humhub/issues/6652
=> Fix profile update on welcome page

CHANGELOG.md, static/js/humhub/humhub.cards.js
Issue: https://github.com/humhub/humhub-internal/issues/120
=> Fix people and space filters

CHANGELOG.md, protected/humhub/modules/content/tests/codeception/acceptance/DraftCest.php, protected/humhub/modules/content/tests/codeception/acceptance/ScheduledCest.php, protected/humhub/modules/stream/models/filters/DraftContentStreamFilter.php, protected/humhub/modules/stream/models/filters/ScheduledContentStreamFilter.php
Issue: https://github.com/humhub/news-issues/issues/6
=> Fix visibility of draft and scheduled content on dashboard

CHANGELOG.md, protected/humhub/components/console/Application.php, protected/humhub/components/console/UrlManager.php, protected/humhub/config/console.php, protected/humhub/libs/SafeBaseUrl.php, protected/humhub/tests/config/common.php
=> Changed console URL handling

.github/workflows/php-test.yml, CHANGELOG.md, composer.json, composer.lock, protected/humhub/modules/tour/tests/codeception/acceptance/AutoTourCest.php
Issue: https://github.com/humhub/humhub/issues/6666
=> Limit jQuery with version < 3.7.0 to avoid dropdown error

CHANGELOG.md, protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub/issues/6677
=> Do not check mobile push module in requirements check on installation

CHANGELOG.md, protected/humhub/modules/admin/controllers/SettingController.php
Issue: https://github.com/humhub/humhub/issues/6700
=> Reload theme variable `@baseTheme` after flushing cache

CHANGELOG.md, protected/humhub/modules/user/services/IsOnlineService.php, protected/humhub/modules/user/widgets/Image.php
Issue: https://github.com/humhub/humhub/issues/6694
=> Fix #6694: Remove the "Offline" tooltip when my own "Online" status is not displayed

CHANGELOG.md, protected/humhub/modules/content/widgets/StateBadge.php
=> Enh: Make state badge customizable

CHANGELOG-DEV.md, protected/humhub/modules/content/components/ContentContainerActiveRecord.php, protected/humhub/modules/content/models/ContentContainerBlockedUsers.php, protected/humhub/modules/friendship/widgets/FriendshipButton.php, protected/humhub/modules/space/controllers/MembershipController.php, protected/humhub/modules/space/widgets/HeaderControlsMenu.php, protected/humhub/modules/space/widgets/MembershipButton.php, protected/humhub/modules/user/controllers/ProfileController.php, protected/humhub/modules/user/widgets/HeaderControlsMenu.php, protected/humhub/modules/user/widgets/views/profileHeaderControls.php
Issue: https://github.com/humhub/humhub/issues/5751
=> Allow user blocking from profile page

protected/humhub/modules/space/widgets/HeaderControlsMenu.php, protected/humhub/modules/space/widgets/MembershipButton.php
https://github.com/humhub/humhub/issues/5751#issuecomment-1849622515
=> Rename button of leaving a space

.github/workflows/php-test.yml, protected/humhub/modules/tour/tests/codeception/acceptance/AutoTourCest.php
Related to https://github.com/humhub/humhub/pull/6685#issuecomment-1849590480
=> Upload codeception test output

MIGRATE-DEV.md
I've put the type restriction documentation in the wrong section
- #6693
=> Fix: migarte dev (regression from #6693)

protected/humhub/modules/tour/tests/codeception/acceptance/AutoTourCest.php
Related to https://github.com/humhub/humhub/pull/6731
=> Skip auto tour test

CHANGELOG-DEV.md, static/js/humhub/humhub.ui.topNavigation.js, static/js/humhub/humhub.ui.view.js
Issue https://github.com/humhub/humhub/issues/6725
=> Fix #6725: Allow theme without second topbar menu

CHANGELOG-DEV.md, static/js/humhub/humhub.ui.navigation.js
Issue https://github.com/humhub/humhub/issues/6721
=> Fix #6721: Top menu entries for spaces are not highlighted when clicked

CHANGELOG.md, static/js/humhub/humhub.client.js
Issue: https://github.com/humhub/humhub/issues/6708
=> Fix displaying of alert when RichText is changed on refresh a page

CHANGELOG.md, protected/humhub/modules/admin/models/forms/BasicSettingsForm.php
Issue: https://github.com/humhub/humhub/issues/6734
=> Trim Base URL on save

CHANGELOG.md, protected/humhub/libs/SafeBaseUrl.php
Issue: https://github.com/humhub/humhub/issues/6741
=> Fix no pretty url of password recovery link

protected/humhub/modules/user/components/User.php
Just a small documentation fix so IDE code completion is more accurate.
=> Document return type of `component\User::getIdentity()` as `model\User`

protected/humhub/libs/SelfTest.php
=> Fix: regression `isInstalled` (Fix #6693)

protected/humhub/modules/user/models/User.php
=> Enh: Document model\User dynamic field types

CHANGELOG-DEV.md, MIGRATE-DEV.md, protected/humhub/modules/content/components/ContentContainerModule.php
- Fix #6754
- Related #6550
- Bugfix
- Yes
=> Fix #6754 Regression due to return type (#6550)

MIGRATE-DEV.md
Another one gone missing. Sorry.
See
- https://github.com/humhub/humhub/pull/6550#issuecomment-1859715531
- #6755
=> Fix: missing documentation MIGRATE-DEV

CHANGELOG.md, protected/humhub/modules/content/components/ContentContainerPermissionManager.php
Issue: https://github.com/humhub/humhub/issues/6747
=> Fix loading of default container permissions from cache

CHANGELOG-DEV.md, protected/humhub/libs/ProfileImage.php, protected/humhub/modules/content/widgets/views/containerProfileHeader.php, protected/humhub/modules/space/widgets/views/members.php, protected/humhub/modules/user/widgets/views/peopleCard.php
Issue https://github.com/humhub/humhub-internal/issues/131
=> Enh #131: Online Indicator- People Cards, Members Snippet, My Profile

CHANGELOG.md, protected/humhub/config/common.php, protected/humhub/modules/admin/widgets/TrackingWidget.php
=> Added Twig Sandbox Extension

CHANGELOG-DEV.md, protected/humhub/modules/user/models/User.php
Issue: https://github.com/humhub/humhub-internal/issues/136
=> Lowercase user email before save

CHANGELOG-DEV.md, protected/humhub/modules/user/models/Password.php
Issue: https://github.com/humhub/humhub-internal/issues/137
=> Improve password hashing

CHANGELOG.md, protected/humhub/modules/marketplace/components/OnlineModuleManager.php, protected/humhub/modules/marketplace/models/Module.php, protected/humhub/modules/marketplace/services/FilterService.php, protected/humhub/modules/marketplace/widgets/ModuleFilters.php, protected/humhub/modules/marketplace/widgets/ModuleGroups.php
Issue: https://github.com/humhub/humhub/issues/6791
=> Fix number of filtered modules on Marketplace

CHANGELOG-DEV.md, protected/humhub/modules/marketplace/models/Module.php
Issue: https://github.com/humhub/humhub/issues/6790
=> Fix marketplace searching

CHANGELOG-DEV.md, protected/humhub/modules/user/Module.php, protected/humhub/modules/user/controllers/AuthController.php, protected/humhub/modules/user/controllers/RegistrationController.php, protected/humhub/modules/user/views/auth/login.php, protected/humhub/modules/user/views/auth/login_modal.php, protected/humhub/modules/user/views/registration/byLink.php, protected/humhub/modules/user/views/registration/index.php, protected/humhub/modules/user/widgets/AuthChoice.php
Related: https://github.com/humhub/humhub/issues/6780#issuecomment-1881296805
configuration file example
```php
return [
'container' => [
'definitions' => [
\humhub\modules\user\controllers\AuthController::class => [
'showLoginForm' => false,
'allowUserRegistrationFromAuthClientIds' => ['keycloak', 'saml']
]
]
]
];
```
=> Test Disable Login Form

CHANGELOG.md, protected/humhub/components/SocialActivity.php, protected/humhub/modules/friendship/notifications/Request.php, protected/humhub/modules/friendship/notifications/RequestApproved.php, protected/humhub/modules/friendship/notifications/RequestDeclined.php, protected/humhub/modules/space/activities/MemberAdded.php, protected/humhub/modules/user/notifications/Followed.php
Issue: https://github.com/humhub/humhub-internal/issues/140
=> Fix missed domain of profile url in email notifications

CHANGELOG-DEV.md, protected/humhub/components/behaviors/PolymorphicRelation.php
- Fix #6772
- Regression #6587
- Bugfix
- No
=> Fix: polymorphic relation lookup (Fix #6772)

CHANGELOG.md, protected/humhub/widgets/Pjax.php
- Back-porting https://github.com/humhub/humhub/pull/6713#issuecomment-1896273060
- Also see https://github.com/humhub/humhub/pull/6277#discussion_r1419548525
=> Fix: Keep string class option for Pjax Widget (#6713)

protected/humhub/tests/codeception/_support/HumHubHelper.php, protected/humhub/tests/codeception/_support/WebHelper.php, protected/humhub/tests/codeception/config/config.php
=> Removed unused test settings

CHANGELOG.md, protected/humhub/modules/user/models/fieldtype/CountrySelect.php
=> Fix: Iso3166Codes class calls

CHANGELOG.md, protected/humhub/modules/user/behaviors/Followable.php
=> Fix for displaying whether I follow a user. #6813

protected/humhub/modules/space/modules/manage/models/DeleteForm.php
https://github.com/humhub/wording/issues/131
=> Space name wording on delete

CHANGELOG-DEV.md, protected/humhub/modules/ui/widgets/DirectoryFilters.php, protected/humhub/modules/ui/widgets/views/directoryFilter.php, protected/humhub/modules/user/Module.php, protected/humhub/modules/user/components/PeopleQuery.php, protected/humhub/modules/user/tests/codeception/unit/PeopleFiltersTest.php, protected/humhub/modules/user/views/people/index.php, protected/humhub/modules/user/widgets/PeopleFilterPicker.php, protected/humhub/modules/user/widgets/PeopleFilters.php
https://github.com/humhub/humhub-internal/issues/120#issuecomment-1892505437
https://github.com/humhub/humhub/pull/6806#issuecomment-1904682427
=> Reduce people filter options depending on what filtered users have

CHANGELOG.md, protected/humhub/modules/user/components/Session.php
=> Fix Session Timeout

CHANGELOG.md, protected/humhub/modules/admin/models/UserSearch.php
Issue: https://github.com/humhub/humhub/issues/6795
=> Fix searching of disabled users in Administration

protected/humhub/modules/content/components/ContentActiveRecord.php, protected/humhub/modules/content/models/Content.php
=> Add Throwable and StaleObjectException to hardDelete method doc

protected/humhub/modules/admin/views/information/database.php
=> Fix 6819: DB Migration Button

CHANGELOG-DEV.md, protected/humhub/modules/marketplace/controllers/BrowseController.php
=> Fix: Wrong view filename after module enabling

CHANGELOG.md, protected/humhub/modules/content/models/Content.php, protected/humhub/modules/content/tests/codeception/unit/models/ContentVisibilityTest.php, protected/humhub/modules/dashboard/tests/codeception/unit/DashboardMemberStreamQueryTest.php, protected/humhub/modules/ui/form/widgets/ContentVisibilitySelect.php
https://github.com/humhub/cfiles/issues/206#issuecomment-1930601973
=> Fix saving of public content

CHANGELOG-DEV.md, protected/humhub/modules/file/resources/js/humhub.file.js
https://github.com/humhub/humhub-prosemirror/issues/121#issuecomment-1934062408
=> Use prosemirror file handler flag

protected/humhub/modules/file/resources/js/humhub.file.js, protected/humhub/widgets/CoreJsConfig.php
Related to https://github.com/humhub/humhub-prosemirror/issues/121#issuecomment-1915054602
=> Extend file URL mode for Prosemirror editor

CHANGELOG.md, protected/humhub/modules/stream/models/filters/DraftContentStreamFilter.php, protected/humhub/modules/stream/models/filters/ScheduledContentStreamFilter.php, protected/humhub/modules/stream/models/filters/StreamQueryFilter.php
Issue: https://github.com/humhub/humhub/issues/6859
=> Hide scheduled and draft content on other user profile pages

CHANGELOG.md, protected/humhub/libs/BaseSettingsManager.php
Issue https://github.com/humhub/humhub/issues/6871
=> Fix #6871: Cache is not deleted after deleting a value in the settings

CHANGELOG-DEV.md, protected/humhub/modules/user/views/people/index.php
Issue: https://github.com/humhub/humhub-internal/issues/157
=> Change people header with selected group

CHANGELOG-DEV.md, protected/humhub/components/Module.php, protected/humhub/modules/admin/controllers/ModuleController.php, protected/humhub/modules/admin/jobs/RemoveModuleJob.php
Issue https://github.com/humhub/humhub/issues/6707
=> Enh #6707: Uninstalling modules should be done in a background job

CHANGELOG.md, protected/humhub/modules/admin/models/forms/CacheSettingsForm.php, protected/humhub/modules/admin/views/setting/caching.php
=> Enh: Better support for custom caches

CHANGELOG.md, protected/humhub/modules/notification/controllers/OverviewController.php
https://github.com/humhub/humhub-internal/issues/193
=> Fix obsolete notifications

CHANGELOG.md, protected/humhub/modules/space/models/Space.php, protected/humhub/modules/user/Events.php
https://github.com/humhub/humhub-internal/issues/195
=> Fix clearing of "Follow" records on space deletion

static/js/humhub/humhub.ui.navigation.js
Issue: https://github.com/humhub/humhub-internal/issues/201
=> Fix initialization of js module `ui.navigation`

static/js/humhub/humhub.ui.search.js
Issue: https://github.com/humhub/humhub-internal/issues/204
=> Meta search: Hide provider on error from server side

CHANGELOG-DEV.md, protected/humhub/modules/content/tests/codeception/unit/search/AbstractDriverTestSuite.php
https://github.com/humhub/humhub-internal/issues/208
=> Content Search: Add Tests regarding `state`

CHANGELOG-DEV.md, protected/humhub/modules/content/widgets/richtext/AbstractRichTextEditor.php
https://github.com/humhub/mail/issues/383
=> Fix default mentioning URL

CHANGELOG.md, protected/humhub/components/Module.php, protected/humhub/modules/ldap/module.json
https://github.com/humhub/humhub/issues/6899
=> Fix a missed module config file

CHANGELOG-DEV.md, protected/humhub/tests/codeception/_support/HumHubApiTestCest.php
https://github.com/humhub/humhub-internal/issues/191#issuecomment-2028874738
=> Fix API tests

protected/humhub/modules/user/models/Invite.php
=> Add missing `originator` property in the documentation of the `user`module `Invite` class

CHANGELOG.md, protected/humhub/tests/codeception/_support/HumHubApiTestCest.php
Related to https://github.com/humhub/humhub/pull/6913
=> Fix API tests (#6913)

CHANGELOG-DEV.md, protected/humhub/modules/user/controllers/AuthController.php, protected/humhub/modules/user/controllers/RegistrationController.php, protected/humhub/modules/user/models/Invite.php, protected/humhub/modules/user/services/LinkRegistrationService.php, protected/humhub/modules/user/views/mails/UserInviteSelf.php
Issue https://github.com/humhub/humhub/issues/6730
=> Fix #6730: Invitation link for existing user

protected/config/common.php, protected/config/console.php, protected/config/web.php
**Code comment update**
The previous links lead to a 404 page.
=> Update links in config files

protected/humhub/modules/space/widgets/SpaceDirectoryIcons.php
https://github.com/humhub/humhub-internal/issues/219
=> Fix space member count

protected/humhub/modules/admin/messages/de/user.php, protected/humhub/modules/user/tests/codeception/unit/ApproveUserFormTest.php
https://github.com/humhub/humhub-internal/issues/218
=> Fix wording for tests

protected/humhub/modules/stream/resources/js/humhub.stream.SimpleStream.js
Related to https://github.com/humhub/humhub/pull/6925
=> Fix content searching when page is short so scroll down indicator is not triggered

CHANGELOG-DEV.md, protected/humhub/modules/ldap/authclient/LdapAuth.php
=> Fixed disabled users

protected/humhub/modules/space/search/SpaceSearchProvider.php, protected/humhub/modules/user/search/UserSearchProvider.php
Fix url of link "Show all results" to People and Spaces when config `'enablePrettyUrl' => false`.
=> Fix search provider full URLs when pretty URL is disabled

CHANGELOG-DEV.md, protected/humhub/components/ApplicationTrait.php, protected/humhub/helpers/ArrayHelper.php, protected/humhub/libs/SelfTest.php
=> Added handling for legacy configuration file options

CHANGELOG-DEV.md, protected/humhub/modules/content/jobs/SearchDeleteDocument.php, protected/humhub/modules/content/jobs/SearchRebuildIndex.php, protected/humhub/modules/content/jobs/SearchUpdateDocument.php, protected/humhub/modules/content/services/SearchJobService.php
https://github.com/humhub/humhub/issues/5419
=> Lock search index while reindexing

CHANGELOG.md, protected/humhub/modules/content/components/AbstractActiveQueryContentContainer.php, protected/humhub/modules/space/components/ActiveQuerySpace.php, protected/humhub/modules/user/components/ActiveQueryUser.php, protected/humhub/modules/user/models/fieldtype/CountrySelect.php
https://github.com/humhub/humhub/issues/6919
=> Fix saving of user profile country field value

CHANGELOG-DEV.md, protected/humhub/components/Module.php
https://github.com/humhub/humhub/issues/6944
=> Fix the marketplace searching when a module config file has missed fields

CHANGELOG-DEV.md, protected/humhub/modules/content/widgets/ContainerProfileHeader.php, protected/humhub/modules/content/widgets/views/containerProfileHeader.php
https://github.com/humhub/humhub/issues/6952
=> Improve container title encoding in header

static/js/humhub/humhub.ui.search.js
https://github.com/humhub/humhub/issues/6953
=> Fix search out of viewport on mobile

CHANGELOG-DEV.md, protected/humhub/modules/user/widgets/PeopleFilters.php
https://github.com/humhub/humhub/issues/6962
=> People filter - Hide follower options if Following is disabled in the User module

CHANGELOG.md, protected/humhub/modules/like/migrations/m240425_144905_unique_index.php, protected/humhub/modules/like/models/Like.php
https://github.com/humhub/humhub-internal/issues/226
=> Create unique index for the table `like`

CHANGELOG-DEV.md, protected/humhub/modules/ui/form/widgets/MultiSelect.php
https://github.com/humhub/humhub/commit/dd2d23058dbffa53fd1718123f9f61c9b79588fe#r141253611
=> Fix: MultiSelect loads wrong options

protected/humhub/modules/ui/form/widgets/IconPicker.php
=> Fix IconPicker widget if value is null with PHP 8

CHANGELOG-DEV.md, protected/humhub/modules/comment/resources/js/humhub.comment.js, protected/humhub/modules/comment/widgets/ShowMore.php, protected/humhub/modules/comment/widgets/views/showMore.php, protected/humhub/modules/content/views/search/_layout.php
https://github.com/humhub/humhub-internal/issues/227#issuecomment-2079689534
=> Highlight a content searching keyword on show more comments

CHANGELOG-DEV.md, protected/humhub/modules/content/services/ContentSearchService.php
https://github.com/humhub/humhub-internal/issues/233
=> Index sub comments for searching

CHANGELOG-DEV.md, protected/humhub/modules/marketplace/services/ModuleService.php
https://github.com/humhub/humhub/issues/6978
=> Fix module enabling from marketplace

CHANGELOG-DEV.md, protected/humhub/modules/content/Events.php, protected/humhub/modules/content/assets/ContentHighlightAsset.php, protected/humhub/modules/content/config.php, protected/humhub/modules/content/controllers/PermaController.php, protected/humhub/modules/content/resources/js/humhub.content.highlight.js, protected/humhub/modules/content/search/ContentSearchProvider.php, protected/humhub/modules/content/search/SearchRecord.php, static/js/humhub/humhub.ui.search.js
https://github.com/humhub/humhub-internal/issues/158
=> Meta search: Highlight keyword in single content view

MIGRATE-DEV.md, composer.json, composer.lock, protected/humhub/components/export/SpreadsheetExport.php
=> Enh: Migrate phpspreadsheet 2.0

CHANGELOG.md, protected/humhub/modules/user/widgets/AuthChoice.php, static/resources/user/authChoice.css, static/resources/user/authChoice.js
https://github.com/humhub/humhub-internal/issues/258#issuecomment-2115895368
=> Fix opening more auth clients

CHANGELOG-DEV.md, protected/humhub/modules/ui/view/components/View.php, protected/humhub/views/layouts/main.php
Issue https://github.com/humhub/humhub/issues/5310
=> Enh #5310: Mobile - Zooming into pictures

CHANGELOG-DEV.md, protected/humhub/modules/ui/widgets/DirectoryFilters.php
https://github.com/humhub/humhub/issues/7007
=> Allow resetting of people filters

CHANGELOG-DEV.md, protected/humhub/components/ApplicationTrait.php
=> Fix: Exception 'yii\base\InvalidConfigException' with message 'Unsupported configuration type: object'

CHANGELOG.md, protected/humhub/modules/user/controllers/AuthController.php
=> Fixed auto mapping user

CHANGELOG-DEV.md, protected/humhub/modules/user/migrations/m240523_081438_fix_null_password.php, protected/humhub/modules/user/models/Password.php
https://github.com/humhub/humhub-internal/issues/258#issuecomment-2125005826
=> Fix empty password

protected/humhub/modules/ui/widgets/DirectoryFilters.php, protected/humhub/modules/user/widgets/PeopleFilterPicker.php
https://github.com/humhub/humhub/issues/7007#issuecomment-2125137292
=> Set placeholder "Select" for all people dropdown filters

protected/humhub/modules/content/tests/codeception/unit/search/AbstractDriverTestSuite.php, protected/humhub/modules/content/tests/codeception/unit/search/ZendLucenceDriverTest.php
https://github.com/humhub/solr/pull/11#pullrequestreview-2077130202
=> Add tests for search URL in content

CHANGELOG-DEV.md, protected/humhub/modules/content/search/driver/MysqlDriver.php, protected/humhub/modules/content/search/driver/ZendLucenceDriver.php, protected/humhub/modules/content/tests/codeception/unit/search/MysqlDriverTest.php
=> Enh: Add search tests

CHANGELOG-DEV.md, protected/humhub/modules/marketplace/Events.php, protected/humhub/modules/marketplace/config.php, protected/humhub/modules/marketplace/search/MarketplaceSearchProvider.php, protected/humhub/modules/marketplace/search/SearchRecord.php
https://github.com/humhub/humhub-internal/issues/203
=> Marketplace meta search provider

static/js/humhub/humhub.ui.search.js
https://github.com/humhub/app-internal/issues/28
=> Fix meta search panel position

CHANGELOG.md, protected/humhub/modules/activity/Events.php, protected/humhub/modules/activity/config.php, protected/humhub/modules/activity/tests/codeception/unit/ActivityTest.php, protected/humhub/modules/content/models/Content.php
https://github.com/humhub/humhub-internal/issues/263
=> Update visibility of activities according to the parent object

CHANGELOG.md, protected/humhub/modules/content/components/ContentContainerSettingsManager.php
https://github.com/humhub/humhub-internal/issues/265
=> Fix container setting for broken records

protected/humhub/modules/content/components/ContentContainerModuleManager.php
https://github.com/humhub/humhub-internal/issues/265#issuecomment-2154492616
=> Fix container module setting for record with broken `contentcontainer_id`

CHANGELOG-DEV.md, protected/humhub/modules/content/search/driver/MysqlDriver.php
https://github.com/humhub/humhub/issues/2610
=> Search content by ID (mysql driver)

protected/humhub/modules/admin/controllers/UserController.php
https://github.com/humhub/humhub-internal/issues/280
=> Fix saving of empty password by admin

composer.json, composer.lock, protected/humhub/modules/content/helpers/EmojiHelper.php, protected/humhub/modules/content/widgets/richtext/converter/RichTextToEmailHtmlConverter.php, protected/humhub/modules/content/widgets/richtext/converter/RichTextToPlainTextConverter.php, protected/humhub/modules/notification/targets/MailTarget.php
https://github.com/humhub/team_tasks/issues/343
=> Render emojis in email content

CHANGELOG.md, protected/humhub/libs/SelfTest.php
https://github.com/humhub/humhub-internal/issues/287
=> Improve handling of legacy configuration for "search" component

CHANGELOG.md, protected/humhub/modules/user/views/registration/byLink.php
=> Fix: Missing closing div HTML tag in the registration by link view

protected/humhub/modules/content/widgets/ContentTagPicker.php
https://github.com/humhub/humhub-internal/issues/270#issuecomment-2197093835
=> Display color box for searched content tags

CHANGELOG.md, protected/humhub/modules/content/search/driver/MysqlDriver.php
https://github.com/humhub/humhub/issues/7102
=> Fix content search with word ending with hyphen

CHANGELOG.md, Gruntfile.js
=> Fix rebuilding the search index with Grunt (since 1.16.0)

protected/humhub/modules/content/migrations/m240715_150726_fulltext_index.php
https://github.com/humhub/humhub/issues/7119
=> Fix after failed migration of content fulltext index

CHANGELOG.md, protected/humhub/libs/UrlOembedHttpClient.php
https://github.com/humhub/humhub/issues/6794
=> Improve log wrong parsing of OEmbed URL

CHANGELOG.md, protected/humhub/libs/SelfTest.php
https://github.com/humhub/humhub/issues/7098
=> Add a warning if we have a mix of different collations

CHANGELOG.md, protected/humhub/commands/CronController.php, protected/humhub/libs/SelfTest.php
https://github.com/humhub/humhub/issues/7111
=> Prerequisites - check for mixed php version/user

CHANGELOG.md, protected/humhub/modules/space/services/MemberListService.php, protected/humhub/modules/space/widgets/SpaceDirectoryIcons.php
https://github.com/humhub/humhub-internal/issues/311
=> Fix member count on a space directory

CHANGELOG.md, protected/humhub/libs/UrlOembedHttpClient.php, protected/humhub/migrations/m220121_193617_oembed_setting_update.php, protected/humhub/tests/codeception/fixtures/data/setting.php
https://github.com/humhub/humhub/issues/6794
=> Add `User-Agent` to oEmbed CURL request (fix for Reddit)

CHANGELOG.md, protected/humhub/modules/user/models/Invite.php
https://github.com/humhub/rest/issues/161
=> REST Endpoint for pending invites - Extended response

CHANGELOG.md, static/js/humhub/humhub.ui.search.js
https://github.com/humhub/humhub/issues/7141
=> Fix meta searching twice for the same keyword

CHANGELOG.md, protected/humhub/modules/content/search/SearchRequest.php, protected/humhub/modules/content/search/driver/MysqlDriver.php, protected/humhub/modules/content/search/driver/ZendLucenceDriver.php, protected/humhub/modules/content/tests/codeception/unit/search/AbstractDriverTestSuite.php
https://github.com/humhub/wiki/issues/344
=> Fix search request by container guid

CHANGELOG.md, protected/humhub/helpers/DeviceDetectorHelper.php, protected/humhub/modules/ui/helpers/DeviceDetectorHelper.php, protected/humhub/modules/user/components/User.php
See https://github.com/humhub/app/issues/188#issuecomment-2258721321
=> Add device detector

CHANGELOG.md, protected/humhub/modules/post/controllers/PostController.php, protected/humhub/modules/post/models/Post.php
https://github.com/humhub/humhub/issues/6870
=> Disable post message required validation when post has attached files

CHANGELOG.md, protected/humhub/modules/space/Events.php, protected/humhub/modules/space/widgets/Chooser.php
https://github.com/humhub/humhub-internal/issues/323
=> Fix duplicated following spaces in the chooser widget

CHANGELOG.md, protected/humhub/modules/content/assets/ContentHighlightAsset.php, protected/humhub/modules/content/resources/js/humhub.content.highlight.js
https://github.com/humhub/humhub-internal/issues/321#issuecomment-2273554260
=> Highlight content after open a page from search results

protected/humhub/modules/content/assets/ContentHighlightAsset.php
https://github.com/humhub/humhub-internal/issues/321#issuecomment-2275955549
=> Fix highlight content after open a page from search results

CHANGELOG.md, protected/humhub/modules/content/widgets/richtext/converter/RichTextToEmailHtmlConverter.php
https://github.com/humhub/humhub-internal/issues/334
=> Fix rendering of new line on email messages

CHANGELOG.md, protected/humhub/modules/marketplace/models/Module.php, protected/humhub/modules/marketplace/services/FilterService.php, protected/humhub/modules/marketplace/widgets/ModuleActionButtons.php, protected/humhub/modules/marketplace/widgets/ModuleStatus.php
https://github.com/humhub/humhub-internal/issues/322#issuecomment-2289139041
=> Fix marketplace module label "Professional Edition"

CHANGELOG.md, protected/humhub/modules/space/permissions/CreatePrivateSpace.php, protected/humhub/modules/space/permissions/CreatePublicSpace.php, protected/humhub/modules/user/components/PermissionManager.php
https://github.com/humhub/humhub-internal/issues/337
=> Fix broken tests

CHANGELOG.md, static/js/humhub/humhub.ui.additions.js
https://github.com/humhub/humhub-internal/issues/339
=> Highlight only words with 3 or more characters

CHANGELOG.md, static/js/humhub/humhub.ui.additions.js
https://github.com/humhub/humhub-internal/issues/325#issuecomment-2304251519
=> Fix initialization of several select2 inputs on the same page

CHANGELOG.md, protected/humhub/compat/HForm.php
https://github.com/humhub/humhub-internal/issues/340
=> Fix duplicated label of checkbox profile field

CHANGELOG.md, protected/humhub/modules/admin/views/user/edit.php
https://github.com/humhub/humhub-internal/issues/325#issuecomment-2304685328
=> Fix active form on user edit form for correct working of widget inputs

protected/humhub/modules/content/components/ContentActiveRecord.php
https://github.com/humhub/meeting/issues/41#issuecomment-2311947955
https://github.com/humhub/humhub/pull/6612
=> Add `@since` tag for `ContentActiveRecord::getSearchAttributes()`

CHANGELOG.md, static/js/humhub/humhub.ui.additions.js
https://github.com/humhub/humhub/issues/7152
=> Fix search starting with special characters

protected/humhub/modules/space/widgets/views/myMembership.php
https://github.com/humhub/humhub/issues/7162
=> Translate space member role

CHANGELOG.md, protected/humhub/modules/content/Events.php, protected/humhub/modules/content/commands/SearchController.php, protected/humhub/modules/content/config.php, protected/humhub/modules/content/jobs/SearchDeleteDocument.php, protected/humhub/modules/content/search/driver/AbstractDriver.php, protected/humhub/modules/content/search/driver/MysqlDriver.php, protected/humhub/modules/content/search/driver/ZendLucenceDriver.php, protected/humhub/modules/content/services/ContentSearchService.php
https://github.com/humhub/humhub-internal/issues/344
=> Fix search reindexing after content deletion

CHANGELOG.md, protected/humhub/modules/user/views/registration/index.php
https://github.com/humhub/humhub-internal/issues/325#issuecomment-2317307767
https://github.com/humhub/humhub/pull/7180
=> Fix active form on registration form for correct working of widget inputs

CHANGELOG.md, protected/humhub/modules/content/search/SearchRecord.php
https://github.com/humhub/humhub/issues/7148
=> Improve rendering of meta search content

CHANGELOG.md, protected/humhub/modules/content/widgets/ContainerModule.php, protected/humhub/modules/content/widgets/views/container-module.php
https://github.com/humhub/humhub-internal/issues/350
=> Fix module description for space and user

CHANGELOG.md, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/admin/views/user/add.php, protected/humhub/modules/user/controllers/InviteController.php, protected/humhub/modules/user/models/forms/Invite.php, protected/humhub/modules/user/views/invite/index.php
https://github.com/humhub/humhub-internal/issues/355
=> Make "Invite new people" always possible for user with permission "Manage Users"

CHANGELOG.md, protected/humhub/modules/web/pwa/widgets/LayoutHeader.php
`<meta name="apple-mobile-web-app-capable" content="yes">` is deprecated. Please include `<meta name="mobile-web-app-capable" content="yes">`
=> Fix: Deprecated Meta tag

CHANGELOG.md, protected/humhub/modules/content/components/ContentContainerModuleManager.php
https://github.com/humhub/humhub-internal/issues/370
=> Fix visibility of wall stream content creating form

CHANGELOG.md, protected/humhub/modules/user/migrations/m240916_150536_extend_language.php, protected/humhub/modules/user/models/Invite.php, protected/humhub/modules/user/models/User.php
https://github.com/humhub/humhub-internal/issues/374
=> Increase language column size for new language codes

CHANGELOG.md, protected/humhub/modules/user/Events.php, protected/humhub/modules/user/Module.php, protected/humhub/modules/user/config.php, protected/humhub/modules/user/jobs/CleanupInvites.php
https://github.com/humhub/humhub/issues/7179
=> Cleanup UserInvites after X days

CHANGELOG.md, protected/humhub/modules/ui/view/components/View.php
https://github.com/humhub/humhub-internal/issues/104
=> Fix module JS config initialisation on AJAX request

CHANGELOG.md, protected/humhub/modules/content/services/ContentSearchService.php
https://github.com/humhub/custom-pages/issues/347
=> Fix search reindexing after create new content

CHANGELOG.md, index.php
https://github.com/humhub/humhub-internal/issues/404
=> .env change - Installer - PHP Warnings

CHANGELOG.md, protected/humhub/widgets/PoweredBy.php
https://github.com/humhub/humhub-internal/issues/397
=> Changed PoweredBy URL

CHANGELOG.md, protected/humhub/modules/file/models/File.php
https://github.com/humhub/custom-pages/issues/349
=> Fix file visibility for object with viewable interface

CHANGELOG.md, protected/humhub/modules/space/Events.php, protected/humhub/modules/space/config.php, protected/humhub/modules/space/widgets/Menu.php
https://github.com/humhub/humhub-internal/issues/410
=> Move "About" into Space Control Menu

protected/humhub/modules/space/tests/codeception/acceptance/AdvancedSettingsCest.php, protected/humhub/modules/space/tests/codeception/acceptance/SpaceCest.php
https://github.com/humhub/humhub-internal/issues/410#issuecomment-2414673507
=> Fix tests after moving "About" into Space Control Menu

CHANGELOG.md, protected/humhub/modules/like/Module.php
https://github.com/humhub/humhub-internal/issues/419
=> Disable "Like" on archived content

CHANGELOG.md, protected/humhub/modules/ui/menu/MenuEntry.php
https://github.com/humhub/humhub-internal/issues/277
=> Improve `MenuEntry::isActiveState` to support query params check

protected/humhub/components/ApplicationTrait.php, protected/humhub/helpers/ControllerHelper.php, protected/humhub/libs/TimezoneHelper.php
https://github.com/humhub/humhub-internal/issues/386
=> Fix unknown time zone on a database server

CHANGELOG.md, protected/humhub/modules/user/views/profile/about.php
Issue https://github.com/humhub/humhub/issues/7265
=> Enh #7265: Profile About page: don't display the menu if only one entry

protected/humhub/modules/installer/views/config/localisation.php
https://github.com/humhub/humhub-internal/issues/425
=> Set time zone from browser on installer

CHANGELOG.md, MIGRATE-DEV.md, protected/humhub/modules/user/Module.php, protected/humhub/modules/user/models/Password.php, protected/humhub/modules/user/models/forms/Login.php
Issue https://github.com/humhub/humhub/issues/5423
=> Enh #5423: Display password rules in form field hint

protected/humhub/modules/user/models/forms/Login.php
Issue https://github.com/humhub/humhub/pull/7272#issuecomment-2431115344
=> Remove password hint on the login - since PR 7272

CHANGELOG.md, protected/humhub/modules/dashboard/stream/filters/DashboardGuestStreamFilter.php
https://github.com/humhub/humhub-internal/issues/387
=> Restrict guest content

CHANGELOG.md, static/js/humhub/humhub.ui.search.js
https://github.com/humhub/humhub/issues/6947#issuecomment-2439347221
=> Don't remove html tags by JS from search post record because it is done by PHP

CHANGELOG.md, protected/humhub/modules/space/models/forms/InviteForm.php, protected/humhub/modules/space/widgets/views/inviteModal.php
https://github.com/humhub/humhub-internal/issues/423
=> Allow to add a space as default for new users from "Invite members" modal window

protected/humhub/libs/SelfTest.php
https://github.com/humhub/humhub/issues/7282
=> Fix self test for "Mobile App - Push Service"

protected/humhub/modules/space/models/forms/InviteForm.php, protected/humhub/modules/user/tests/codeception/functional/LinkInviteCest.php
https://github.com/humhub/humhub/pull/7280#issuecomment-2447804351
=> Fix tests with form to invite users to a space

CHANGELOG.md, protected/humhub/modules/content/components/ContentTagActiveQuery.php, protected/humhub/modules/content/models/ContentTag.php, protected/humhub/modules/content/widgets/ContentTagPicker.php
https://github.com/humhub/calendar/issues/509#issuecomment-2447390181
=> Content tag visibility

CHANGELOG.md, protected/humhub/libs/SelfTest.php, protected/humhub/modules/user/models/Profile.php, protected/humhub/modules/user/models/fieldtype/BaseType.php, protected/humhub/modules/user/models/fieldtype/Template.php
https://github.com/humhub/humhub/issues/7056
=> Virtual Profile Field Type: Template

CHANGELOG.md, composer.json, composer.lock
https://github.com/humhub/humhub-internal/issues/432#issuecomment-2454063644
=> Add Twig string extension

CHANGELOG.md, protected/humhub/modules/content/models/Content.php
Issue https://github.com/humhub/humhub/issues/7276
=> Fix #7276: Cron jobs cannot "Create public content" (since 1.15.3)

CHANGELOG.md, protected/humhub/helpers/DeviceDetectorHelper.php
Only iOS and Android mobile apps released after November 6, 2024 will be detected.
=> Fix iOS mobile app detection for iPad devices

CHANGELOG.md, protected/humhub/modules/user/models/forms/AccountChangeEmail.php, protected/humhub/modules/user/models/forms/Invite.php
https://github.com/humhub/humhub-internal/issues/442
=> Fix email validation of invite new users

CHANGELOG.md, protected/humhub/modules/live/assets/LiveAsset.php, protected/humhub/modules/live/controllers/PollController.php, protected/humhub/modules/live/resources/js/humhub.live.poll.js
https://github.com/humhub/humhub-internal/issues/411#issuecomment-2460362213
=> Auto refresh a page with obsolete nonce value

protected/humhub/modules/live/assets/LiveAsset.php
Fix a bug from PR https://github.com/humhub/humhub/pull/7297 on run `grunt build-assets`.
=> Fix build assets from console

CHANGELOG.md, protected/humhub/assets/OpenSansAsset.php
https://github.com/humhub/humhub-internal/issues/449
=> Open Sans - Hungarian Error

protected/humhub/modules/live/assets/LiveAsset.php
Issue description: https://github.com/humhub/humhub-internal/issues/411#issuecomment-2478901901
Bug after the PR https://github.com/humhub/humhub/pull/7297
=> Fix init nonce checking for Live Poll driver

CHANGELOG.md, protected/humhub/components/ApplicationTrait.php
https://github.com/humhub/mail/issues/429
=> Fix formatter default time zone

CHANGELOG.md, protected/humhub/modules/live/assets/LiveAsset.php, protected/humhub/modules/live/controllers/PollController.php, protected/humhub/modules/live/resources/js/humhub.live.js, protected/humhub/modules/live/resources/js/humhub.live.poll.js, protected/humhub/modules/live/resources/js/humhub.live.push.js, protected/humhub/modules/web/security/helpers/Security.php, protected/humhub/widgets/CoreJsConfig.php, static/js/humhub/humhub.client.js
https://github.com/humhub/humhub-internal/issues/411
=> Refresh obsolete nonce value on Live drivers

CHANGELOG.md, protected/humhub/modules/space/widgets/views/spaceDirectoryCard.php, static/less/space.less, themes/HumHub/css/theme.css
Issue https://github.com/humhub/humhub-internal/issues/456
Expends the clickable zone:
=> Enh: Space browser: Make the whole space card header and body clickable

CHANGELOG.md, protected/humhub/modules/user/models/Profile.php, protected/humhub/modules/user/models/User.php
https://github.com/humhub/humhub/issues/7319
=> Display correct profile field value in user subtitle

CHANGELOG.md, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/admin/views/user/add.php, protected/humhub/modules/user/controllers/InviteController.php, protected/humhub/modules/user/controllers/RegistrationController.php, protected/humhub/modules/user/models/forms/Invite.php, protected/humhub/modules/user/services/LinkRegistrationService.php, protected/humhub/modules/user/tests/codeception/functional/LinkInviteCest.php, protected/humhub/modules/user/views/invite/index.php
https://github.com/humhub/humhub-internal/issues/460
=> Always allow invitation by link

CHANGELOG.md, protected/humhub/components/Migration.php, protected/humhub/migrations/m131203_110444_oembed.php, protected/humhub/modules/activity/migrations/m150703_012735_typelength.php, protected/humhub/modules/notification/migrations/m150629_220311_change.php, protected/humhub/modules/stream/migrations/m170123_125622_pinned.php, protected/humhub/modules/user/migrations/m160408_100725_rename_groupadmin_to_manager.php
https://github.com/humhub/humhub-internal/issues/469
=> New safe method to rename a database column

.github/workflows/php-test.yml, CHANGELOG.md
https://github.com/humhub/humhub-internal/issues/470#issuecomment-2536521821
=> Update GitHub workflow versions

MIGRATE-DEV.md, protected/humhub/modules/content/models/Content.php
Fix for PR https://github.com/humhub/humhub/pull/7329
=> Fix MIGRATE-DEV and Content model when the user is null (e.g. in cron jobs)

.github/workflows/php-cs-fixer.yml
https://github.com/humhub/humhub-internal/issues/466
=> Create branch and Pull Request automatically for new changes from PHP CS Fixer

CHANGELOG.md, protected/humhub/modules/admin/models/forms/BasicSettingsForm.php, protected/humhub/modules/admin/views/setting/basic.php
https://github.com/humhub/humhub-internal/issues/475
=> disable fixed baseurl

CHANGELOG.md, index.php, protected/yii
https://github.com/humhub/humhub-internal/issues/477
=> Fix debug mode setting

.github/workflows/php-cs-fixer.yml
Fix [the error](https://github.com/humhub/humhub/actions/runs/12349333719/job/34459957588#step:7:21):
=> Skip creating of branch and PR if no changes from PHP CS Fixer

.php-cs-fixer.php
https://github.com/humhub/humhub-internal/issues/486
=> Don't process file "assets-prod.php" by PHP CS Fixer

CHANGELOG.md, protected/humhub/modules/user/components/PermissionManager.php
https://github.com/humhub/humhub/issues/7351
=> Fix caching of space permissions in user stream

CHANGELOG.md, index-test.php, index.php, protected/humhub/helpers/EnvHelper.php, protected/humhub/modules/web/tests/codeception/unit/env/ConfigTest.php, protected/yii
https://github.com/humhub/humhub-internal/issues/481
=> env application type

protected/humhub/libs/SelfTest.php
https://github.com/humhub/humhub-internal/issues/478
=> Fix Base URL selftest with Reverse Proxy

protected/humhub/tests/codeception/unit/widgets/TimeAgoWidgetTest.php
=> Fix whitespace in Tests output

CHANGELOG.md, protected/humhub/config/common.php, protected/humhub/helpers/DeviceDetectorHelper.php
=> Fix DeviceDetectorHelper when no user agent

protected/humhub/modules/admin/views/logging/log_entries.php
Logs of the level "trace" were shown with the red label "Error", with this PR they are shown with a grey (default color) label "Trace".
Most users won't see a change because "Trace" level logs are not activated by default.
=> Logging UI: fix label of Trace logs

protected/humhub/modules/comment/resources/js/humhub.comment.js, protected/humhub/modules/comment/widgets/Comments.php
https://github.com/humhub/humhub-internal/issues/508
=> Collapsed comments

CHANGELOG.md, protected/humhub/libs/SelfTest.php, protected/humhub/modules/installer/libs/InitialData.php
https://github.com/humhub/humhub-internal/issues/478#issuecomment-2589462235
=> Improve SelfTest for Base URL

CHANGELOG.md, protected/humhub/modules/user/controllers/InviteController.php, protected/humhub/modules/user/services/InviteRegistrationService.php, protected/humhub/modules/user/views/registration/index.php
https://github.com/humhub/humhub/issues/7375
=> Save current language for email invitation and show language chooser on registration form

CHANGELOG.md, protected/humhub/modules/user/stream/filters/IncludeAllContributionsFilter.php
https://github.com/humhub/humhub/issues/7395
=> Fix profile stream for guests

protected/humhub/components/captcha/AltchaCaptcha.php, protected/humhub/components/captcha/AltchaCaptchaAction.php, protected/humhub/components/captcha/AltchaCaptchaAsset.php, protected/humhub/components/captcha/AltchaCaptchaInput.php, protected/humhub/components/captcha/AltchaCaptchaValidator.php, protected/humhub/components/captcha/CaptchaInterface.php, protected/humhub/components/captcha/YiiCaptcha.php, protected/humhub/components/captcha/YiiCaptchaInput.php, protected/humhub/components/captcha/YiiCaptchaValidator.php, protected/humhub/config/__autocomplete.php, protected/humhub/config/web.php, protected/humhub/controllers/CaptchaController.php, protected/humhub/modules/user/controllers/AuthController.php, protected/humhub/modules/user/models/Invite.php, protected/humhub/modules/user/models/forms/AccountRecoverPassword.php, protected/humhub/modules/user/views/auth/login.php, protected/humhub/modules/user/views/auth/login_modal.php, protected/humhub/modules/user/views/password-recovery/index.php, protected/humhub/modules/user/views/password-recovery/index_modal.php, protected/humhub/modules/user/views/registration/byLink.php, protected/humhub/widgets/form/CaptchaField.php
=> Refactoring

protected/humhub/modules/space/models/Membership.php
=> Correct typo in comments

CHANGELOG.md, protected/humhub/modules/admin/tests/codeception/functional/ApprovalCest.php, protected/humhub/modules/user/tests/codeception/functional/LinkInviteCest.php, protected/humhub/modules/user/tests/codeception/functional/RegistrationCest.php, protected/humhub/modules/user/views/auth/register_success.php, protected/humhub/modules/user/views/auth/register_success_modal.php
Issue https://github.com/humhub/wording/issues/174
=> Enh: Confusing message after creating an account

CHANGELOG.md, static/js/humhub/humhub.ui.modal.js
https://github.com/humhub/humhub-internal/issues/535
=> Reset modal window after close

CHANGELOG.md, static/js/humhub/humhub.ui.picker.js
https://github.com/humhub/wiki/issues/370
=> Fix picker autofocus

CHANGELOG.md, protected/humhub/libs/Html.php
https://github.com/humhub/humhub-internal/issues/559
=> Use strikethrough style for disabled user name

protected/humhub/modules/friendship/views/manage/sent-requests.php
https://community.humhub.com/content/perma?id=284730
=> Enh: Translate Cancel Friendship Button

CHANGELOG.md, static/js/humhub/humhub.ui.picker.js
=> Add beforeInitCallback `humhub.ui.picker`

CHANGELOG.md, protected/humhub/modules/user/behaviors/Followable.php
https://github.com/humhub/humhub/issues/7442
=> Inactive users included in follower count

CHANGELOG.md, protected/humhub/compat/HForm.php, protected/humhub/modules/admin/controllers/GroupController.php, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/admin/models/forms/UserEditForm.php
https://github.com/humhub/humhub/pull/7408#issuecomment-2685698043
https://github.com/humhub/limited-user-admin/issues/1
=> Update code to manage users from external modules

CHANGELOG.md, protected/humhub/modules/stream/models/StreamSuppressQuery.php, protected/humhub/modules/stream/resources/js/humhub.stream.wall.js
https://github.com/humhub/wiki/issues/364
=> Stream will break if Wiki Entries are archived

CHANGELOG.md, protected/humhub/modules/user/models/forms/Registration.php
https://github.com/humhub/humhub-internal/issues/575
=> Master Tests broken #575

CHANGELOG.md, composer.lock
https://github.com/humhub/humhub-internal/issues/468
=> Upgrade Packages

CHANGELOG.md, protected/humhub/libs/BaseSettingsManager.php, protected/humhub/models/Setting.php, protected/humhub/tests/codeception/unit/models/SettingTest.php
=> Setting manager backwards compatibility

composer.json, composer.lock
https://github.com/humhub/humhub-internal/issues/509
=> Upgrade PhpSpreadsheet to latest version

CHANGELOG.md, protected/humhub/modules/space/modules/manage/views/security/index.php, protected/humhub/modules/space/resources/js/humhub.space.js
https://github.com/humhub/humhub/issues/7457
=> Fix changing of space visibility

protected/humhub/modules/user/models/forms/Registration.php
Additional fix to avoid errors like [this](https://github.com/humhub/legal/issues/96#issuecomment-2720624437).
=> Don't reset additional registration form elements on init default elements

CHANGELOG.md, protected/humhub/modules/content/search/driver/MysqlDriver.php
https://github.com/humhub/humhub-internal/issues/581
=> Fix searching with not full latin words

CHANGELOG.md, protected/humhub/modules/content/widgets/SearchFilters.php
https://github.com/humhub/humhub-internal/issues/583
=> Fix advanced searching by space filter

CHANGELOG.md, protected/humhub/compat/HForm.php, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/user/services/AuthClientService.php
https://github.com/humhub/humhub/issues/7472
=> Fix missing fields when creating a new user from admin

CHANGELOG.md, MIGRATE-DEV.md, protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/user/controllers/RegistrationController.php, protected/humhub/modules/user/models/forms/Registration.php, protected/humhub/modules/user/services/AuthClientService.php
=> Refactor Registration Form Options

protected/humhub/modules/admin/controllers/UserController.php, protected/humhub/modules/user/services/AuthClientService.php
https://github.com/humhub/humhub/pull/7477/files#diff-9256b1b6a70a7b70126b04c379383b609854ca5374b0feedf7580fe4d0d59fe0L266
=> Don't require approval for user created from administration

CHANGELOG.md, protected/humhub/modules/content/resources/js/humhub.content.form.js
https://github.com/humhub/humhub-internal/issues/595
=> Fix the post submit button title after back from draft mode

protected/humhub/modules/user/components/PermissionManager.php
https://github.com/humhub/humhub-internal/issues/597
=> Fix permission manager

CHANGELOG.md, protected/humhub/modules/installer/views/setup/database.php
https://github.com/humhub/humhub-internal/issues/600
=> Use password type on the installation DB config form

CHANGELOG.md, protected/humhub/modules/comment/widgets/Comments.php
https://github.com/humhub/humhub-internal/issues/604
=> Fix comments list when comment is active from another parent comment

protected/humhub/modules/file/messages/ru/base.php
https://github.com/humhub/humhub-internal/issues/605
=> Fix plural wording

CHANGELOG.md, protected/humhub/modules/file/handler/FileHandlerCollection.php
https://github.com/humhub/humhub-internal/issues/602#issuecomment-2785477163
=> Catch errors in external file handlers

CHANGELOG.md, protected/humhub/modules/space/models/forms/InviteForm.php, protected/humhub/modules/space/widgets/InviteModal.php, protected/humhub/modules/space/widgets/views/inviteModal.php
https://github.com/humhub/humhub-internal/issues/596
=> Fix access to options on space invite form

CHANGELOG.md, protected/humhub/components/Module.php
https://github.com/humhub/humhub-internal/issues/618
=> Don't run migration on updating of disabled module

static/js/humhub/humhub.ui.modal.js
https://github.com/humhub/humhub-internal/issues/620#issuecomment-2822064755
=> Display message on load modal window

CHANGELOG.md, index.php
https://github.com/humhub/humhub-internal/issues/635
=> Dynamic config priority

CHANGELOG.md, index.php
https://github.com/humhub/humhub-internal/issues/635
=> Fix priority of dynamic config

protected/humhub/modules/notification/components/BaseNotification.php
https://github.com/humhub/humhub-internal/issues/639
=> Fix error on notification with grouped users

CHANGELOG.md, protected/humhub/modules/admin/messages/de/user.php
https://github.com/humhub/humhub/issues/7515
=> Fix Incorrect German Translation

CHANGELOG.md, protected/humhub/components/bootstrap/SettingsLoader.php
https://github.com/humhub/humhub-internal/issues/643
=> mailer config fix

CHANGELOG.md, protected/humhub/modules/queue/Events.php, protected/humhub/modules/queue/LongRunningActiveJob.php, protected/humhub/modules/queue/config.php
=> Change LongRunningActiveJob handling

protected/humhub/components/Theme.php, protected/humhub/helpers/ThemeHelper.php, protected/humhub/modules/ui/tests/codeception/unit/ThemeHelperTest.php, protected/humhub/modules/ui/tests/codeception/unit/scss/ScssHelperTest.php
https://github.com/humhub/humhub-internal/issues/622
=> Test theme build css

.gitignore
=> Add .test-env to .gitignore

CHANGELOG.md, protected/humhub/modules/admin/widgets/InstalledModuleControls.php, protected/humhub/modules/content/widgets/ContainerModuleActionButtons.php
Issue https://github.com/humhub/humhub-internal/issues/631
=> Enh: Change title when disabling a module

MIGRATE-BS5.md, MIGRATE-DEV-BS5.md, static/scss/_button.scss, static/scss/_topbar.scss, static/scss/variables.scss
Issue https://github.com/humhub/humhub-internal/issues/592
=> Bs5 colors

CHANGELOG.md, protected/humhub/modules/user/controllers/AuthController.php
Issue https://github.com/humhub/app-internal/issues/109#issuecomment-2927261154
=> Enh: Allow logout from Mobile App

CHANGELOG.md, protected/humhub/components/console/UrlManager.php
https://github.com/humhub/humhub/issues/7388
=> Email "Reset Password" link is wrong when pretty URL is disabled and HumHub not in the URL root 

CHANGELOG.md, protected/humhub/modules/ui/filter/widgets/DatePickerFilterInput.php
https://github.com/humhub/humhub-internal/issues/682
=> Fixstream filter placeholder

protected/humhub/modules/content/widgets/richtext/AbstractRichTextEditor.php, protected/humhub/modules/post/widgets/views/form.php
https://github.com/humhub/humhub-internal/issues/690
=> Remove space under post field on wall stream

CHANGELOG.md, protected/humhub/modules/ui/form/assets/CodeMirrorAssetBundle.php, static/js/humhub/humhub.ui.codemirror.js
https://github.com/humhub/humhub-internal/issues/692
=> Fix `CodeMirrorInputWidget` in collapsible fields

CHANGELOG.md, protected/humhub/migrations/m250715_070647_group_name_length.php, protected/humhub/modules/user/models/Group.php
https://github.com/humhub/humhub-internal/issues/712
=> Increase Group Name max length to 120chars

protected/humhub/modules/comment/widgets/Comment.php, static/scss/_comment.scss
https://github.com/humhub/humhub-internal/issues/740
=> BS5 - Stream Overflow

protected/humhub/modules/comment/resources/js/humhub.comment.js, protected/humhub/modules/comment/widgets/views/comments.php, static/scss/_comment.scss
https://github.com/humhub/humhub-internal/issues/746
=> BS5 - Comments: alignment issues

CHANGELOG.md, protected/humhub/modules/user/models/forms/Registration.php, protected/humhub/modules/user/services/AuthClientService.php
https://github.com/humhub/humhub-internal/issues/749
=> Fix registration by auth clients

MIGRATE-BS5.md, protected/humhub/modules/admin/models/forms/FileSettingsForm.php, protected/humhub/modules/admin/models/forms/MobileSettingsForm.php, protected/humhub/modules/admin/views/logging/log_entries.php, protected/humhub/modules/admin/views/setting/mobile_app.php, protected/humhub/modules/content/views/share-intend/index.php, protected/humhub/modules/file/views/share-intend/index.php, protected/humhub/modules/marketplace/widgets/Settings.php, protected/humhub/modules/post/views/share-intend/create.php, protected/humhub/modules/ui/menu/widgets/Menu.php, protected/humhub/modules/user/models/fieldtype/Checkbox.php
https://github.com/humhub/humhub-internal/issues/756
=> Fix unmigrated views for BS5

MIGRATE-DEV.md
https://github.com/humhub/humhub-internal/issues/762#issuecomment-3159817788
=> Update MIGRATE-DEV.md for Codeception v5

CHANGELOG.md, protected/humhub/modules/admin/controllers/UserProfileController.php, protected/humhub/modules/user/models/ProfileField.php
https://github.com/humhub/humhub-internal/issues/753
=> User profile field translation category validation

protected/humhub/modules/user/widgets/views/userListBox.php
https://github.com/humhub/humhub-internal/issues/768
=> BS5 - User List Box - Remove extra image margin for online icon

CHANGELOG.md, protected/humhub/modules/comment/resources/js/humhub.comment.js, protected/humhub/modules/comment/views/comment/edit.php, protected/humhub/modules/comment/widgets/views/form.php, protected/humhub/modules/file/resources/js/humhub.file.js, protected/humhub/modules/post/views/post/edit.php, protected/humhub/modules/stream/tests/codeception/acceptance/StreamCest.php, static/scss/_comment.scss, static/scss/_form.scss, static/scss/_list-group.scss
https://github.com/humhub/humhub-internal/issues/774
=> Fix: Send button inside upload-buttons class

CHANGELOG.md, protected/humhub/modules/installer/views/config/modules.php, protected/humhub/modules/installer/views/setup/database.php
https://github.com/humhub/humhub-internal/issues/778
=> BS5 - Installer - Small buttons

CHANGELOG.md, protected/humhub/modules/installer/views/config/modules.php, protected/humhub/modules/installer/views/setup/database.php
https://github.com/humhub/humhub-internal/issues/780
=> Fix: Installer - Replace loading modal box with button loading custom messages

CHANGELOG.md, static/js/humhub/humhub.ui.loader.js
https://github.com/humhub/humhub-internal/issues/789
=> Fix loader on attach image to RichText field

MIGRATE-BS5.md
=> MIGRATE-BS5.md: Fix BS imports for modules

protected/humhub/modules/comment/widgets/EditLink.php, static/js/humhub/humhub.ui.panel.js, static/scss/_nav.scss
=> Fix Icon right spacing in buttons

protected/humhub/modules/space/behaviors/SpaceController.php
=> Fix JS error

MIGRATE-BS5.md
https://github.com/humhub/humhub-internal/issues/782
=> Add Tooltip tt deprecation to MIGRATE-BS5.md

protected/humhub/modules/user/widgets/AuthChoice.php
This class was already present in 1.17.
It's not used anywhere and make no sense.
However, I left `$extraCssClass` because it's used for further buttons to make them small.
=> Remove Auth Choice btn-sxm class

CHANGELOG.md, protected/humhub/modules/installer/commands/InstallController.php
I ran across this issue when trying to add HumHub v1.18 beta builds to [humhub-docker](https://github.com/dantefromhell/humhub-docker). Automated deployment tests were failing like https://github.com/dantefromhell/humhub-docker/actions/runs/17483167821/job/49657483783#step:11:119
=> fix: Add missing DatabaseForm import to InstallController

CHANGELOG.md, MIGRATE-BS5.md, protected/humhub/modules/content/widgets/ContainerModuleActionButtons.php, protected/humhub/modules/content/widgets/stream/views/wallStreamEntryHeader.php, protected/humhub/modules/marketplace/widgets/ModuleUpdateActionButtons.php, protected/humhub/modules/space/widgets/SpaceDirectoryActionButtons.php, protected/humhub/modules/tour/widgets/views/dashboard.php, protected/humhub/modules/ui/widgets/views/counterSetHeader.php, protected/humhub/modules/user/views/auth/login.php, protected/humhub/modules/user/widgets/PeopleActionButtons.php, static/scss/_base.scss, static/scss/_bootstrap3.scss, static/scss/_button.scss, static/scss/_cards.scss, static/scss/_comment.scss, static/scss/_dropdown.scss, static/scss/_file.scss, static/scss/_list-group.scss, static/scss/_list.scss, static/scss/_modal.scss, static/scss/_modules.scss, static/scss/_nav.scss, static/scss/_notification.scss, static/scss/_pagination.scss, static/scss/_richtext.scss, static/scss/_stream.scss, static/scss/_table.scss, static/scss/_topbar.scss, static/scss/maps.scss, static/scss/variables.scss
https://github.com/humhub/humhub-internal/issues/806
=> BS5 - Link & Marketplace Colors + various fixes

protected/humhub/modules/activity/tests/codeception/acceptance/ActivityStreamCest.php, protected/humhub/tests/config/env/github.yml
=> Updated Codeception

CHANGELOG.md, static/scss/_search.scss, static/scss/_topbar.scss, static/scss/variables.scss
https://github.com/humhub/humhub-internal/issues/831
=> Fix: Enable Bootstrap box-shadows, mainly for dropdown menus

CHANGELOG.md, protected/humhub/migrations/m250226_125226_rename_mailer_vars.php
https://github.com/humhub/humhub/issues/7696
=> mailer settings

protected/humhub/modules/installer/controllers/ConfigController.php
https://github.com/humhub/humhub-internal/issues/752
=> SaaS - Installer drop error on last step

composer.json, composer.lock, protected/humhub/assets/JqueryWidgetAsset.php, protected/humhub/config/assets-dev.php, protected/humhub/config/assets.php, protected/humhub/helpers/ThemeHelper.php
=> Removed second Jquery

CHANGELOG.md, static/js/humhub/humhub.ui.search.js, static/scss/_search.scss
https://github.com/humhub/humhub-internal/issues/841
=> Fix scroll of meta search modal window

CHANGELOG.md, static/scss/_bootstrap3.scss
https://github.com/humhub/humhub-internal/issues/840
=> Fix: Images in HTML created by TinyMCE are not responsive

CHANGELOG.md, static/scss/_select2.scss
https://github.com/humhub/humhub-internal/issues/835
=> Form input border color inconsistency

CHANGELOG.md, protected/humhub/modules/user/views/auth/login_modal.php, protected/humhub/modules/user/widgets/AuthChoice.php, static/resources/user/authChoice.css, static/resources/user/authChoice.js, static/scss/_login.scss
https://github.com/humhub/humhub-internal/issues/842
=> Enh: Review SSO auth buttons layout in login form

protected/humhub/models/UrlOembed.php
https://github.com/humhub/humhub-internal/issues/839#issuecomment-3327524585
=> Fix run of OEmbed scripts on page refresh

MIGRATE-BS5.md, static/scss/_button.scss, static/scss/_dropdown.scss, static/scss/_nav.scss, static/scss/_table.scss
=> Update bootstrap assets from bower to npm in docs

CHANGELOG.md, protected/humhub/components/Migration.php
https://github.com/humhub/humhub-internal/issues/837
=> fix is initial installation state

CHANGELOG.md, protected/humhub/modules/activity/components/MailSummary.php
=> Fix mail summary scope for new users

CHANGELOG.md, protected/humhub/modules/content/resources/js/humhub.content.form.js
=> Fix ui form model name identification

CHANGELOG.md, protected/humhub/modules/content/resources/js/humhub.content.form.js
=> Fix content `resetForm` after form submit

CHANGELOG.md, static/scss/_tour.scss
https://github.com/humhub/humhub-internal/issues/848
=> Fix: Tour module - the bottom part of the Profile image is hidden

CHANGELOG.md, protected/humhub/components/ThemeVariables.php
https://github.com/humhub/humhub-internal/issues/849
=> Use theme variable values from customization settings

CHANGELOG.md, protected/humhub/modules/content/commands/SearchController.php, protected/humhub/modules/content/jobs/ReindexUserContent.php, protected/humhub/modules/content/jobs/SearchRebuildIndex.php, protected/humhub/modules/content/search/driver/AbstractDriver.php, protected/humhub/modules/content/services/ContentSearchService.php, protected/humhub/modules/content/services/SearchDriverService.php, protected/humhub/services/MetaSearchService.php
https://github.com/humhub/humhub-internal/issues/843
=> Flush cache after rebuild content search results
