humhub/humhub

- protected/modules_core/user/widgets/views/profileHeader.php
Added Ekko Lightbox to User Profile Image to view larger version.
> Added Ekko Lightbox to User Profile Image

- protected/views/layouts/main.php
Added truncate class for user title from previous pull request
http://i.imgur.com/HggVLAk.png
> Added truncate to User Title

- protected/modules_core/user/views/account/delete.php
user delete account password field does not have any placeholder or label so it was added.
> added placeholder for delete account

- protected/libs/Helpers.php
Added `Helpers::arrayCompVal()` for JSON/Array/Object value comparison. Useful in data handling.
> Added arrayCompVal()

- protected/models/UrlOembed.php
> oembed: Allow also oembed data of type photo

- protected/libs/LogoImage.php
- protected/modules_core/file/libs/ImageConverter.php
Please revise if this solution is acceptable because the change is made on ImageConverter file.
> enabled use of transparent png files

- protected/modules_core/space/messages/de/widgets_views_spaceInfo.php
- protected/modules_core/space/widgets/views/spaceInfo.php
> [FIXED] Missing translation! (#742)

- protected/modules_core/space/behaviors/SpaceControllerBehavior.php
- protected/modules_core/space/behaviors/SpaceModuleBehavior.php
added missing @package and @throws
> Minor improvement

- protected/modules_core/admin/console/ModuleTool.php
Added and updated PHPDoc comments too.
> [FIXED]  Wrong USAGE information for Yii console command 'help module' (#769)

- protected/modules_core/admin/views/about/index.php
Keeps the copyright year always up-to-date.
Partly fixes #690
> [FIX] Change copyright year (#690)

- protected/vendors/yii/test/CTestCase.php
use CTestCase.php from YiiFramework 1.1.16 for better compatibility with latest phpunit
> update CTestCase.php to Yii 1.1.16

- protected/modules_core/admin/controllers/ApprovalController.php
- protected/modules_core/admin/messages/de/controllers_ApprovalController.php
Make text translatable via message file
> Fix for Issue #823: make approval and decline email texts translatable

- protected/modules_core/user/views/profile/about.php
TextArea fields contains new lines which should be respected in view (do not use HHtml::enrichText, do only nl2br for such fields)
> nl2br on ProfileFieldTypeTextArea fields

- protected/humhub/compat/CHtml.php
- protected/humhub/modules/activity/models/Activity.php
- protected/humhub/modules/user/libs/Ldap.php
- protected/humhub/modules/user/models/ProfileField.php
This PR removes unreachable statements. It doesn't remove the following ones:
* [protected/humhub/modules/user/migrations/m131023_164513_initial.php#L183](https://github.com/humhub/humhub/blob/bafea8b872748dd085edbdfc50d7ef0e95d4cb46/protected/humhub/modules/user/migrations/m131023_164513_initial.php#L183)
* [protected/humhub/components/ModuleManager.php#L291](https://github.com/humhub/humhub/blob/bafea8b872748dd085edbdfc50d7ef0e95d4cb46/protected/humhub/components/ModuleManager.php#L291)
> Removed unreachable statements

- protected/humhub/modules/installer/libs/InitialData.php
- protected/humhub/modules/like/notifications/views/newLike.php
- protected/humhub/modules/user/models/Invite.php
fix issue #1442 'Firstname' should display as 'First name' ....
fix issue #1459  Notification of Comment Like indicates Post instead Comment.
> fix issue #1442 and #1459

- js/app.js
- protected/humhub/modules/content/widgets/views/wallCreateContentForm.php
- protected/humhub/modules/user/views/auth/login.php
- protected/humhub/modules/user/widgets/UserPicker.php
- protected/humhub/modules/user/widgets/views/userPicker.php
- protected/humhub/widgets/views/richTextEditor.php
- resources/user/userpicker.js
Enh: Enhanced user picker (ordering, data transfer)
Fix: Richtext clear event is triggered when contentcreateform is submitted
Enh: Removed client form validation in login form
> Fix: New Mail Modal Form fix

- protected/humhub/modules/user/controllers/AuthController.php
redirect should always return.
> fixed redirect in login to avoid executing login logic again

- protected/humhub/modules/search/behaviors/Searchable.php
- protected/humhub/modules/search/engine/ZendLuceneSearch.php
- protected/humhub/modules/search/interfaces/Searchable.php
- protected/humhub/modules/search/libs/SearchResultSet.php
> fixed search results for short keywords

- protected/humhub/components/ModuleManager.php
- protected/humhub/components/bootstrap/ModuleAutoLoader.php
- protected/humhub/modules/content/components/ContentContainerActiveRecord.php
- protected/humhub/modules/directory/widgets/Sidebar.php
- protected/humhub/modules/like/notifications/NewLike.php
- protected/humhub/modules/notification/models/Notification.php
- protected/humhub/modules/notification/views/layouts/web.php
> cleanup, small fixes and phpdoc improvements

- protected/humhub/modules/comment/controllers/CommentController.php
- protected/humhub/modules/content/components/ContentAddonActiveRecord.php
- protected/humhub/modules/content/components/ContentAddonController.php
- protected/humhub/modules/file/models/File.php
> allow sending image-only comments

- protected/humhub/compat/HForm.php
- protected/humhub/modules/user/models/fieldtype/BaseType.php
- protected/humhub/modules/user/models/fieldtype/MarkdownEditor.php
- protected/humhub/modules/user/views/profile/about.php
While we creating profiles fields in humhub, Now it is possible to add the markdown editor in the fields
> Integrated Markdown Editor

- protected/humhub/widgets/BaseStack.php
function was unimplemented with a todo annotation.
> implemented BaseStack::removeWidget()

- protected/humhub/modules/content/widgets/Stream.php
- protected/humhub/modules/space/models/Space.php
also fixes an issues which adds superflous param "1=route" to every
space url.
> added Stream::$streamActionParams to customize stream Url

- protected/humhub/modules/content/components/actions/Stream.php
added before and after action events that can be used to modify the
stream action filter.
> allow customization of Stream action via events

- protected/humhub/modules/dashboard/controllers/DashboardController.php
- protected/humhub/modules/dashboard/views/dashboard/index.php
- protected/humhub/modules/dashboard/views/dashboard/index_guest.php
- protected/humhub/modules/dashboard/widgets/DashboardContent.php
Added DashboardContent widget to have an event before dashboard content rendering
> Added DashboardContent widget

- protected/humhub/modules/content/components/ContentContainerActiveRecord.php
- protected/humhub/modules/space/views/space/_layout.php
- protected/humhub/modules/space/widgets/Menu.php
- protected/humhub/modules/space/widgets/SpaceContent.php
Added `SpaceContent` widget to have an event before space content rendering.
Minor PHPDocs updates
> Added SpaceContent widget

- protected/humhub/libs/SelfTest.php
> Add check for PDO Mysql extension. 

- protected/humhub/docs/guide/dev-i18n.md
> added note about dev env for i18n guide

- protected/humhub/compat/CActiveForm.php
- protected/humhub/modules/admin/views/authentication/authentication.php
- protected/humhub/modules/admin/views/setting/basic.php
- protected/humhub/modules/admin/views/setting/design.php
- protected/humhub/modules/admin/views/setting/mailing_server.php
- protected/humhub/modules/comment/widgets/views/form.php
- protected/humhub/modules/content/controllers/ContentController.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/content/models/ContentContainerSetting.php
- protected/humhub/modules/file/libs/ImageConverter.php
- protected/humhub/modules/post/views/post/edit.php
- protected/humhub/modules/post/widgets/views/form.php
- protected/humhub/modules/search/commands/SearchController.php
- protected/humhub/modules/space/modules/manage/views/security/index.php
- protected/humhub/modules/space/views/membership/invite.php
- protected/humhub/modules/space/widgets/MembershipButton.php
- protected/humhub/modules/user/models/UserFilter.php
- protected/humhub/modules/user/models/fieldtype/CountrySelect.php
- protected/humhub/modules/user/views/account/editSettings.php
- protected/humhub/modules/user/views/account/emailing.php
- protected/humhub/modules/user/views/invite/index.php
- protected/humhub/modules/user/widgets/UserPicker.php
- protected/humhub/widgets/RichText.php
- Fixed missing method modifiers.
- Fixed case mismatch.
- Fixed calling non-static methods statically.
> Code style fixes

- protected/humhub/modules/file/widgets/views/showFiles.php
Moves from
`33.634178 kilobytes`
to
`33.6 KB`
> More human readable file sizes

- themes/HumHub/css/theme.less
> Add padding on user detail view

- protected/humhub/modules/comment/messages/fr/widgets_views_link.php
Specify that we are adding a comment, not reading an existent one.
> Update string to be more specific

- protected/humhub/views/layouts/main.php
Remove additional spaces and line breaks
> Code not being parsed for IE specific tags

- protected/humhub/modules/like/messages/fr/base.php
We are about to like, so in french this should be write this way.
> Specifying the Like action

- protected/humhub/modules/file/controllers/FileController.php
> Attached files browser caching, fixes #2091

- protected/humhub/modules/post/models/Post.php
I add the full username to search params. Now i'm able to search for posts by user.
> search for post by author name

- protected/humhub/libs/SelfTest.php
> Added check for APCu to installation checks

- composer.json
1.2.0 Raised minimum PHP Version to 5.6
> Require PHP >= 5.6

- .htaccess.dist
Access to composer files should not be world readable as a malicious user could find information on outdated libraries.
> [security] Update .htaccess

- protected/humhub/messages/fr/base.php
- protected/humhub/messages/fr/widgets_views_markdownEditor.php
- protected/humhub/modules/admin/messages/fr/views_space_settings.php
- protected/humhub/modules/comment/messages/fr/widgets_views_showComment.php
- protected/humhub/modules/content/messages/fr/views_wallLayout.php
- protected/humhub/modules/content/messages/fr/widgets_views_permaLink.php
- protected/humhub/modules/user/messages/fr/base.php
- protected/humhub/modules/user/messages/fr/controllers_AccountController.php
- protected/humhub/modules/user/messages/fr/models_Invite.php
- protected/humhub/modules/user/messages/fr/permissions.php
- protected/humhub/modules/user/messages/fr/views_auth_login.php
I tried translate.humhub.org but the FR espace seems inactive so I created this PR. Feel free to merge or close it.
And I can't find these translations in the files :
> Adding more french translations

- .codeclimate.yml
Excluded **/messages from analysis.
> Updated .codeclimate.yml

- protected/humhub/modules/admin/models/forms/BasicSettingsForm.php
When removed all default Spaces in settings
> fix bug:  in_array() expects parameter 2 to be array, string given

- protected/humhub/modules/file/libs/FileHelper.php
Moves from `237.5167356 kilobytes` to `237.5 KB`
> Human readable file sizes

- static/less/topbar.less
> Fix small gap on TopNav mouse hover

- static/less/nav.less
Calculating height by `height = a2 + b2 = c2`
> Center .caret

- protected/humhub/components/Module.php
Added `setting` phpdoc-property to `humhub/components/Module.php`
> PHPDoc property To autocompleate IDE

- protected/humhub/modules/notification/models/Notification.php
> To corrected query when Sql Mode ONLY_FULL_GROUP_BY

- protected/humhub/libs/Helpers.php
- protected/humhub/modules/file/libs/ImageConverter.php
Tested on PHP7.1 Windows 
When loaded image get error
```
yii\base\ErrorException: A non well formed numeric value encountered in 
\humhub\protected\humhub\modules\file\libs\ImageConverter.php:121
```
after local fix getted next error
```
yii\base\ErrorException: A non well formed numeric value encountered in 
\humhub\protected\humhub\libs\Helpers.php:125
```
PR fixes this errors
P.S. `Helpers::GetBytesOfPHPIniValue()` named as non standart of code
> fix bug: when load image file

- protected/humhub/modules/admin/models/forms/CacheSettingsForm.php
> Fix: APCu Testing

- protected/humhub/docs/guide/admin/spaces.md
- protected/humhub/modules/space/models/Space.php
- protected/humhub/modules/space/modules/manage/views/security/index.php
<sub><sup>P.S. Fix #1962</sup></sub>
> Space visibility provided to common description

- protected/humhub/modules/stream/actions/Stream.php
- protected/humhub/modules/stream/models/StreamQuery.php
- protected/humhub/modules/stream/models/StreamSuppressQuery.php
improve autocomplete
remove unused import
> fix phpDoc

- protected/humhub/widgets/ShowMorePager.php
> typo in ShowMorePager

- protected/humhub/modules/content/components/ContentContainerController.php
> To improving for code of ContentContainerController

- protected/humhub/components/queue/driver/Sync.php
See https://github.com/humhub/humhub/commit/ac3ef620565f3c5592d6ae75103e74aac00052d4#commitcomment-21615930
> fix declaration with Queue::run($job)

- .travis.yml
https://github.com/humhub/humhub/pull/2478
> Reflect last composer.json update PR

- protected/humhub/docs/guide/developer/git-installation.md
https://github.com/humhub/humhub/pull/2478 & https://github.com/humhub/humhub/pull/2479
> Update git-installation.md from latets PRs

- protected/humhub/modules/user/views/layouts/main.php
Tags already loaded at https://github.com/humhub/humhub/blob/9a34a1a815283d2107519dcdd07eaf0c903e485a/protected/humhub/components/View.php#L175
> Avoid double loading of CsrfTags

- protected/humhub/messages/zh_cn/ContentController.base.php
- protected/humhub/messages/zh_cn/base.php
- protected/humhub/modules/activity/messages/zh_cn/base.php
- protected/humhub/modules/admin/messages/zh_cn/forms_CacheSettingsForm.php
- protected/humhub/modules/admin/messages/zh_cn/permissions.php
- protected/humhub/modules/admin/messages/zh_cn/views_setting_authentication_ldap.php
- protected/humhub/modules/admin/messages/zh_cn/views_user_delete.php
- protected/humhub/modules/content/messages/zh_cn/base.php
- protected/humhub/modules/content/messages/zh_cn/controllers_ContentController.php
- protected/humhub/modules/directory/messages/zh_cn/base.php
- protected/humhub/modules/file/messages/zh_cn/base.php
- protected/humhub/modules/notification/messages/zh_cn/views_notificationLayoutMail.php
- protected/humhub/modules/space/messages/zh_cn/widgets_SpacePickerField.php
- protected/humhub/modules/space/messages/zh_cn/widgets_views_profileHeader.php
- protected/humhub/modules/space/messages/zh_cn/widgets_views_spaceChooserItem.php
- protected/humhub/modules/user/messages/zh_cn/views_auth_login.php
- protected/humhub/modules/user/messages/zh_cn/widgets_BasePickerField.php
- protected/humhub/modules/user/messages/zh_cn/widgets_UserPickerField.php
- protected/humhub/modules/user/messages/zh_cn/widgets_views_profileHeader.php
> update zh_cn language

- protected/humhub/modules/user/messages/fr/base.php
> Update users French base

- protected/humhub/modules/file/libs/ImageConverter.php
See https://secure.php.net/manual/en/function.imagecreatefromjpeg.php#refsect1-function.imagecreatefromjpeg-examples
> Create GDimage from data if JPEG fails - Fix #2561

- protected/humhub/modules/activity/Events.php
То batch query for deleting of Activity of an object.
> Enh to code \activity\Events::onActiveRecordDelete

- protected/humhub/models/UrlOembed.php
https://community.humhub.com/content/perma?id=107414
> to fix "Undefined index: html"

- protected/humhub/modules/directory/Module.php
Actually only two or more groups are shown.
Fixes #2533
> Show groups at directory if >= 1

- protected/humhub/modules/user/messages/fr/base.php
Minor typo in french translation at the key 'Sign in / up'.
> Typo in translation

- .github/issue_template.md
Add a small note about using the community for questions about customizing.
> Add small note

- .htaccess.dist
Exclude acme-challenge at https redirect
> Fix SSL Rewrite Rule

- protected/config/.gitignore
- protected/config/common.php
- protected/config/console.php
- protected/config/web.php
To avoid commits like this https://github.com/humhub/humhub/commit/589b1e3afd00811c1c6c5b25a6aed7a411898ad0 in future
> added local environments to gitignore

- protected/humhub/modules/user/components/UrlRule.php
> remove strtolower($username)

- protected/humhub/modules/file/widgets/views/showFiles.php
To reduce traffic from the vidos -> preload = "metadata"
And render WEBM videos
> preload="metadata" + add .webm

- protected/humhub/libs/SelfTest.php
> Add check for php iconv extension to the setup

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/docs/guide/admin/search.md
- protected/humhub/modules/search/engine/ZendLuceneSearch.php
> Allow configuration of lucene query term limit

- protected/humhub/docs/guide/admin/authentication.md
This should fix the issue with the leak in html on the live version of the docs. :smile:
> Docs minor html leak fix

- protected/humhub/docs/guide/admin/security.md
Added `,` and `we're` to express that the team is continuously improving security features as well as removed unneeded line spaces and other grammar fixes.
> Fix: Add some grammar fixes

- .htaccess.dist
- protected/humhub/docs/CHANGELOG.md
The issue is seen on the community site [here](https://community.humhub.com/content/perma?id=133524).
> Fix: Let's Encrypt ACME Error

- protected/humhub/modules/installer/Module.php
> Remove dead code

- protected/humhub/modules/user/views/password-recovery/index_modal.php
> Typo and format

- protected/humhub/modules/user/tests/codeception/unit/MentionTest.php
- Remove use Specify (unused & not required in composer.json)
- Code Style
> Fix MentionTest

- protected/humhub/modules/user/tests/codeception/unit/FollowTest.php
- Remove use Specify (unused & not required in composer.json)
- Code Style
> Fix FollowTest

- protected/humhub/modules/user/tests/codeception/unit/ApprovalTest.php
- Remove `use Specify` (unused & not required in composer.json)
- Code Style
> Fix ApprovalTest

- protected/humhub/modules/user/components/PermissionManager.php
@githubjeka @acs-ferreira would you be so kind to review?
> Phpdoc permmanager

- protected/humhub/modules/admin/controllers/AuthenticationController.php
- protected/humhub/modules/admin/views/authentication/authentication_ldap.php
I would like to fix #2919 and prepared some changes. Lets start with this small cleanup for Controller & Template.
@luke- @buddh4 I guess Setting::IsFixed is depcreated. Could you tell me the new way?
> CodeStyle for AuthenticationController & View

- protected/humhub/components/export/ExportResult.php
- Added throws to phpdoc
- Remove is_dir (https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L545 the first check inside createDirectory is is_dir)
@acs-ferreira fyi
> Update phpdoc (add missing throws)

- static/js/humhub/humhub.core.js
> Update .ready() function

- protected/humhub/modules/user/models/fieldtype/BaseType.php
> Update phpdoc, Remove Yii methods, Codestyle

- protected/humhub/migrations/m171015_155102_contentcontainer_module.php
To avoid possible errors by `contentcontainer_module` applied (I had)
> Enhancement to migration [skip ci]

- protected/humhub/modules/queue/driver/Instant.php
see https://travis-ci.org/humhub/humhub/jobs/341313158#L859
> PHP Fatal error:  Access level to Instant::status() must be public

- protected/humhub/modules/space/views/space/home.php
> Clean and fix

- protected/humhub/modules/user/authclient/Twitter.php
> Twitter Oauth2 update

- protected/humhub/libs/MimeHelper.php
- protected/humhub/tests/codeception/unit/libs/MimeHelperTest.php
- Add unit test for MimeHelper
- Migrate if/elseif to map
@acs-ferreira fyi
> Refactor mimehelper

- protected/humhub/components/SocialActivity.php
Fixes like https://travis-ci.org/humhub/humhub/jobs/343713320#L1969
revert some code from commit 130c4aa6de88daa42189f7cafec6669baaaa4bbd
> Fix unit tests

- protected/humhub/docs/guide/basics/core/md-cheatsheet.md
Added some missing Markdown syntax.
> Enh: MD docs

- protected/humhub/modules/comment/controllers/CommentController.php
When POST request with empty comment sends then get 200OK. It increases counters comment in wallEnrty, but comment not flashed
PR fixed it
> fix Invalid 200 OK when comment is empty

- static/js/jquery.pjax.modified.js
> Fix compatible PJAX  with jQuery 3

- protected/humhub/modules/notification/targets/BaseTarget.php
The merge with master by  https://github.com/humhub/humhub/commit/c086edf7fd31d579f8c203e8f0b57f3ab479fcfa provide to fail on PHP7.2 
see https://travis-ci.org/humhub/humhub/jobs/347135954#L1950
> re-fix conflict after master-merge

- protected/humhub/modules/space/modules/manage/models/MembershipSearch.php
> to fix static deprecated php error

- composer.json
- protected/humhub/components/export/ExportResult.php
- protected/humhub/libs/LogoImage.php
- protected/humhub/libs/ProfileBannerImage.php
- protected/humhub/libs/ProfileImage.php
- protected/humhub/modules/file/components/StorageManager.php
- protected/humhub/modules/search/engine/ZendLuceneSearch.php
Requires `Yii 2.0.14` https://github.com/yiisoft/yii2/pull/15335
> Switch from unlink() to FileHelper::unlink()

- protected/humhub/config/common.php
- protected/humhub/config/i18n.php
- protected/humhub/docs/CHANGELOG.md
I made a translation request quite a while ago :/
Modeled after https://github.com/humhub/humhub/commit/003d02165f08b06c0c95a5886e6233512627f781
> Added Slovene language

- .htaccess.dist
Issue can be seen [here](https://community.humhub.com/content/perma?id=144928).
> Fix: Install in Sub-directory

- protected/humhub/modules/space/modules/manage/views/member/pending-invitations.php
> Show 'never' instead of fake date

- protected/humhub/models/forms/UploadProfileImage.php
- protected/humhub/modules/admin/models/forms/DesignSettingsForm.php
> #3148: Rely on Max Upload Settings for Logo and Profile uploads

- .htaccess.dist
- protected/.htaccess
- uploads/file/.htaccess
See https://httpd.apache.org/docs/2.4/en/upgrading.html
> Better Apache 2.4 support

- protected/humhub/components/Theme.php
Fix for Theme class force `pathMap` change. So now, you can change module default views in your config files with `pathMap`.
> Fix for humhub\components\Theme

- protected/humhub/docs/guide/developer/snippet.md
Add a few examples of snippets for the docs later can be changed however.
> Enh: Add Snippets documentation

- .htaccess.dist
This removes a duplicate line of code for preventing httpd from serving dotfiles.
> Fix: Remove duplicate

- protected/humhub/modules/admin/models/forms/AddGroupMemberForm.php
- protected/humhub/modules/admin/models/forms/UserEditForm.php
- protected/humhub/modules/admin/models/forms/UserGroupForm.php
- protected/humhub/modules/topic/controllers/ManageController.php
- protected/humhub/modules/user/models/User.php
To discuss about https://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes#affected-code
> Arrays on findOne() methods

- protected/humhub/components/behaviors/PolymorphicRelation.php
https://github.com/humhub/humhub/issues/3194#issuecomment-410963612
Rename $_cached to $cached
Add @throws
> Fix broken import for PolymorphicRelation

- protected/humhub/docs/guide/admin/installation-configuration.md
See also https://github.com/humhub/humhub/issues/3255
> Clarify things about Cronjobs & Asynchronous Tasks

- protected/humhub/modules/admin/widgets/views/incomplete-setup-warning.php
> Chg: Send to a more exact place in docs

- static/css/select2Theme/select2-humhub.less
> Fix space selector image alignement

- protected/humhub/modules/activity/widgets/ActivityStreamViewer.php
- protected/humhub/modules/activity/widgets/views/activityStream.php
Another approach to implement #3177
> Enh: Make Latest activities collapsible

- protected/humhub/Yii.php
- protected/humhub/components/bootstrap/ModuleAutoLoader.php
- protected/humhub/tests/codeception/unit/components/bootstrap/ModuleAutoLoaderTest.php
**Dangerous change:** Removed conditional caching from ModuleAutoLoader
> Improve moduleloader

- protected/humhub/modules/space/Module.php
- protected/humhub/modules/space/models/Space.php
- protected/humhub/modules/user/Module.php
- protected/humhub/modules/user/models/User.php
add maximum username length & maximum/minimum space url length for /protected/config/common.php
> add maximum username length & maximum/minimum space url length

- protected/humhub/modules/queue/Events.php
https://github.com/yiisoft/yii2-queue/blob/d291834dc3df44dd2f17b4222a3172102eb16a4a/src/ErrorEvent.php#L13
> ErrorEvent has been deprecated

- .travis.yml
https://secure.php.net/ChangeLog-7.php#7.3.0
> Add PHP7.3 to TravisCI

- protected/humhub/modules/user/views/account/editModules.php
> Added: css class for support wiki module acceptance tests.

- protected/humhub/modules/admin/models/forms/AuthenticationSettingsForm.php
- protected/humhub/modules/admin/views/authentication/authentication.php
- protected/humhub/modules/user/models/Invite.php
- protected/humhub/modules/user/views/auth/login.php
- protected/humhub/modules/user/views/auth/login_modal.php
- static/js/humhub/humhub.ui.loader.js
> Added a captcha for the register form.

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/space/widgets/views/membershipButton.php
> Fix: #3463 Change 'Deny Invite' to 'Decline Invite'

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/space/modules/manage/models/MembershipSearch.php
- protected/humhub/modules/space/modules/manage/views/member/index.php
> Enh: #3466 Add inviter name to Space Admin Member section

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/admin/controllers/SpaceController.php
- protected/humhub/modules/admin/models/forms/BasicSettingsForm.php
- protected/humhub/modules/admin/models/forms/SpaceSettingsForm.php
- protected/humhub/modules/admin/views/setting/basic.php
- protected/humhub/modules/admin/views/space/settings.php
"Default spaces" setting has been moved to "Space Settings".
> Enh: #3449 Move "Default spaces" setting to "Space Settings"

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/admin/commands/ModuleController.php
> Enh: #3470 CLI: show content deletion warning on module disabling

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/user/components/User.php
- protected/humhub/modules/user/controllers/AccountController.php
- protected/humhub/modules/user/models/forms/AccountChangeUsername.php
- protected/humhub/modules/user/views/account/changeUsername.php
- protected/humhub/modules/user/views/account/changeUsername_success.php
- protected/humhub/modules/user/views/mails/ChangeUsername.php
- protected/humhub/modules/user/views/mails/plaintext/ChangeUsername.php
- protected/humhub/modules/user/widgets/AccountProfilMenu.php
> Feature: Change username

- protected/humhub/modules/space/modules/manage/views/member/index.php
- protected/humhub/modules/space/modules/manage/views/member/pending-invitations.php
Fix #3466 
Moved 'Invited By' column from 'Members' to 'Pending Invites' section.
> Fix #3466 Moved 'Invited By' column

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/directory/widgets/views/groupStats.php
- protected/humhub/modules/directory/widgets/views/memberStats.php
- protected/humhub/modules/directory/widgets/views/spaceStats.php
- static/less/progress.less
When building a new custom theme the color for Group Stats doesn't change colors, with this it fixes the problem. (#3579)
> Fix: Progress Color changing

- protected/humhub/events/OembedFetchEvent.php
- protected/humhub/libs/UrlOembedHttpClient.php
- protected/humhub/models/UrlOembed.php
- static/js/humhub/humhub.oembed.js
- static/js/humhub/humhub.ui.markdown.js
Just minor cleaning up of the code. :yum:
> Fix: Minor clean up

- protected/humhub/docs/guide/theme/tutorial.md
See [Less.js](http://lesscss.org/usage/) for more information.
> Fix: Moved -g to the end

- protected/humhub/modules/admin/views/space/index.php
- protected/humhub/modules/admin/views/user/list.php
- protected/humhub/modules/notification/widgets/views/notificationSettingsForm.php
- static/less/panel.less
- static/less/table.less
Fixed responsive design issues on pages:
Administration menu -> Users , Administration menu -> Spaces, http://joxi.ru/l2Z4DakCz8K6xr
Administration menu ->settings->notifications http://joxi.ru/Dr8RL0MtokxVZ2.
> Responsive design style issues were been fixed.

- .htaccess.dist
> Avoid error 403 with let's encrypt challenge

- protected/humhub/modules/content/controllers/ContentController.php
https://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes#affected-code
> Explicitly specifying the colum to search

- protected/humhub/components/mail/Mailer.php
- protected/humhub/components/mail/Message.php
In some enterprise environments, all internal communication that targets a large number of recipients must be signed by a trusted certificate to meet company security policies.
Feature Request #3649
> Provide a way to set smime signer on Message

- protected/humhub/modules/notification/targets/MailTarget.php
> Removed HTML encode for FROM attribute of Email

- protected/humhub/modules/file/Module.php
> Allowed using apostrophe in filename

- protected/humhub/modules/user/models/Profile.php
- protected/humhub/modules/user/models/User.php
> Trim function for username

- protected/humhub/modules/user/messages/cs/chooser.php
> Fix: Translation Bug

- CONTRIBUTING.md
The URL to the Contributor License Agreement (CLA) was incorrect.
> CONTRIBUTING.md: Corrected CLA link

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/comment/Module.php
> Fix #3885: Prevent comments on archived content

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/libs/ProfileBannerImage.php
> Fix #3986: redundant usage of yii\helpers\Html in ProfileBannerImage

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/queue/driver/MySQL.php
- protected/humhub/modules/queue/driver/MySQLCommand.php
> Fix #4009: Yii queue error handling broken

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/admin/views/logging/log_entries.php
- protected/humhub/modules/admin/views/space/index.php
- protected/humhub/modules/friendship/views/manage/list.php
- protected/humhub/modules/friendship/views/manage/requests.php
- protected/humhub/modules/friendship/views/manage/sent-requests.php
- protected/humhub/modules/topic/views/manage/overview.php
- protected/humhub/modules/user/models/Invite.php
- protected/humhub/modules/user/widgets/PermisionGridModuleFilter.php
> Fix #4004: Missing translation strings

- protected/humhub/modules/comment/controllers/CommentController.php
- protected/humhub/modules/comment/models/Comment.php
- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
- protected/humhub/modules/content/widgets/richtext/AbstractRichTextProcessor.php
- protected/humhub/modules/content/widgets/richtext/ProsemirrorRichTextProcessor.php
- protected/humhub/modules/post/controllers/PostController.php
- protected/humhub/modules/post/models/Post.php
> Fix #4008: Some richtext images are embedded as Base64

- protected/humhub/modules/file/components/StorageManager.php
> Fixed upload of base64 images fails

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/file/converter/PreviewImage.php
> Fix #4019: Animated Gifs not handled correctly with GMagick extension

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/activity/jobs/SendMailSummary.php
> Fix #4021: Activity mail queue job timeout error handling

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/ui/view/components/View.php
> Fix #4023: Background flickering on firefox page transition

- composer.json
- composer.lock
> Updated richtext version to 1.0.24

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/libs/SelfTest.php
> Enh #4026: Check memory limit in prerequisites check

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/admin/widgets/views/incomplete-setup-warning.php
> Fix #4050: Broken Cron-job documentation link used in cron info snippet

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/tests/codeception/config/config.php
> Fix #4080: Invalid absolute urls created in acceptance tests

- protected/humhub/docs/CHANGELOG.md
- static/js/humhub/humhub.ui.topNavigation.js
> Fix #4030: #search-menu-nav required in theme view layout main

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/content/resources/js/humhub.ui.richtext.prosemirror.js
Wrap richtext tables in `table-responsive` wrapper div for better overflow handling.
> Enh #4088: Improved table overflow handling in richtext content

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/content/components/ContentActiveRecord.php
- protected/humhub/modules/content/tests/codeception/unit/MoveContentTest.php
- protected/humhub/modules/post/models/Post.php
> Fix #4096: Missing CreatePost permission check in post model canMove

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/space/models/Space.php
- protected/humhub/modules/space/modules/manage/controllers/SecurityController.php
> Fix #4098: Space setting edit fails due to unique name validation

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/user/views/profile/about.php
Fixes https://github.com/humhub/humhub/issues/4056
> Fix #4056: Images not rendered in markdown profile field

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/search/views/search/index.php
> Fix #4046: Search results not highlighted

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/user/models/fieldtype/Birthday.php
> Fix: Profile about displays birthdays in current user timezone

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/admin/assets/AdminAsset.php
- protected/humhub/modules/admin/resources/js/humhub.admin.js
- protected/humhub/modules/admin/views/setting/design.php
> Fix #4108: Issues deleting network logo

- protected/humhub/docs/CHANGELOG.md
- static/js/humhub/humhub.oembed.js
- static/js/humhub/humhub.util.js
> Fix: Oembed not found due to different encoding

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/admin/models/forms/LogFilterForm.php
Fixes https://github.com/humhub/humhub/issues/4069
> Fix #4069: Duplication of log level filter parameter in pagination url

- .travis/install-dependencies.sh
> Updated travis chrome version to 83.0.4103.39

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/admin/models/forms/UserDeleteForm.php
> Fix #4116: Definitive user deletion doesn't work

- protected/humhub/modules/tour/tests/codeception/acceptance/TourCest.php
> Skip broken tour cest

- README.md
> update license link

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/notification/controllers/OverviewController.php
> Fix #4168: Erroneous pagination in notification overview

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/live/assets/LivePushAsset.php
- protected/humhub/modules/live/driver/Push.php
Fixes https://github.com/humhub/humhub/issues/4187
> Fix #4187: Use of invalid LivePushAsset namespace

- protected/humhub/modules/web/pwa/controllers/ServiceWorkerController.php
Omits sending of cookies in offline page request.
> Fix: Omit credentials in offline page request

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/content/Module.php
- protected/humhub/modules/content/controllers/ContentController.php
Implements https://github.com/humhub/humhub/issues/4194
- Enh #4194: Make max pinnable content configurable on space/profile level
- Enh #4194: Increased max pinnable space content
> - Enh #4194: Increased max pinnable space content

- protected/humhub/docs/CHANGELOG_DEV.md
- static/js/humhub/humhub.ui.widget.js
Fixes https://github.com/humhub/humhub/issues/4227
> Fix #4227: Removed redundant code from `humhub.ui.widget.js`

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/marketplace/components/OnlineModuleManager.php
- protected/humhub/modules/marketplace/controllers/BrowseController.php
- protected/humhub/modules/marketplace/controllers/UpdateController.php
- protected/humhub/modules/marketplace/migrations/m200715_171721_defaultOption.php
- protected/humhub/modules/marketplace/views/browse/_module.php
- protected/humhub/modules/marketplace/views/browse/list.php
- protected/humhub/modules/marketplace/views/browse/thirdpartyDisclaimer.php
- protected/humhub/modules/marketplace/views/update/list.php
> Enh: Community and Beta modules

- protected/humhub/modules/web/Events.php
- protected/humhub/modules/web/config.php
> Fix: Script nonce not working on first request

- protected/humhub/modules/stream/tests/codeception/acceptance/StreamCest.php
> Fixes StreamCest issue with comment fade animation.

- protected/humhub/modules/comment/views/comment/showPopup.php
> Fix: Hide comment seperator in comment modal if no comment is available.

- .travis.yml
> Added PHP 7.4 to Travis

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/comment/widgets/views/showMore.php
> Fix #4262: Additional hr in comment section

- protected/humhub/modules/comment/migrations/m200715_184207_commentIndex.php
- protected/humhub/modules/comment/migrations/m200729_080349_commentIndex_fix_order.php
> Changed comment combined index field order

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/like/widgets/LikeLink.php
> Fix #4161: Number of 'n more' likes is invalid

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/marketplace/views/browse/_module.php
> Fix #4285: All ThirdParty modules are also marked with 'Community'

- protected/humhub/components/db/MysqlSchema.php
- protected/humhub/config/common.php
- protected/humhub/docs/CHANGELOG.md
> Fix #4287: Fixed Yii2 compatibility issue with MySQL 8+

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/comment/models/Comment.php
> Fixed syntax error

- protected/humhub/modules/marketplace/messages/de/base.php
> Fix typo in german language

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/user/models/User.php
> Fix #4315: UserInvite (E-Mail Approval) not deleted when declining users

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/ldap/authclient/LdapAuth.php
> Fix #4318: Timezone issue with LDAP and birthday fields

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/admin/controllers/ApprovalController.php
- protected/humhub/modules/admin/messages/de/user.php
- protected/humhub/modules/admin/models/forms/ApproveUserForm.php
- protected/humhub/modules/admin/models/forms/AuthenticationSettingsForm.php
- protected/humhub/modules/file/models/File.php
- protected/humhub/modules/user/tests/codeception/unit/ApproveUserFormTest.php
- protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
> Fix: Internationalization of user approval/decline message text

- protected/humhub/components/bootstrap/ModuleAutoLoader.php
- protected/humhub/tests/codeception/unit/components/bootstrap/ModuleAutoLoaderTest.php
> Removed deprecated code

- protected/humhub/modules/admin/migrations/m141106_185632_log_init.php
and COLLATE utf8mb4_unicode_ci?
> May CHARACTER SET be utf8mb4?

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/marketplace/views/browse/list.php
- protected/humhub/modules/marketplace/views/update/list.php
> Added missing script nonce

- protected/humhub/modules/marketplace/views/update/list.php
> Fixed wrong import

- protected/humhub/modules/content/tests/codeception/unit/ContentEditTest.php
> Fixed ContentEditTest

- CHANGELOG_DEV.md
- protected/humhub/models/forms/CropProfileImage.php
- protected/humhub/modules/content/views/container-image/cropModal.php
> Issues Cropping Images #4111

- protected/humhub/modules/live/tests/codeception.yml
- protected/humhub/modules/live/tests/codeception/_bootstrap.php
- protected/humhub/modules/live/tests/codeception/_output/.gitignore
- protected/humhub/modules/live/tests/codeception/_support/AcceptanceTester.php
- protected/humhub/modules/live/tests/codeception/_support/FunctionalTester.php
- protected/humhub/modules/live/tests/codeception/_support/UnitTester.php
- protected/humhub/modules/live/tests/codeception/acceptance.suite.yml
- protected/humhub/modules/live/tests/codeception/acceptance/_bootstrap.php
- protected/humhub/modules/live/tests/codeception/config/functional.php
- protected/humhub/modules/live/tests/codeception/config/unit.php
- protected/humhub/modules/live/tests/codeception/fixtures/LiveFixture.php
- protected/humhub/modules/live/tests/codeception/fixtures/data/live.php
- protected/humhub/modules/live/tests/codeception/functional.suite.yml
- protected/humhub/modules/live/tests/codeception/functional/_bootstrap.php
- protected/humhub/modules/live/tests/codeception/unit.suite.yml
- protected/humhub/modules/live/tests/codeception/unit/_bootstrap.php
- protected/humhub/modules/live/tests/config/common.php
- protected/humhub/modules/live/tests/config/functional.php
- protected/humhub/modules/live/tests/config/test.php
- protected/humhub/modules/live/tests/config/unit.php
- protected/humhub/tests/codeception/_support/DynamicFixtureHelper.php
- protected/humhub/tests/codeception/_support/FixtureHelper.php
- protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
This PR adds the test directory of the live module and a fixture for clearing live data for test runs. Prior to this PR
live events were not cleared after tests.
> Enh: Added test layout and fixtures for live module.

- CHANGELOG_DEV.md
- protected/humhub/modules/ui/tests/codeception/unit/less/LessHelperTest.php
- protected/humhub/modules/ui/tests/codeception/unit/less/first.less
- protected/humhub/modules/ui/tests/codeception/unit/less/second.less
- protected/humhub/modules/ui/view/helpers/LessHelper.php
- protected/humhub/modules/ui/view/helpers/ThemeHelper.php
> #4401 Variables in the theme variables.less file cannot have an other variable as value

- CHANGELOG_DEV.md
- protected/humhub/modules/user/widgets/views/userSpaces.php
> Fix title quoting for space icons in widget “Member in these spaces”

- CHANGELOG_DEV.md
- protected/humhub/components/ActiveRecord.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/space/models/Membership.php
- protected/humhub/modules/user/controllers/RegistrationController.php
- protected/humhub/modules/user/migrations/m140303_125031_password.php
- protected/humhub/modules/user/models/Group.php
> Replace db Expression time now with func date()

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/notification/widgets/views/notificationOverviewList.php
> Fix #4430: Invalid notifications breaks notification overview

- protected/humhub/modules/content/widgets/WallEntryControls.php
- protected/humhub/modules/stream/actions/LegacyStreamTrait.php
Fixes https://github.com/humhub/humhub/issues/4440
> Fix #4440: WallEntry Compatibility issue in WallEntryControls

- .travis/install-dependencies.sh
Prior to this PR we had to manually sync the chrome driver version on travis.
Solution from: https://travis-ci.community/t/how-to-setup-chromedriver-74-with-chrome-74-for-travis/2678/10
> Enh: auto chrome driver version detection

- protected/humhub/modules/user/models/Group.php
Issue: https://github.com/humhub/humhub-modules-rest/issues/20
> Return bool result on add user into group

- .travis/install-dependencies.sh
> Fix invalid chrome version used in travis

- CHANGELOG_DEV.md
- protected/humhub/modules/live/Module.php
- protected/humhub/modules/user/models/Follow.php
> Enh/add user follows to live #3994

- protected/humhub/libs/LogoImage.php
> Double the logo size for high res displays

- CHANGELOG_DEV.md
- static/js/humhub/humhub.action.js
Fixes an issue in which the event trigger loader is not reset.
> Fix: Loader not removed from event trigger

- CHANGELOG_DEV.md
- protected/humhub/components/bootstrap/ModuleAutoLoader.php
Catches e.g. syntax errors in modules config.php.
> Fix: Catch all Throwables when loading module config

- CHANGELOG_DEV.md
- protected/humhub/tests/codeception/unit/widgets/TimeAgoWidgetTest.php
- protected/humhub/widgets/TimeAgo.php
- static/js/humhub/humhub.ui.additions.js
Implements https://github.com/humhub/humhub/issues/4407
> Enh #4407: Reworked TimeAgo widget

- composer.json
- composer.lock
- protected/humhub/assets/ClipboardJsAsset.php
> Updated clipboard-polyfill to v3

- composer.json
> Fixed composer.json error.

- protected/humhub/modules/content/widgets/UpdatedIcon.php
Fixes https://github.com/humhub/humhub/issues/4489
> Fix #4489 Use of proper UpdatedIcon tooltip date format

- CHANGELOG_DEV.md
- protected/humhub/modules/space/notifications/Invite.php
> Fix/invite notification target url #4354

- protected/humhub/modules/content/widgets/stream/StreamEntryOptions.php
Fixes https://github.com/humhub/humhub/issues/4487
> Fix #4487: Missing Space name on Profile Space post

- protected/humhub/modules/stream/resources/js/humhub.stream.Stream.js
Fixes https://github.com/humhub/humhub/issues/4488
> Fix #4488: Changing scope filter hides filter nav if no result was found

- protected/humhub/modules/stream/actions/Stream.php
> Fixed activity queue processing problem

- protected/humhub/modules/content/widgets/stream/StreamEntryOptions.php
> Fix console viewcontext

- CHANGELOG_DEV.md
> Changed CHANGELOG_DEV.md

- .travis.yml
- composer.json
- composer.lock
> PHP Platform 7.1

- CHANGELOG_DEV.md
- protected/humhub/config/common.php
> Prepare 1.7 Beta

- protected/humhub/modules/user/tests/codeception/acceptance/InviteCest.php
- protected/humhub/modules/user/tests/codeception/functional/MailInviteCest.php
> Fix: User invite tests

- protected/humhub/modules/comment/resources/js/humhub.comment.js
- protected/humhub/modules/comment/tests/codeception/acceptance/CommentCest.php
- protected/humhub/modules/comment/widgets/views/form.php
> Fixed Comment related tests

- protected/humhub/modules/admin/models/forms/ApproveUserForm.php
> Fixes translation text in ApproveUserForm

- CHANGELOG_DEV.md
- protected/humhub/modules/user/models/fieldtype/CheckboxList.php
> Fix #4534: In profile checkbox field,  not translatable

- CHANGELOG_DEV.md
> Updated CHANGELOG_DEV.md

- static/less/comment.less
- static/less/login.less
- static/less/markdown.less
- static/less/media.less
- static/less/mentioning.less
- static/less/mixins.less
- static/less/nav.less
- static/less/panel.less
- static/less/popover.less
- static/less/richtext.less
- static/less/table.less
- static/less/topbar.less
- static/less/tour.less
- static/less/user-feedback.less
Add usage of link color variable.
> Improved use of link color variable

- static/less/base.less
> Enh: Use of link color for data-toggle links

- CHANGELOG_DEV.md
- protected/humhub/modules/space/widgets/MyMembership.php
- protected/humhub/modules/space/widgets/views/myMembership.php
related to issue #4542 
- if created_at in membership model is empty:
> ignore memberSince for empty created_at membership #4542

- protected/humhub/modules/stream/resources/js/humhub.stream.Stream.js
> Fixes broken asset build

- protected/humhub/modules/content/components/ContentContainerModuleManager.php
- protected/humhub/modules/user/Module.php
> Fix: Use of wrong @since definition

- CHANGELOG_DEV.md
- protected/humhub/modules/like/widgets/views/likeLink.php
> Fix #4513, make like counter clickable in first like

- static/less/richtext.less
Partly fixes https://github.com/humhub/humhub/issues/4577
> Fixes border radius issue on mobile richtext focus menu

- CHANGELOG_DEV.md
- composer.lock
- protected/humhub/config/common.php
> Prepare Beta 2 Release - Updated Composer Dependencies

- CHANGELOG.md
- protected/humhub/models/forms/CropProfileImage.php
- protected/humhub/modules/content/views/container-image/cropModal.php
Fixes https://github.com/humhub/humhub/issues/4614
> Fix #4614: Profile Image crop broken

- CHANGELOG.md
- protected/humhub/modules/content/tests/codeception/unit/widgets/WallEntryOptionsTest.php
- protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php
Fixes https://github.com/humhub/humhub/issues/4612
> Fix #4612: Dashboard wall stream entry displays user name in sub title

- protected/humhub/config/common.php
- static/less/button.less
Issue: https://github.com/humhub/humhub-modules-theme-builder/issues/3
> Fix #3 theme builder module: Update new color less var @link on preview

- CHANGELOG.md
- protected/humhub/config/common.php
- protected/humhub/modules/file/libs/ImageHelper.php
> Fix #4609: Error on downscale command

- CHANGELOG.md
- protected/humhub/modules/file/widgets/views/showFiles.php
Changed grid size of image preview on fluid themes.
> Fixed image preview size on fluid themes.

- CHANGELOG.md
- protected/humhub/modules/file/libs/ImageHelper.php
> Fix #4621: Wrong image orientation on downscaling with imagick

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/migrations/m201115_083832_add_notify_users_to_group.php
- protected/humhub/modules/admin/views/group/edit.php
- protected/humhub/modules/user/models/Group.php
1) Added notify_users column to group table.
2) Add checkbox to group settings
> Optional Group Membership Notifications #4585

- protected/humhub/modules/user/controllers/RegistrationController.php
> RegistrationController.php doesn't return translated text #4591

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/ApprovalController.php
- protected/humhub/modules/admin/models/forms/ApproveUserForm.php
> Transfer default content of user approve/decline email to approve/decline form #4630

- protected/humhub/modules/content/models/Content.php
> Fix comment error in Content model

- CHANGELOG.md
- protected/humhub/modules/content/widgets/ContainerProfileHeader.php
- protected/humhub/modules/content/widgets/views/containerProfileHeader.php
- protected/humhub/modules/user/controllers/ImageController.php
Fixes https://github.com/humhub/humhub/issues/4650
> Fix #4650: `adminCanChangeUserProfileImages` option has not effect

- CHANGELOG.md
- protected/humhub/assets/DatePickerRussianLanguageAsset.php
- protected/humhub/libs/DbDateValidator.php
- protected/humhub/modules/ui/form/widgets/DatePicker.php
- static/js/compat/date/i18n/datepicker-ru.js
Patches https://github.com/humhub/humhub/issues/4638
and fixes https://github.com/humhub/humhub/issues/4596
This patch switches the jui language file for russian locale.
> Fix #4638: Profile settings do not accept birthdate in russian format

- protected/humhub/modules/content/tests/codeception/unit/ReadableContentQueryTest.php
> Improved test execution time in ReadableContentQueryTest

- protected/humhub/modules/web/security/controllers/ReportController.php
This PR obscures the nonce in csp report logs.
> Obscure nonce header in csp report log

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/views/space/index.php
Issue: https://github.com/humhub/humhub/issues/4692
> Fix visibility of the button “Add new space”

- protected/humhub/modules/user/models/GroupSpace.php
- protected/humhub/modules/user/tests/codeception/fixtures/GroupSpaceFixture.php
- protected/humhub/modules/user/tests/codeception/fixtures/UserFullFixture.php
- protected/humhub/modules/user/tests/codeception/fixtures/data/group_space.php
- protected/humhub/modules/user/tests/codeception/unit/models/GroupTest.php
> Fixed group tests using old default group space api

- CHANGELOG.md
- protected/humhub/migrations/m141021_162639_oembed_setting.php
- protected/humhub/migrations/m201217_071828_fix_oembed_setting.php
Issue: https://github.com/humhub/humhub/issues/4714
> Use https for sample OEmbed endpoints

- protected/humhub/modules/user/controllers/AccountController.php
- protected/humhub/modules/user/controllers/PasswordRecoveryController.php
> Fix success change password with error on save model

- protected/humhub/modules/user/models/forms/EditGroupForm.php
Issue: https://github.com/humhub/humhub/issues/4740
> Fix saving a group without Default Space

- protected/humhub/modules/comment/Module.php
- protected/humhub/modules/comment/permissions/CreateComment.php
With this p/r it allows the User to also allow/deny commenting on their post(s)
https://community.humhub.com/content/perma?id=232539
> Enh: canComment permissions

- protected/humhub/modules/admin/widgets/AdminMenu.php
- protected/humhub/modules/ui/menu/MenuEntry.php
> Removed deprecated addItem from AdminMenu

- .github/workflows/php-test.yml
- protected/humhub/modules/user/models/Invite.php
- protected/humhub/modules/user/tests/codeception/unit/models/GroupTest.php
- protected/humhub/tests/codeception/fixtures/data/setting.php
> Fixed group tests

- CHANGELOG.md
- protected/humhub/modules/like/Events.php
- protected/humhub/modules/like/widgets/LikeLink.php
Issue: https://github.com/humhub/humhub/issues/4743
> Hide "Like" link when no permission "Can like"

- CHANGELOG.md
- protected/humhub/libs/ProfileBannerImage.php
> Fix #4744: Banner image orientation not being processed

- CHANGELOG.md
- protected/humhub/modules/space/models/Space.php
- protected/humhub/modules/space/widgets/Image.php
Issue: https://github.com/humhub/tasks/issues/56
> Restrict HTML tags in Space name

- CHANGELOG_DEV.md
- protected/humhub/modules/file/components/StorageManager.php
- protected/humhub/modules/file/handler/DownloadFileHandler.php
- protected/humhub/modules/file/libs/FileHelper.php
- protected/humhub/modules/file/migrations/m210111_105355_hash.php
- protected/humhub/modules/file/models/File.php
- protected/humhub/modules/file/widgets/FileDownload.php
Issue: https://github.com/humhub/humhub/issues/4752
> File hash for download url

- CHANGELOG.md
- protected/humhub/modules/user/models/User.php
- protected/humhub/modules/user/models/forms/AccountChangeUsername.php
Issue: https://github.com/humhub/humhub/issues/3617
> Deny slashes in usernames

- CHANGELOG_DEV.md
- protected/humhub/modules/user/Module.php
- protected/humhub/modules/user/models/User.php
- protected/humhub/modules/user/models/forms/AccountChangeUsername.php
- protected/humhub/modules/user/tests/codeception/unit/models/UsernameTest.php
Issue: https://github.com/humhub/humhub/issues/4781
> Change allowed characters in username

- protected/humhub/modules/admin/tests/codeception/unit/DefaultPermissionsTest.php
- protected/humhub/modules/content/components/ContentContainerPermissionManager.php
Fix for PR https://github.com/humhub/humhub/pull/4678 because of failed test https://github.com/humhub/humhub/runs/1734952715?check_suite_focus=true#step:21:321
> Fix tests for default permission of content container

- CHANGELOG_DEV.md
- protected/humhub/modules/space/notifications/SpaceMemberNotificationCategory.php
Issue: https://github.com/humhub/humhub/issues/4787
> Always enable Space Membership Web Notifications

- CHANGELOG_DEV.md
- protected/humhub/modules/web/Module.php
- protected/humhub/modules/web/pwa/controllers/ManifestController.php
- protected/humhub/modules/web/pwa/widgets/LayoutHeader.php
> Enh: Added option to disable PWA/ServiceWorker Support

- CHANGELOG.md
- protected/humhub/modules/user/models/fieldtype/Select.php
Issue: https://github.com/humhub/humhub/issues/4794
> Fix CountrySelect definition

- CHANGELOG.md
- protected/humhub/modules/user/controllers/ProfileController.php
Issue: https://github.com/humhub/humhub/issues/4792
> Fix guest access to user profile home page

- CHANGELOG.md
- protected/humhub/compat/HForm.php
Issue: https://github.com/humhub/humhub/issues/4793
> Fix custom label of HForm field

- CHANGELOG.md
- protected/humhub/modules/user/models/fieldtype/Checkbox.php
Issue: https://github.com/humhub/humhub/issues/4389
NOTE! Please read the investigation and discussion in the issue before merging this PR!
> Require to check a checkbox if the profile field is required

- CHANGELOG.md
- protected/humhub/components/bootstrap/ModuleAutoLoader.php
Issue: https://github.com/humhub/humhub/issues/4569
> Prevent double module registration

- protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php
Issue: https://github.com/humhub/humhub/issues/4806
> Fix primary key of the table `contentcontainer_default_permission`

- CHANGELOG_DEV.md
- protected/humhub/modules/file/models/File.php
Issue from PR https://github.com/humhub/humhub/pull/4769#issuecomment-770253413
> Fix saving hash of a deleted file from disk

- protected/humhub/modules/comment/widgets/CommentEntryLinks.php
- protected/humhub/modules/content/widgets/WallEntryLinks.php
Issue: https://github.com/humhub/humhub/issues/4809
> Fix separator between comment and like links in wall stream

- CHANGELOG.md
- protected/humhub/modules/user/models/ProfileField.php
- protected/humhub/modules/user/tests/codeception/unit/models/ProfileFieldModelTest.php
Issue: https://github.com/humhub/humhub/issues/3687
> Disable profile field type for existing record

- protected/humhub/modules/live/resources/js/humhub.live.poll.js
> Fix js error in live poll client

- CHANGELOG_DEV.md
- protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub/issues/4818
> Add db/table collation prerequisite check

- CHANGELOG.md
- protected/humhub/migrations/m210204_054203_fix_settings_unique_index.php
Issue: https://github.com/humhub/humhub/issues/4825
> Make settings index(name, module_id) unique

- CHANGELOG_DEV.md
- protected/humhub/modules/user/models/User.php
Issue: https://github.com/humhub/humhub/issues/4831
> Validate username by pattern only on change or for new users

- static/less/markdown.less
- static/less/richtext.less
Fixes https://github.com/humhub/humhub/issues/4820
> Fix markdown table border missing

- protected/humhub/modules/user/components/User.php
No issue, only error from chat:
> Also seeing an error for humhub\modules\user\components\User::mustChangePassword in protected/humhub/modules/live/controllers/PollController.php?
> Fix User::mustChangePassword()

- CHANGELOG_DEV.md
- protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub/issues/4835
> SelfTest - Fix Database Min Version detection

- protected/humhub/modules/admin/controllers/SpaceController.php
- protected/humhub/modules/admin/controllers/UserPermissionsController.php
- protected/humhub/modules/admin/tests/codeception/unit/DefaultPermissionsTest.php
- protected/humhub/modules/content/components/ContentContainerDefaultPermissionManager.php
From chat: Any reasons why this(`ContentContainerDefaultPermissionManager::contentcontainer_class`) is not camelCase?
> Clean up class ContentContainerDefaultPermissionManager

- CHANGELOG_DEV.md
- protected/humhub/modules/space/behaviors/SpaceModelMembership.php
- protected/humhub/modules/space/models/forms/InviteForm.php
Issue: https://github.com/humhub/humhub/issues/4856
> Allow to invite users to space with pending membership application

- CHANGELOG_DEV.md
- protected/humhub/widgets/mails/MailContentEntry.php
Issue: https://github.com/humhub/humhub/issues/4869
> Fix cached comment content in email notification

- CHANGELOG_DEV.md
- protected/humhub/modules/content/widgets/richtext/converter/BaseRichTextConverter.php
- protected/humhub/widgets/mails/MailContentEntry.php
Issue: https://github.com/humhub/humhub/issues/4857
Related issue: https://github.com/humhub/humhub/issues/4869
> Fix wrong content id used in building cache key

- README.md
Remove travis build status from README.md https://github.com/humhub/humhub/issues/4843
> Remove travis badge from README.md

- CHANGELOG_DEV.md
- protected/humhub/modules/live/resources/js/humhub.live.poll.js
> Fixes error thrown if live poll broadcast focus event is triggered

- protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextShortTextConverterTest.php
- protected/humhub/modules/content/widgets/richtext/converter/RichTextToShortTextConverter.php
- Chng: Aligned OPTIONS_PRESERVE_SPACES to OPTION_PRESERVE_SPACES
- Enh: Implemented RichTextToShortTextConverter::OPTION_NL2BR
> Chng: Changed OPTIONS_PRESERVE_SPACES to OPTION_PRESERVE_SPACES

- CHANGELOG.md
- protected/humhub/modules/content/resources/js/humhub.content.container.js
Issue: https://github.com/humhub/humhub/issues/4895
> Fix js warning of not loaded module space.chooser

- CHANGELOG_DEV.md
- protected/humhub/modules/comment/Events.php
- protected/humhub/modules/like/Events.php
Issue: https://github.com/humhub/humhub/issues/4907
> Fix positions of Comment / Like links under posts

- CHANGELOG_DEV.md
- protected/humhub/components/access/ControllerAccess.php
- protected/humhub/components/behaviors/AccessControl.php
Issue: https://github.com/humhub/humhub/issues/4912
> Restrict guest access on maintenance mode

- static/less/form.less
BugFix for
#4841 
Made style of label selector for checkboxes in the pending registration grid.
> Delete pending registrations automatically - 2 bugfix #4225

- CHANGELOG.md
- protected/humhub/modules/admin/models/UserApprovalSearch.php
Issue: https://github.com/humhub/humhub/issues/4921
> Fix ambiguous column status

- CHANGELOG.md
- protected/humhub/modules/file/Module.php
- protected/humhub/modules/file/tests/codeception/unit/FileValidatorTest.php
- protected/humhub/modules/file/validators/FileValidator.php
Issue: https://github.com/humhub/humhub/issues/4923
> Replace denied characters with underscore in uploaded file names

- CHANGELOG.md
- protected/humhub/config/common.php
- protected/humhub/modules/admin/widgets/AdminMenu.php
- protected/humhub/modules/admin/widgets/UserMenu.php
Issue: https://github.com/humhub/humhub/issues/4931
> Fix highlight parent navigations for sub section "Profile Permissions" (and LDAP)

- CHANGELOG.md
- protected/humhub/modules/user/messages/de/account.php
> Fix #4940: Typo in German translation Benachrichtigungen

- CHANGELOG.md
- protected/humhub/modules/ldap/commands/LdapController.php
- protected/humhub/modules/ldap/components/ZendLdap.php
> LDAP PHP 8 Issues 

- CHANGELOG.md
- protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php
Issue: https://github.com/humhub/humhub/issues/4946
> Fix migration of the default permissions

- CHANGELOG.md
- protected/humhub/modules/content/widgets/richtext/extensions/emoji/RichTextEmojiExtension.php
Issue: https://github.com/humhub/humhub/issues/4955
> Fix convert emoji with sign “+”

- CHANGELOG.md
- protected/humhub/components/ModuleManager.php
- protected/humhub/components/bootstrap/ModuleAutoLoader.php
Issue: https://github.com/humhub/humhub/issues/4569
> Config to overwrite module path

- CHANGELOG.md
- protected/humhub/modules/stream/actions/Stream.php
Issue: https://github.com/humhub/humhub/issues/4898
> No streamExcludes option when loading single stream entry

- composer.json
- composer.lock
- protected/humhub/tests/codeception/_support/ApiTester.php
- protected/humhub/tests/codeception/_support/HumHubApiTestCest.php
- protected/humhub/tests/codeception/api.suite.yml
- protected/humhub/tests/codeception/api/_bootstrap.php
- protected/humhub/tests/codeception/config/api.php
Related to issue https://github.com/humhub/humhub-modules-rest/issues/33 in order to test REST API endpoints.
> Add “codeception/module-rest” for test REST API modules

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/UserController.php
- protected/humhub/modules/user/commands/UserController.php
Issue: https://github.com/humhub/humhub/issues/4951
> New command to delete user

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/GroupController.php
- protected/humhub/modules/user/models/Group.php
Issue: https://github.com/humhub/humhub/issues/4972
> Fix enabling to send notification on remove user from group

- CHANGELOG.md
- protected/humhub/modules/marketplace/controllers/UpdateController.php
> Enh #4967: Module update broken with expired licence key

- CHANGELOG.md
- protected/humhub/modules/stream/actions/Stream.php
Issues: https://github.com/humhub/humhub/issues/4985, https://github.com/humhub/tasks/issues/102.
> Fix Activity Mail QueryParams on console mode

- CHANGELOG_DEV.md
- protected/humhub/libs/DynamicConfig.php
- protected/humhub/migrations/m210331_115144_default_timezone.php
- protected/humhub/modules/admin/models/forms/BasicSettingsForm.php
- protected/humhub/modules/admin/views/setting/basic.php
- protected/humhub/modules/installer/controllers/ConfigController.php
- protected/humhub/modules/user/controllers/AccountController.php
- protected/humhub/modules/user/models/User.php
Issue: https://github.com/humhub/humhub/issues/4871
> Default timezone for guests

- CHANGELOG.md
- protected/humhub/modules/admin/views/user-profile/_fieldGrid.php
Issue: https://github.com/humhub/tasks/issues/104
> Translate profile field title in admin list

- CHANGELOG.md
- protected/humhub/tests/codeception/_support/BaseTester.php
- protected/humhub/tests/codeception/_support/FunctionalTester.php
Issue: https://github.com/humhub/humhub-modules-rest/issues/33#issuecomment-814293868
> Fix loading of fixture spaces on tests

- CHANGELOG.md
- protected/humhub/modules/activity/tests/codeception/acceptance/ActivityStreamCest.php
- protected/humhub/modules/content/tests/codeception/_support/AcceptanceTester.php
- protected/humhub/modules/content/tests/codeception/acceptance/ArchivedCest.php
- protected/humhub/modules/content/tests/codeception/fixtures/data/content.php
- protected/humhub/modules/marketplace/Module.php
- protected/humhub/modules/post/tests/codeception/fixtures/data/post.php
- protected/humhub/modules/stream/models/filters/DefaultStreamFilter.php
- protected/humhub/modules/stream/tests/codeception/acceptance/StreamCest.php
Issue: https://github.com/humhub/humhub/issues/4626
> Fix visibility of content in profile stream from archived spaces

- CHANGELOG.md
- protected/humhub/modules/activity/stream/ActivityStreamQuery.php
> Fixed acitvity stream performance

- CHANGELOG.md
- protected/humhub/components/Response.php
Issue: https://github.com/humhub/humhub/issues/5013
> Fix undefined $_SERVER['SERVER_SOFTWARE']

- CHANGELOG.md
- protected/humhub/modules/content/widgets/richtext/converter/RichTextToEmailHtmlConverter.php
- protected/humhub/modules/content/widgets/richtext/extensions/file/FileExtension.php
- protected/humhub/modules/content/widgets/richtext/extensions/link/LinkParserBlock.php
- protected/humhub/modules/file/actions/DownloadAction.php
- protected/humhub/modules/file/models/File.php
Issue: https://github.com/humhub/humhub-modules-news/issues/23
> Allow to read image URLs with token param

- CHANGELOG.md
- protected/humhub/modules/file/commands/FileController.php
- protected/humhub/modules/user/authclient/AuthClientHelpers.php
> Fix #5017: File CLI Command fails due to manually deleted files

- CHANGELOG.md
- protected/humhub/modules/comment/activities/views/mail/newComment.php
- protected/humhub/modules/content/activities/views/mail/created.php
- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
- protected/humhub/modules/user/authclient/AuthClientHelpers.php
> Fix #4947: Preview text maxLength issue 

- protected/humhub/modules/content/tests/codeception/unit/RichTextToEmailHtmlConverterTest.php
Issue: https://github.com/humhub/humhub-modules-news/issues/23#issuecomment-823247330
> Test RichTextToEmailHtmlConverter

- CHANGELOG.md
- protected/humhub/modules/user/models/Group.php
Issue: https://github.com/humhub/humhub/issues/5022
> Fix assign default group on user registration

- protected/humhub/modules/file/controllers/FileController.php
> Allow download action even without guest access

- CHANGELOG.md
- protected/humhub/modules/content/widgets/richtext/converter/BaseRichTextConverter.php
Issue: https://github.com/humhub/humhub/issues/5039
> Fix RichText converter in HTML format

- CHANGELOG_DEV.md
- protected/humhub/config/common.php
- protected/humhub/libs/DynamicConfig.php
- protected/humhub/tests/codeception/config/dynamic.php
Issue: https://github.com/humhub/humhub/issues/5045
> Remove FormatterApp

- protected/humhub/components/Application.php
Issue: https://github.com/humhub/humhub/issues/5045#issuecomment-827670743
> Remove config param 'FormatterApp' on init application

- protected/humhub/components/console/Application.php
Issue: https://github.com/humhub/humhub/issues/5045#issuecomment-828266250
> Remove config param 'FormatterApp' on init console application

- CHANGELOG_DEV.md
- protected/humhub/modules/content/tests/codeception/functional/RichTextToEmailHtmlConverterCest.php
Issue: https://github.com/humhub/humhub/issues/5026
> Tests for tokenized image urls in email message

- CHANGELOG.md
- protected/humhub/widgets/views/footerNavigation_login.php
Issue: https://github.com/humhub-contrib/legal/issues/29
> Fix login form view on browser back button after footer link

- CHANGELOG_DEV.md
- protected/humhub/libs/SelfTest.php
https://github.com/humhub/humhub/issues/5065#issuecomment-839544841
> Add checking for php PCNTL extension

- CHANGELOG_DEV.md
- protected/humhub/tests/codeception/_support/ApiTester.php
- protected/humhub/tests/codeception/_support/HumHubApiTestCest.php
Issue: https://github.com/humhub/rest/issues/53#issuecomment-839629472
**Note:** wait merging until api tests for all modules will be completed from this comment https://github.com/humhub/rest/issues/53#issuecomment-839629472.
> Enhance API tests

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/controllers/UserController.php
Issue: https://github.com/humhub/humhub/issues/5062
> Show user ID on admin user edit page

- CHANGELOG_DEV.md
- protected/humhub/modules/space/controllers/SpaceController.php
- protected/humhub/modules/space/views/space/home.php
- protected/humhub/modules/stream/resources/js/humhub.stream.Stream.js
- protected/humhub/modules/user/controllers/ProfileController.php
- protected/humhub/modules/user/views/profile/home.php
Issue: https://github.com/humhub/humhub/issues/4927
> Hide post input field on single entry stream

- CHANGELOG.md
- protected/humhub/modules/space/modules/manage/views/default/index.php
Issue: https://github.com/humhub/humhub/issues/5088
> Set max length for space description input

- CHANGELOG_DEV.md
- protected/humhub/modules/dashboard/stream/filters/DashboardMemberStreamFilter.php
- protected/humhub/modules/dashboard/tests/codeception/unit/DashboardMemberStreamQueryTest.php
- protected/humhub/modules/friendship/models/Friendship.php
- protected/humhub/modules/friendship/tests/codeception/unit/FriendShipTest.php
- protected/humhub/modules/live/tests/codeception/unit/LegitimationTest.php
- protected/humhub/modules/user/widgets/UserFollowButton.php
Issue: https://github.com/humhub/humhub/issues/5089
> Allow to Follow users independent of Friendship

- CHANGELOG_DEV.md
- protected/humhub/modules/space/tests/codeception/acceptance/InviteCest.php
- protected/humhub/modules/space/tests/codeception/acceptance/RequestMembershipCest.php
- protected/humhub/modules/user/models/Profile.php
- protected/humhub/modules/user/tests/codeception/unit/UserModuleTest.php
- protected/humhub/tests/codeception/_pages/DirectoryPage.php
Issue: https://github.com/humhub/humhub/issues/5101
> Fix to allow editabling of not required profile fields

- CHANGELOG_DEV.md
- static/js/humhub/humhub.directory.js
Issue: https://github.com/humhub/team_tasks/issues/122
> Fix button "Load more" initialization on Pjax loading

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/models/forms/PeopleSettingsForm.php
- protected/humhub/modules/admin/views/user-people/index.php
- protected/humhub/modules/ui/widgets/DirectoryFilters.php
- protected/humhub/modules/ui/widgets/views/directoryFilter.php
- protected/humhub/modules/user/components/PeopleQuery.php
Issue: https://github.com/humhub/team_tasks/issues/123
> New sorting option "Default" for people directory page

- CHANGELOG.md
- protected/humhub/modules/user/views/auth/login.php
- protected/humhub/modules/user/views/auth/login_modal.php
Issue: https://github.com/humhub/humhub/issues/5107
> Fix captcha client validation after request new code

- protected/humhub/modules/admin/models/forms/PeopleSettingsForm.php
- protected/humhub/modules/user/widgets/PeopleFilters.php
Issue: https://github.com/humhub/team_tasks/issues/123#issuecomment-857535692
> Changes for default group of people sorting filter

- CHANGELOG.md
- protected/humhub/modules/admin/views/setting/oembed_edit.php
- protected/humhub/modules/admin/widgets/AdvancedSettingMenu.php
Issue: https://github.com/humhub/wording/issues/22
> Fix misplaced OEmbed provider buttons on general settings form

- package-lock.json
Issue: https://github.com/humhub/team_tasks/issues/124
> Fix Dependabot warning

- CHANGELOG_DEV.md
- protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub/pull/5071#issuecomment-862458499
> Don't require PCNTL extension

- CHANGELOG_DEV.md
- protected/humhub/components/i18n/Formatter.php
Issue: https://github.com/humhub/humhub/issues/5137
> Fix convert to short integer on PHP 8

- CHANGELOG_DEV.md
- protected/humhub/modules/user/models/fieldtype/Checkbox.php
- protected/humhub/modules/user/models/fieldtype/CheckboxList.php
Issue: https://github.com/humhub/humhub/issues/5136
> Fix get value of user profile field with type "Checkbox List"

- CHANGELOG_DEV.md
- protected/humhub/modules/space/widgets/MembershipButton.php
- protected/humhub/modules/space/widgets/views/membershipButton.php
- protected/humhub/modules/space/widgets/views/profileHeaderControls.php
Issue: https://github.com/humhub/humhub/issues/5149
> Use a link mode for space button "Join" from space header

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/views/user-profile/_fieldGrid.php
> Enh #5144: Show sort order in profile fields settings

- CHANGELOG_DEV.md
- protected/humhub/modules/user/activities/UserFollow.php
Issue: https://github.com/humhub/humhub/issues/4459
> Make UserFollow activity public

- CHANGELOG_DEV.md
- protected/humhub/libs/SelfTest.php
Issue: https://github.com/humhub/humhub/issues/4830
> Fix Prerequisites / Self Test translations

- .github/workflows/php-test.yml
- index-test.php
- index.php
- protected/humhub/modules/user/tests/codeception/acceptance/ProfileCest.php
- protected/humhub/tests/codeception/_support/AcceptanceTester.php
- protected/humhub/tests/codeception/config/acceptance.php
Issue: https://github.com/humhub/humhub/issues/3824
> Run acceptance tests with pretty URLs

- CHANGELOG_DEV.md
- Gruntfile.js
Issue: https://github.com/humhub/humhub/issues/3824#issuecomment-876921407
> Update grunt command "test-server" to work with pretty URLs

- CHANGELOG.md
- protected/humhub/modules/ui/view/components/View.php
> Fix #5155: Open basedir restriction error in with PHP 7.4.21/8.0.8

- CHANGELOG_DEV.md
- protected/humhub/compat/HForm.php
- protected/humhub/modules/admin/controllers/UserController.php
https://github.com/humhub/humhub/issues/5169
> Enh #5169: Enable more than 50 groups to a user

- CHANGELOG_DEV.md
- protected/humhub/modules/content/widgets/ContainerTagPicker.php
- protected/humhub/modules/tour/views/tour/welcome.php
Issue: https://github.com/humhub/humhub/issues/5174
> Fix tags field on welcome modal window

- CHANGELOG_DEV.md
- static/js/humhub/humhub.ui.modal.js
Issue: https://github.com/humhub/humhub/issues/5173
> Fix closing the action confirmation modal window on top close icon

- CHANGELOG_DEV.md
- protected/humhub/modules/dashboard/views/dashboard/index_guest.php
- protected/humhub/modules/space/widgets/NewSpaces.php
- protected/humhub/modules/space/widgets/views/newSpaces.php
- protected/humhub/modules/user/widgets/NewMembers.php
- protected/humhub/modules/user/widgets/views/newMembers.php
Issue: https://github.com/humhub/humhub/issues/5172
> Move directory widgets

- CHANGELOG_DEV.md
- protected/humhub/modules/user/components/CheckPasswordValidator.php
- protected/humhub/modules/user/models/User.php
> Fix #5182: Password field should not be required if user has no password

- protected/humhub/modules/user/components/CheckPasswordValidator.php
Issue: https://github.com/humhub/humhub/issues/5182#issuecomment-884539695
> Fix validation for user current password

- CHANGELOG.md
- protected/humhub/components/export/ArrayColumn.php
- protected/humhub/modules/admin/controllers/UserController.php
Issue: https://github.com/humhub/humhub/issues/5195
> Fix export users with tags data

- protected/humhub/modules/ui/messages/fr/base.php
> Added Translation for 'Reset filters'

- CHANGELOG.md
- protected/humhub/modules/user/migrations/m210727_102150_follow_friend.php
Issue: https://github.com/humhub/humhub/issues/5200
> Auto creating following for friends

- CHANGELOG_DEV.md
- protected/humhub/components/ModuleManager.php
- protected/humhub/components/bootstrap/ModuleAutoLoader.php
Issue: https://github.com/humhub/humhub/issues/4242
> More failsave module loading when reading module config

- CHANGELOG_DEV.md
- protected/humhub/modules/user/widgets/views/userListBox.php
Issue: https://github.com/humhub/humhub/issues/3688
> Use Image widget in user list

- CHANGELOG.md
- protected/humhub/modules/space/modules/manage/views/default/index.php
- protected/humhub/modules/space/widgets/views/spaceChooserItem.php
Issue: https://github.com/humhub/humhub/issues/5189
> Reduce minimum character limit for tags to 2 chars

- CHANGELOG.md
- protected/humhub/modules/user/models/fieldtype/Birthday.php
Issue: https://github.com/humhub/humhub/issues/5187
> Fix birthday with hidden year in a language-specific format

- CHANGELOG.md
- protected/humhub/modules/space/resources/js/humhub.space.chooser.js
- protected/humhub/modules/space/widgets/views/spaceChooserItem.php
https://github.com/humhub/humhub/issues/5189#issuecomment-888420650
> Hide tags on space chooser if no keyword inside tags

- CHANGELOG.md
- protected/humhub/modules/admin/notifications/ExcludeGroupNotification.php
- protected/humhub/modules/admin/notifications/IncludeGroupNotification.php
- protected/humhub/modules/space/widgets/Chooser.php
- protected/humhub/modules/space/widgets/views/spaceChooser.php
- protected/humhub/modules/user/widgets/views/userTags.php
Issue: https://github.com/humhub/humhub/issues/5215
> Fix links to old directory

- CHANGELOG_DEV.md
- protected/humhub/modules/file/handler/FileHandlerCollection.php
- protected/humhub/modules/file/views/view/index.php
Issue: https://github.com/humhub/humhub/issues/5216
> Separate view document button

- CHANGELOG.md
- protected/humhub/modules/user/views/account/editSettings.php
Issue: https://github.com/humhub/humhub/issues/5189#issuecomment-891980235
> Reduce minimum character limit for user tags to 2 chars

- CHANGELOG.md
- protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextEmailHtmlConverterTest.php
- protected/humhub/modules/content/widgets/richtext/converter/RichTextToEmailHtmlConverter.php
Issue: https://github.com/humhub/humhub/issues/5095
> Fix space between URLs and text in notification message

- CHANGELOG.md
- protected/humhub/modules/content/tests/codeception/functional/RichTextToEmailHtmlConverterCest.php
- protected/humhub/widgets/mails/MailContentEntry.php
Issue: https://github.com/humhub/humhub/issues/5096
> Render links in email notifications

- protected/humhub/modules/topic/messages/nl/base.php
- [ x] Bugfix
- [x ] No
It's just the removal of an error in the translations
> Removed strong&gt; from the Dutch translations

- protected/humhub/modules/content/tests/codeception/functional/RichTextToEmailHtmlConverterCest.php
Issue: https://github.com/humhub/team_tasks/issues/136
> Fix errors in tests RichTextToEmailHtmlConverterCest

- CHANGELOG_DEV.md
- protected/humhub/modules/file/resources/js/humhub.file.js
- protected/humhub/modules/file/widgets/UploadInput.php
Issue: https://github.com/humhub/cfiles/issues/83
> Extend upload buttons to use a paste zone

- CHANGELOG.md
- protected/humhub/components/Migration.php
- protected/humhub/modules/content/migrations/m210211_051243_container_tag.php
Issue: https://github.com/humhub/humhub/issues/5204
> Fix migration of container tags

- CHANGELOG.md
- protected/humhub/components/Application.php
- protected/humhub/components/i18n/I18N.php
- protected/humhub/modules/user/controllers/RegistrationController.php
- protected/humhub/modules/user/models/Invite.php
- protected/humhub/modules/user/models/forms/AccountRecoverPassword.php
- protected/humhub/tests/codeception/unit/libs/DBDateValidatorTest.php
Issue: https://github.com/humhub/team_tasks/issues/139
> Fix translate with not defined language

- CHANGELOG_DEV.md
- protected/humhub/modules/notification/Events.php
- protected/humhub/modules/notification/Module.php
Issue: https://github.com/humhub/humhub/issues/5257
> Delete old unread notifications

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/views/user-profile/_fieldGrid.php
Issue: https://github.com/humhub/humhub/issues/5143
> Unlimited page size for profile fields

- CHANGELOG.md
- protected/humhub/modules/admin/models/forms/LogFilterForm.php
Issue: https://github.com/humhub/humhub/issues/5265
> Fix logging filter "Error" when not entries

- protected/humhub/modules/content/widgets/WallEntryControls.php
- protected/humhub/modules/content/widgets/views/notificationSwitchLink.php
- protected/humhub/modules/stream/resources/js/humhub.stream.StreamEntry.js
Related to task https://github.com/humhub/cfiles/issues/127
> Changes to allow use wall entry controls from external module "cfiles"

- CHANGELOG_DEV.md
- static/js/humhub/humhub.ui.additions.js
Related to the issue: https://github.com/humhub/wiki/issues/163
> Allow to add new item on ui selector

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/controllers/UserController.php
- protected/humhub/modules/admin/grid/UserActionColumn.php
- protected/humhub/modules/user/components/Impersonator.php
- protected/humhub/modules/user/components/User.php
- protected/humhub/modules/user/controllers/AuthController.php
- protected/humhub/modules/user/models/User.php
- protected/humhub/modules/user/tests/codeception/_support/AcceptanceTester.php
- protected/humhub/modules/user/tests/codeception/acceptance/ImpersonateCest.php
- protected/humhub/modules/user/tests/codeception/unit/ImpersonateTest.php
- protected/humhub/modules/user/widgets/AccountTopMenu.php
Issue: https://github.com/humhub/humhub/issues/3546
> Sign in back from impersonate mode

- CHANGELOG.md
- protected/humhub/modules/admin/models/forms/PeopleSettingsForm.php
Issue: https://github.com/humhub/humhub/issues/5301
> Change people default sorting

- CHANGELOG.md
- protected/humhub/modules/space/widgets/Menu.php
Issue: https://github.com/humhub/team_tasks/issues/144
> Fix reset of the space homepage settings

- CHANGELOG_DEV.md
- protected/humhub/modules/file/behaviors/VersioningSupport.php
- protected/humhub/modules/file/behaviors/Versions.php
- protected/humhub/modules/file/interfaces/AttachedFileVersioningSupport.php
- protected/humhub/modules/file/models/File.php
Issue: https://github.com/humhub/cfiles/issues/121#issuecomment-920634420
> File versioning

- composer.lock
- protected/humhub/modules/ui/form/widgets/ContentVisibilitySelect.php
Issue: https://github.com/humhub/cfiles/issues/140
> Improve checkbox widget ContentVisibilitySelect

- CHANGELOG_DEV.md
- protected/humhub/libs/ProfileImage.php
- protected/humhub/modules/content/controllers/ContainerImageController.php
- protected/humhub/modules/file/Module.php
- protected/humhub/modules/file/libs/ImageHelper.php
> Limit uploading profile images

- CHANGELOG.md
- protected/humhub/modules/stream/models/filters/DefaultStreamFilter.php
Issue: https://github.com/humhub/humhub/issues/5316
> Fix filter "I'm involved" on dashboard

- static/js/humhub/humhub.directory.js
Issue: https://github.com/humhub/humhub/issues/5318
> Fix autoload People/Spaces on scroll down

- protected/humhub/modules/ui/view/helpers/ThemeHelper.php
> fix: #5324 check if module provided via string

- CHANGELOG.md
- protected/humhub/modules/content/components/ContentContainerActiveRecord.php
- protected/humhub/modules/content/models/ContentContainerTagRelation.php
Related issue https://github.com/humhub/rest/issues/67. Space tags were not updated from REST API because original model `\humhub\modules\space\modules\manage\models\AdvancedSettingsSpace` instead of expecting `\humhub\modules\space\models\Space`.
> Fix update container tags

- CHANGELOG_DEV.md
- protected/humhub/modules/space/Events.php
- protected/humhub/modules/space/Module.php
> Added option to hide Spaces menu item

- CHANGELOG.md
- protected/humhub/components/Migration.php
Issue: https://github.com/humhub/humhub/issues/5398
> Fix checking of foreign table index on install "contentcontainer_tag"

- CHANGELOG_DEV.md
- protected/humhub/modules/search/controllers/MentioningController.php
Issue: https://github.com/humhub/humhub/issues/5402
> Fix mentioning search in comment content

- protected/humhub/modules/space/messages/de/chooser.php
> Fix new entry translation

- CHANGELOG_DEV.md
- protected/humhub/modules/stream/models/filters/DefaultStreamFilter.php
- protected/humhub/modules/stream/models/filters/StreamQueryFilter.php
https://github.com/humhub/humhub/issues/5386
related to https://github.com/humhub/humhub/pull/5011
> #5386 empty archived stream fix

- CHANGELOG_DEV.md
- protected/humhub/modules/comment/models/Comment.php
Issue: https://github.com/humhub/humhub/issues/5427
> Fix deep comment link with enabled caching

- CHANGELOG_DEV.md
- protected/humhub/modules/content/tests/codeception/acceptance/ArchivedCest.php
- protected/humhub/modules/stream/tests/codeception/acceptance/StreamCest.php
https://github.com/humhub/team_tasks/issues/71
[fixed] stream test - post selector regardless of id in datatable
[fixed] stream test - scroll page on testFilterInvolved
[fixed] archived test - scroll page on testDashboardArchivedContentWithFilter
> fixed tests for galera compatibility

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/views/group/edit.php
- protected/humhub/modules/space/widgets/views/inviteModal.php
> Enh: Better usage of UserPicker in Form Definition

- CHANGELOG_DEV.md
- protected/humhub/modules/file/commands/FileController.php
- protected/humhub/modules/file/components/StorageManager.php
- protected/humhub/modules/file/components/StorageManagerInterface.php
> Exclude history variants

- CHANGELOG.md
- static/css/flatelements.css
> Fix checkbox style

- protected/humhub/modules/comment/models/Comment.php
Fix bug of caching of the limited comments after wrong fix here https://github.com/humhub/humhub/commit/0945f99752a2f7c16e04d08e7751c11faa49b14e#diff-4fcd54238adfe8774ee607eeadd9ff1c821166188d5f9dabd37cac4e2729a218R217
> Fix comments caching

- static/js/humhub/humhub.client.js
Fix bug from PR https://github.com/humhub/humhub/pull/5450.
> Fix confirmation for unsaved form changes

- CHANGELOG_DEV.md
- protected/humhub/modules/tour/resources/js/humhub.tour.js
Issue: https://github.com/humhub/humhub/issues/5434
> Hide disabled next/prev buttons on guide first/last steps

- CHANGELOG.md
- protected/humhub/migrations/m201228_064513_default_group.php
Issue: https://github.com/humhub/humhub/issues/5453
> Fix migration of default group

- CHANGELOG.md
- protected/humhub/modules/comment/activities/NewComment.php
- protected/humhub/modules/comment/models/Comment.php
- protected/humhub/modules/comment/notifications/NewComment.php
- protected/humhub/modules/comment/widgets/CommentControls.php
Issue: https://github.com/humhub/humhub/issues/5457
> Use permalink comment in notification

- CHANGELOG.md
- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
Issue: https://github.com/humhub/humhub/issues/5465
> Fix empty RichText

- .github/workflows/php-test.yml
- protected/humhub/modules/space/controllers/CreateController.php
Improve invitation on creating a space.
> Improved Invitation

- CHANGELOG.md
- protected/humhub/modules/comment/models/Comment.php
Issue: https://github.com/humhub/humhub/pull/5464#issuecomment-993583849
> Fix comment highlighting on permalink

- protected/humhub/modules/comment/models/Comment.php
Issue: https://github.com/humhub/team_tasks/issues/172
> Fix test comments with same date

- CHANGELOG.md
- protected/humhub/modules/content/components/ContentContainerPermissionAccess.php
Issue: https://github.com/humhub/humhub/issues/5479
> Fix ContentContainerPermissionAccess without provided container

- CHANGELOG_DEV.md
- protected/humhub/components/mail/Mailer.php
- protected/humhub/models/Setting.php
- protected/humhub/modules/admin/models/forms/MailingSettingsForm.php
- protected/humhub/modules/admin/views/setting/mailing_server.php
- protected/humhub/modules/notification/targets/MailTarget.php
Enh #5224: Add reply-to email in the settings
> Enh #5224: Add reply-to email in the settings

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/views/approval/index.php
- protected/humhub/modules/user/models/User.php
> invite by in approval

- CHANGELOG_DEV.md
- protected/humhub/events/OembedFetchEvent.php
- protected/humhub/migrations/m220121_193617_oembed_setting_update.php
- protected/humhub/models/UrlOembed.php
- protected/humhub/modules/admin/controllers/SettingController.php
- protected/humhub/modules/admin/models/forms/OEmbedProviderForm.php
- protected/humhub/modules/admin/views/setting/oembed.php
- protected/humhub/modules/admin/views/setting/oembed_edit.php
- protected/humhub/tests/codeception/fixtures/data/setting.php
- protected/humhub/tests/codeception/unit/models/UrlOembedTest.php
- static/less/oembed.less
- themes/HumHub/css/theme.css
oEmbed update:
- Support of oEmbed for Twitter, Facebook and Instagram
- Redesigned of oEmbed settings pages
- Added dynamic endpoint parameters inputs
Issue: https://github.com/humhub/humhub/issues/5494
Screenshots:
> oEmbed for Facebook, Instagram and Twitter

- protected/humhub/modules/activity/Module.php
> Fix comment typo in activity/Module.php

- CHANGELOG.md
- protected/humhub/modules/friendship/tests/codeception/unit/FriendShipTest.php
- protected/humhub/modules/user/controllers/ProfileController.php
- protected/humhub/modules/user/models/Follow.php
Issue: https://github.com/humhub/humhub/issues/5517
> Don't send "Follows" notification on request friendship

- CHANGELOG.md
- protected/humhub/modules/comment/controllers/PermaController.php
Issue: https://github.com/humhub/team_tasks/issues/188
> Fix PermaLink controller error for content without container

- protected/humhub/modules/activity/tests/codeception/acceptance/ActivityStreamCest.php
- protected/humhub/modules/admin/tests/codeception/functional/PermissionCest.php
Issue: https://github.com/humhub/team_tasks/issues/194
> Fix marketplace tests

- protected/humhub/modules/admin/widgets/Modules.php
Issue: https://github.com/humhub/team_tasks/issues/195
> Fix modules list

- protected/humhub/modules/admin/widgets/Modules.php
Issue: https://github.com/humhub/team_tasks/issues/197
> Fix module searching

- CHANGELOG_DEV.md
- protected/humhub/modules/topic/widgets/TopicPicker.php
Issue: https://github.com/humhub/humhub/issues/5549
> Topic icon is missing after search

- CHANGELOG_DEV.md
- protected/humhub/modules/user/models/fieldtype/Date.php
- protected/humhub/modules/user/models/fieldtype/DateTime.php
> Formatted output for date fields

- CHANGELOG_DEV.md
- protected/humhub/widgets/views/modalConfirm.php
- protected/humhub/widgets/views/modalDialog.php
Issue: https://github.com/humhub/emcdda-documenta/issues/1
I found the bug in other modal windows that have a form, so I fixed it in the core.
> Fix Modal Close Button

- CHANGELOG_DEV.md
- protected/humhub/modules/stream/resources/js/humhub.stream.wall.js
- protected/humhub/widgets/CoreJsConfig.php
Issue: https://github.com/humhub/humhub/issues/5460
> Untranslatable string New Updates in Stream

- CHANGELOG_DEV.md
- protected/humhub/modules/user/views/account/editSettings.php
Issue: https://github.com/humhub/humhub/issues/5533
> Added UTC timezone to user account settings

- CHANGELOG_DEV.md
- protected/humhub/modules/comment/Module.php
Issue: https://github.com/humhub/team_tasks/issues/200
> Allow replying for sub comments

- CHANGELOG_DEV.md
- protected/humhub/widgets/views/topNavigation.php
- static/js/humhub/humhub.ui.topNavigation.js
> Mobile navigation: width detection problem

- .github/workflows/php-test.yml
- protected/humhub/compat/ArrayObject.php
- protected/humhub/components/ActiveRecord.php
- protected/humhub/components/SocialActivity.php
- protected/humhub/components/i18n/PhpMessageSource.php
- protected/humhub/modules/admin/views/logging/log_entries.php
- protected/humhub/modules/content/components/ContentContainerActiveRecord.php
- protected/humhub/modules/file/libs/FileHelper.php
- protected/humhub/modules/space/notifications/ApprovalRequest.php
- protected/humhub/modules/user/widgets/views/peopleCard.php
Issue: https://github.com/humhub/humhub/issues/5552
> Support PHP 8.1

- protected/humhub/modules/content/tests/codeception/unit/SpaceContentPermissionTest.php
Issue: https://github.com/humhub/team_tasks/issues/209
> Fix tests for php 7.3

- CHANGELOG_DEV.md
- protected/humhub/modules/search/engine/ZendLuceneSearch.php
Issue: https://github.com/humhub/humhub/issues/5575
> Add content topics to search

- CHANGELOG.md
- protected/humhub/modules/content/resources/js/humhub.ui.richtext.prosemirror.js
Issue: https://github.com/humhub/team_tasks/issues/206
> Backup RichText in sessionStorage

- CHANGELOG_DEV.md
- protected/humhub/modules/installer/views/setup/database.php
Issue: https://github.com/humhub/humhub/issues/5608
> Remove duplicated field "Hostname" on install

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/widgets/ModuleControls.php
Issue: https://github.com/humhub/humhub/issues/5610
> Show menu item "Add Licence Key" for purchased modules

- CHANGELOG_DEV.md
- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
Issue: https://github.com/humhub/humhub/issues/5612
> Fix RichText post process event pass data

- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
Issue: https://github.com/humhub/humhub/pull/5615#issuecomment-1082182981
> Fix missed data on RichText post process event

- CHANGELOG_DEV.md
- protected/humhub/widgets/PoweredBy.php
- protected/humhub/widgets/views/footerNavigation.php
- protected/humhub/widgets/views/footerNavigation_account_menu.php
- protected/humhub/widgets/views/footerNavigation_email.php
- protected/humhub/widgets/views/footerNavigation_login.php
- protected/humhub/widgets/views/footerNavigation_sidebar.php
> Footer View Optimization

- CHANGELOG_DEV.md
- protected/humhub/modules/content/components/ContentContainerModuleManager.php
- protected/humhub/tests/codeception/_support/BaseTester.php
Issue: https://github.com/humhub/news/issues/46#issuecomment-1093139305
> Fix enabling module on functional tests

- CHANGELOG_DEV.md
- protected/humhub/modules/web/tests/codeception/acceptance.suite.yml
- protected/humhub/modules/web/tests/codeception/acceptance/NonceCest.php
Issue: https://github.com/humhub/humhub/issues/5633
> Fix tests NonceCest

- CHANGELOG_DEV.md
- protected/humhub/modules/comment/models/Comment.php
Issue: https://github.com/humhub/team_tasks/issues/212
> Fix cached comments

- CHANGELOG.md
- composer.json
- composer.lock
> Added Laminas Bridge

- protected/humhub/components/OnlineModule.php
Issue: https://github.com/humhub/humhub/issues/5660
> Fix detection of official modules

- CHANGELOG_DEV.md
- protected/humhub/modules/content/models/Content.php
https://github.com/humhub/humhub/issues/5655
> Enh #5655: Possibility to archive and lock comments on global contents

- CHANGELOG.md
- protected/humhub/modules/space/widgets/HeaderCounterSet.php
- protected/humhub/modules/user/widgets/ProfileHeaderCounterSet.php
Issue: https://github.com/humhub/humhub/issues/5657
> Fix links of user counters in container headers

- CHANGELOG.md
- protected/humhub/modules/content/components/ContentAddonController.php
Issue: https://github.com/humhub/humhub/issues/5676
> Use 404 page for deleted content request

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/ApprovalController.php
- protected/humhub/modules/admin/models/forms/ApproveUserForm.php
- protected/humhub/modules/admin/views/approval/index.php
Issue: https://github.com/humhub/humhub/issues/5679
> Fix message on decline multiple users

- CHANGELOG.md
- protected/humhub/modules/ui/form/widgets/ColorPicker.php
Issue: https://github.com/humhub/team_tasks/issues/220
> Check value on colorpicker

- CHANGELOG.md
- protected/humhub/modules/user/models/Profile.php
Issue: https://github.com/humhub/humhub/issues/5691
> Fix attach file to profile markdown field

- CHANGELOG.md
- protected/humhub/components/SocialActivity.php
- protected/humhub/modules/comment/widgets/views/comments.php
Issue: https://github.com/humhub/humhub/issues/5693
> Scroll to comment on single view

- CHANGELOG_DEV.md
- protected/humhub/modules/user/widgets/PeopleDetails.php
https://github.com/humhub/humhub/issues/5695
> Enh #5695: Truncate long profile texts in People cards

- CHANGELOG.md
- protected/humhub/modules/notification/components/BaseNotification.php
- protected/humhub/modules/notification/components/NotificationManager.php
Issue: https://github.com/humhub/humhub/issues/5704
> Don't send notification for non-member of private space

- CHANGELOG.md
- static/js/humhub/humhub.ui.picker.js
Issue: https://github.com/humhub/humhub/issues/5709
> Fix input size for placeholder length in picker field

- CHANGELOG_DEV.md
- protected/humhub/modules/user/authclient/AuthClientHelpers.php
- protected/humhub/modules/user/views/auth/login.php
- protected/humhub/modules/user/views/auth/login_modal.php
- protected/humhub/modules/user/views/registration/index.php
Issue: https://github.com/humhub/humhub/issues/3593
> Allow SSO provider to register

- CHANGELOG.md
- protected/humhub/modules/admin/views/user/delete.php
- static/js/humhub/humhub.action.js
Issue: https://github.com/humhub/humhub/issues/5706
> Fix confirmation window for buttons

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/SettingController.php
- protected/humhub/modules/admin/views/setting/oembed_edit.php
Issue: https://github.com/humhub/humhub/issues/5716
> Fix saving of OEmbed provider endpoint URL

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/ModuleController.php
Issue: https://github.com/humhub-contrib/fcm-push/issues/12
> Fix uninstall module with not writable module path

- CHANGELOG.md
- protected/humhub/migrations/m220121_193617_oembed_setting_update.php
Issue: https://github.com/humhub/humhub/issues/5735
> Fix OEmbed providers migration

- CHANGELOG.md
- protected/humhub/components/access/ControllerAccess.php
Issue: https://github.com/humhub/humhub/issues/5740
> Fix logout action on force change password

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/ApprovalController.php
- protected/humhub/modules/admin/models/forms/ApproveUserForm.php
Issue; https://github.com/humhub/humhub/issues/5736
> Fix user approving/declining

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/models/forms/ApproveUserForm.php
- protected/humhub/modules/user/models/User.php
> Refc: Small user setupApproved Refactoring

- CHANGELOG.md
- static/js/humhub/humhub.ui.additions.js
Issue: https://github.com/humhub/enterprise-theme/issues/27
> Fix context menu position on the right window side

- protected/humhub/config/common.php
- protected/humhub/config/i18n.php
> Added CY Language

- CHANGELOG_DEV.md
- protected/humhub/modules/content/widgets/WallCreateContentForm.php
- protected/humhub/modules/content/widgets/views/wallCreateContentForm.php
- protected/humhub/modules/post/widgets/Form.php
Issue: https://github.com/humhub/team_tasks/issues/229#issuecomment-1161268687
> Fix rendering content form on external modules

- CHANGELOG_DEV.md
- protected/humhub/modules/ui/filter/widgets/DatePickerFilterInput.php
Issue: https://github.com/humhub/team_tasks/issues/230
> Display placeholder for date filter

- protected/humhub/modules/topic/controllers/ManageController.php
- protected/humhub/modules/topic/views/manage/overview.php
- protected/humhub/modules/user/models/forms/AccountSettings.php
- protected/humhub/modules/user/tests/codeception/acceptance/AccountCest.php
- protected/humhub/modules/user/views/account/_userSettingsLayout.php
- protected/humhub/modules/user/widgets/AccountMenu.php
Issue: https://github.com/humhub/wording/issues/66
> Wording for user account settings

- CHANGELOG.md
- protected/humhub/modules/comment/models/Comment.php
Issue: https://github.com/humhub/humhub/issues/5773
> Fix PHP 8 incompatibility with conversion false to array

- CHANGELOG.md
- protected/humhub/modules/marketplace/components/OnlineModuleManager.php
Issue: https://github.com/humhub/humhub/issues/5776
> Hide beta modules on disabled filter

- protected/humhub/modules/space/widgets/FollowButton.php
- protected/humhub/modules/space/widgets/MembershipButton.php
- protected/humhub/modules/user/widgets/UserFollowButton.php
Issue: https://github.com/humhub/team_tasks/issues/234
> Fix space name in membership confirmation
