- protected/modules_core/user/views/profile/about.php
The about field is a text field which allows line-breaks, but the output is condense. This allows those line-breaks to be used by passing the content through the Hhtml::enrichText() function. This will also allow links within the about content.
> Added enrichText() to About Field

- protected/models/UrlOembed.php
Some OEmbed providers may not work correctly if redirections are not
followed. One such example is Flickr.
> OEmbed: Follow redirects when fetching data

- themes/.gitignore
Added .gitignore to themes folder, as well. Similar to the protected/modules folder.
Makes developing own themes with own repositories a lot easier.
> .gitignore for themes folder

- protected/libs/SelfTest.php
introduced variable 'path'
[MINOR] removed redundant closing tag (following best practice)
>  [FIXED] SelfTest | Check Runtime Directory - undefined variable 'path' (#767)

- protected/components/Controller.php
Set the default language to english when the existing language cookie does not exist in the available languages.
> set default language cookie when does not exists in the available languages

- protected/commands/shell/EMailing/EMailing.php
This condition will be never satisfied. Assuming it is used for some testing.
> Cronjob will have empty activity result

- protected/modules_core/admin/controllers/UserprofileController.php
- protected/modules_core/user/models/ProfileField.php
- protected/modules_core/user/models/ProfileFieldType.php
Adding ability to create custom profile field types to use in modules using events
To add new field(s) simply attach this to events
array('class' => 'ProfileFieldType', 'event' => 'onInit', 'callback' => array('YourModule', 'AddCustomProfileFields'))
in module autostart.php file
then to add new custom profile field type you can use as following:
single type:
$event->sender->addFieldType('ProfileFieldTypeCompany', 'Company');
or
$event->sender->fieldTypes['ProfileFieldTypeCompany']='Company';
or you can attach array:
$event->sender->fieldTypes = array(
'ProfileFieldTypeCompany' => 'Company',
'ProfileFieldTypeEmpStatus' => 'Employment Status');
Where "ProfileFieldTypeCompany" is the class for the profile field type and "Company" is profile field type name.
> attach event onInit to ProfileFieldType Class

- protected/components/HClientScript.php
> Add backslashes before characters that need to be escaped

- protected/modules_core/user/models/ProfileFieldTypeText.php
- protected/modules_core/user/views/profile/about.php
HHtml::link only appends field value (email address) to the actual URL. With the (right) URI protocol the right link will be created.
> Email appended to the URL, not a mailto:-link

- protected/humhub/modules/admin/widgets/AdminMenu.php
Fixed - User profiles menu was not highlighted on admin dashboard user profiles page.
> Fix admin dashboard user profiles menu was not highlighting on this page

- protected/humhub/modules/content/Events.php
Because there are column status on 'user' and 'profile' table we should add table name 'user'  to column 'status' to  avoid error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'status' in where clause is ambiguous
> Add table name 'user' before column 'status'

- protected/humhub/modules/file/controllers/FileController.php
When I tried to use the "X-Sendfile" option with Nginx no images were displayed and I got a bunch of `substr() expects parameter 1 to be string, object given` in the logs.
Seems like we should use $filePath instead of $file here, I tried it and everything works great now :3
> Fix $filePath generation with Nginx when X-Sendfile is used

- protected/humhub/modules/post/controllers/PostController.php
- protected/humhub/modules/post/views/post/edit.php
- protected/humhub/widgets/views/richTextEditor.php
Fix issue #1515 Edit post with empty string
Now editing a Post with empty string renders the Yii model rule error correctly
(Tested on Chromium, Firefox, Opera, Edge and IE11)
> Fix issue #1515 Edit post with empty string

- protected/humhub/modules/comment/notifications/NewComment.php
Skip new comment notification if the user was mentioned in a comment.
> Fixed #1465 Double notifications for comments

- protected/humhub/modules/user/models/forms/Registration.php
fixed group registration default value to make automatic registration (e.g. via oauth) work directly without showing the registration form.
this default value is the same as set by the registration form.
fixes #1672
> fixed group registration default value

- protected/humhub/components/Application.php
- protected/humhub/components/behaviors/AccessControl.php
- protected/humhub/modules/admin/controllers/GroupController.php
- protected/humhub/modules/admin/controllers/IndexController.php
- protected/humhub/modules/admin/controllers/LoggingController.php
- protected/humhub/modules/admin/controllers/SettingController.php
- protected/humhub/modules/admin/controllers/SpaceController.php
- protected/humhub/modules/admin/controllers/UserController.php
- protected/humhub/modules/admin/controllers/UserProfileController.php
- protected/humhub/modules/directory/controllers/DirectoryController.php
- protected/humhub/modules/installer/controllers/ConfigController.php
- protected/humhub/modules/installer/controllers/IndexController.php
- protected/humhub/modules/installer/controllers/SetupController.php
- protected/humhub/modules/notification/controllers/EntryController.php
- protected/humhub/modules/space/controllers/CreateController.php
- protected/humhub/modules/space/controllers/MembershipController.php
- protected/humhub/modules/space/modules/manage/controllers/DefaultController.php
- protected/humhub/modules/tour/controllers/TourController.php
- protected/humhub/modules/user/controllers/AccountController.php
- protected/humhub/modules/user/controllers/AuthController.php
- protected/humhub/modules/user/controllers/RegistrationController.php
- make sure response instance is returned and nothing else is executed
after redirect
- use consistent syntax, avoid extra calls to Url helper, which are not
needed
- use controller redirect methods instead of
Yii::$app->response->redirect()
- use goHome() and goBack() shortcut methods where applicable
- fixed some excpetion imports and catch blocks I found while fixing the
above.
> cleanup overall usage of redirect()

- protected/config/common.php
aad2063e6ca3ca87d708956ad173fbc45fe9db1f has been fixed on master, applied it to v1.1-dev too.
> Apply aad2063e6ca3ca87d708956ad173fbc45fe9db1f to v1.1-dev

- protected/humhub/modules/search/engine/Search.php
does not make much sense otherwise. This ensures proper implementation of child classes.
> make unimplemented functions in search class abstract

- protected/humhub/components/ModuleManager.php
Fixed issue #1766  "No module-update possible if runtime-folder is on other volume"
> Suggest a fix for #1766

- themes/HumHub/css/theme.less
share widget has been removed in 0471bdc229dfe80e8b1ef03f3535037561513257 but style is still present in .less file in the theme.
Am I correct, that version 1.1 is now developed on master?
> Removed share-panel styles

- protected/humhub/modules/space/controllers/CreateController.php
this allows themes to create links for "create public space" and "create private space" like so:
create private space:
Url::to(['/space/create/create', 'visibility' => \humhub\modules\space\models\Space::VISIBILITY_NONE])
also save() includes validate so the duplicate call has been removed.
> allow pre-selected visibility for space creation

- js/panelMenu.js
to allow adjusted styling for collapsed panels, that is different from
expanded panels add a css class `panel-collapsed` when panel is collapsed.
Works when panel is collapsed manually as well as with saved collapse status from cookie.
> Small Enhancement: add css class to collapsed panels

- protected/humhub/modules/directory/widgets/views/spaceStats.php
fixed missing echo to display the rendered menu. Currently the collapse/expand menu does not show up on this sidebar panel.
> fixed bug in directory spaces sidebar

- protected/humhub/modules/space/widgets/views/spaceWall.php
use the image widget instead of displaying the image directly as it is done in other places.
> Show space acronym instaed of blank image in search results

- composer.json
More restrictive version constraints. Otherwise Humhub would break if Yii releases a 2.1 version. Same for extensions.
> Adjust Yii requirements in composer.json

- protected/humhub/modules/content/components/ActiveQueryContent.php
- protected/humhub/modules/file/widgets/FileUploadList.php
When using FileUploadList in a form with normal validation (not client
validation) all uploaded files are lost after a validation error occurs.
This fixes the widget to keep files in that case, i.e. when
$model->isNewRecord is true, it will take the file list from the post
field assigned to the record instead of from the database.
> Fixed file upload list to work with new models

- resources/user/profileHeaderImageUpload.js
Got an error:
> yii\base\ErrorException: imagecreatefromjpeg(/home/humhub/humhub/uploads/profile_image/banner/db6d3351-957f-49b9-8248-343de23a266a_org.jpg): failed to open stream: No such file or directory in /home/humhub/humhub/protected/humhub/libs/ProfileImage.php:134
That was because banner image size was too big. And after getting error-window, we could crop or delete our non-existing image.
> Fix user profile banner error.

- protected/humhub/modules/user/widgets/ProfileHeader.php
If we visit someones user profile, which is subscribed for other users and spaces, we will see the total number of subscribed entities (users and spaces). But If we open this window we'll see only followed users.
> fix following count

- resources/like/like.js
It can be an issue on slow connections.
When two requests are sent concurrently , `likeContainerDiv` is the same for both requests.
> Add var keyword for container in like.js

- protected/humhub/modules/comment/models/Comment.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/content/models/Wall.php
- protected/humhub/modules/content/models/WallEntry.php
- protected/humhub/modules/file/models/File.php
- protected/humhub/modules/like/models/Like.php
- protected/humhub/modules/post/models/Post.php
- protected/humhub/modules/space/models/Membership.php
- protected/humhub/modules/space/models/Space.php
- protected/humhub/modules/user/models/Group.php
- protected/humhub/modules/user/models/GroupAdmin.php
- protected/humhub/modules/user/models/GroupUser.php
- protected/humhub/modules/user/models/Invite.php
- protected/humhub/modules/user/models/Mentioning.php
- protected/humhub/modules/user/models/Password.php
- protected/humhub/modules/user/models/ProfileField.php
- protected/humhub/modules/user/models/ProfileFieldCategory.php
- protected/humhub/modules/user/models/User.php
- these do not receive user input and should not be changeable via forms.
I have not seen a concrete case where it was possible to exploit these
but it is still wrong to have them in there.
- Made sure the AR classes that have these fields extend
`humhub\components\ActiveRecord` so these fields are actually
mainained. For a lot of tables they are all null right now.
- Fixed a relation definition in ProfileField, which was a relict from
Yii 1.1.
> removed created/updated_at/by fields from model rules

- .htaccess.dist
- check if Apache module is available before processing rules
- prevent accessing app folders (like app, assets, js...)
- prevent using the /index.php in the URL
- removes the need of RewriteBase in case HumHub is installed on a sub-folder
> Better .htaccess file

- protected/humhub/modules/admin/Events.php
- protected/humhub/modules/admin/controllers/SettingController.php
- protected/humhub/modules/admin/models/forms/LogsSettingsForm.php
- protected/humhub/modules/admin/views/setting/logs.php
- protected/humhub/modules/admin/widgets/AdvancedSettingMenu.php
Reason behind this pull request is that after one year of running in production, the logs table got to aprox. 5GB.
It lets the admin set a maximum age for logs. Logs older than this max age will be deleted by the daily cron.
> Clear old logs

- protected/humhub/modules/space/widgets/SpacePickerField.php
vs
```php
// from Space
[['guid', 'name', 'url'], 'string', 'max' => 45, 'min' => 2],
```
> fix bug: Space picker required  3 char vs 2 min from Space

- protected/humhub/modules/search/engine/ZendLuceneSearch.php
I don't think there is a need to store the comments text blob in the index, tokenizing and indexing should be enough for searching.
So we can use the unStored Field factory function instead.
```php
/**
* Constructs a String-valued Field that is tokenized and indexed,
* but that is not stored in the index.
*
* @param string $name
* @param string $value
* @param string $encoding
* @return \ZendSearch\Lucene\Document\Field
*/
public static function unStored($name, $value, $encoding = 'UTF-8')
```
> [Search] Do not store comments with search index

- static/less/form.less
To avoid this (very) small issue of letters not being displayed entirely.
> Fix height of <select> under Firefox

- protected/humhub/migrations/m131203_110444_oembed.php
IMO 180 chars are enough for `url` column and it needs to allow for 4 bytes per character with `utf8mb4`, but `255*4 = 1020 bytes` wich is `>767 bytes` allowed by the database configuration.
> TryToFix #2357: length of primary key is too long

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/file/libs/ImageConverter.php
> Code of ImageConverter::allocateMemory uses different units of memory

- protected/humhub/modules/stream/actions/Stream.php
INIT called in the constructor.
```php
//from yii code of controller
$action = $this->createAction($id); // this INIT by default
$result = $action->runWithParams($params); // This you again call INIT. Why?
```
> remove reinitialize stream

- package.json
- Update dependencies
- Fix warnings on build
```
npm WARN humhub@ No repository field.
npm WARN humhub@ license should be a valid SPDX license expression
```
> Update dev grunt dependencies

- protected/humhub/views/layouts/main.php
Like `<title><strong>Search</strong></title>` that becomes `<title>Search</title>`
> Avoid HTML tags on Page Titles

- protected/humhub/libs/Helpers.php
- protected/humhub/modules/installer/controllers/SetupController.php
I setup a local humhub copy today on my vagrant box (ubuntu 16.04, php7, mysql5.7). The initial setup was a bit frustrating ;-) First setup crashed when task-module enabled (#1786) and later with (#1777).  
Both problems may solved if mysql is running with sql_mode traditional. I can change this on my vagrant box but not on a shared hosting. 
I ended up with adding a small helper function which changes the sql_mode for the current session. Then changed the db configuration to run this callback after a successfull mysql connection.
This is not a real solution for the issues but a neat workaround until all sql strict mode related issues are solved.
> workaround for #1777 and #1786

- static/resources/user/userpicker.js
'Add a user' is the correct form in English. Use of 'a' or 'an' are not determined by spelling, but pronunciation. Any word which sounds like it begins with a vowel (it may or may not actually begin with a vowel) will take 'an' and any word which begins with sound of a consonant will take 'a' as the preceding article.
> Changed 'Add an user' to 'Add a user'

- protected/humhub/modules/space/widgets/Menu.php
An ID must not be the empty string in view of this widget:
```html
<div id="<?= $this->context->id; ?>" class="panel panel-default">
```
[protected/humhub/widgets/views/leftNavigation.php:11](https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/views/leftNavigation.php#L11)
> Added missed id attribute to the widget

- CONTRIBUTING.md
Some minor fixes (Grammar and link fixes. Although I can't fix the `https://www.humhub.org/cla/github/sign` link missing in action...)
> Grammar & Link Fixes

- protected/humhub/modules/file/models/FileCompat.php
I've got a widget calling `File::getFilesOfObject($object)`. The method has been deprecated but a compatibility layer exists, `FileCompat`.
`humhub\modules\file\components\FileManager::getAll()` doesn't exist so I assume it's `humhub\modules\file\components\FileManager::findAll()` which should be called.
I've fixed a typo and a wrong exception call at the same time.
> Use FileManager::findAll() instead of non existing FileManager::getAll()

- protected/humhub/modules/user/models/User.php
If I create a custom field with the Select type, what was indexed was the index number (for exemple 1) instead of the value, so the choice wasn't searchable.
Fix by setting false to the raw parameter of getUserValue.
> Fix search index containing index for select fields

- composer.json
- Make sure to be compatible with newer versions of the plugin
> The "extra.asset-installer-paths" option is deprecated, use the
> "config.fxp-asset.installer-paths" option
- Improve performance of dependency resolution:
https://github.com/yiisoft/yii2-app-basic/commit/120d35506e411e575ee07aac900d7394b5b7386c#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
> improve composer-asset-plugin config

- protected/humhub/assets/JqueryWidgetAsset.php
````PHP Warning 'yii\base\ErrorException' with message 'file_get_contents(/static/assets/956b8bf1/ui/minified/widget.min.js): failed to open stream: No such file or directory'````
> Fix bug on grunt build-assets

- protected/humhub/modules/content/widgets/views/wallEntry.php
This PR adds a link on the 'ago' text to the permalink for a post. the point of this is to make it easier to refer back to conversations by link by providing a much quicker way to get that link (right click, copy link) instead of needing to click into a context menu, find the permalink entry, and then copy it from the dialog.
> add a link to the permalink from the ago text

- protected/humhub/widgets/BasePickerField.php
Using of Html::getAttributeValue() for parsing model attribute name resolve this issue.
> Fix #2851: getting model attribute value using Html::getAttributeValue()

- .codeclimate.yml
- ruleset.xml
@Felli told me that [] is preferred over array(). This pr adds a custom phpcs ruleset (based on PSR-1 & PSR-2) with Short-Array-Syntax preferred.
> Add custom phpcs configuration

- protected/humhub/modules/installer/controllers/SetupController.php
I would prefer a temporary connection object for checking connectivity instead of the global db object
> Use temporary connection object

- protected/humhub/modules/user/models/fieldtype/Birthday.php
In general all DateTime-Fields should follow the global and configurable dateInputFormat. For the Birthday-Field we should choose a default which protects the user from breaking functionality when changing global HumHub configuration.
Like described in #2848 the date format 'short' does not work for birthdates (18 = 2018 or 1918?).
> Use medium as date format

- protected/humhub/modules/user/components/PermissionManager.php
You can pass an array with permissions to PermissionManager->can(). But string[] is the wrong annotation.
> Fix phpdoc for PermissionManager->can

- .codeclimate.yml
> Exclude folder static/assets for codeclimate.

- protected/humhub/widgets/GridView.php
Yii 2.0.11 [see this commit](https://github.com/yiisoft/yii2/commit/7c1693479fbc8441d1565958942aeb7490872cb6) added Init-Event for Widgets.
I guess its required to remove the Init-Event from humhub\widgets\GridView because the event is trigger twice at the moment.
@acs-ferreira @githubjeka
> Yii 2.0.11 added Init-Event for Widget.

- static/js/humhub/humhub.client.js
- static/js/humhub/humhub.ui.modal.js
This PR allows us to automatically detect `dataType` based on server response type.
We have a custom fork of the humhub-module-calendar where we'd like to introduce some changes. These involve changing the server response-type from `html` to `json`. Unfortunately, we were forced us to modify all references to `modal.load(...)`, specifying that these were now `dataType = 'json'` requests.
This is sub-optimal, since the `dataType` is already specified in the server response. [`$.ajax`](http://api.jquery.com/jquery.ajax/) already does the right thing:
> If none is specified, jQuery will try to infer [dataType] based on the MIME type of the response
I've attached [our private patch](https://github.com/humhub/humhub/files/1626334/0001-cleanup-major-always-return-json-when-editing-calend.patch.g …
> Detect dataType from server response in AJAX requests

- .codeclimate.yml
Files inside codeception/_support/_generate could be ignored by codeclimate
> Exclude codeception generated

- static/js/humhub/humhub.ui.modal.js
now your listeners can process the server response, which was
previously hidden.
as described in https://github.com/humhub/humhub-modules-calendar/issues/105
> feature: supply 'submitted' listeners with server response

- protected/humhub/tests/config/common.php
Fixes for travis ci Exception 'ReflectionException' with message 'Class humhub\components\queue\driver\Instant does not exist' 
https://travis-ci.org/humhub/humhub/jobs/340865331#L544
Also, need to merge 1.3-dev with the lasted master branch to fix next others tests problems...
> Fix Exception 'ReflectionException'

- protected/humhub/modules/admin/models/UserSearch.php
Non-static method humhub\modules\admin\models\UserSearch::getStatusAttributes() should not be called statically in /opt/site/protected/humhub/modules/admin/views/user/list.php at line 38
> fix PHP Deprecated Warning

- protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
Fix tests like this https://travis-ci.org/humhub/humhub/jobs/342250980#L2106
> fix assertEqualsLastEmailSubject in tests

- protected/humhub/modules/content/components/ContentActiveRecord.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/content/models/ContentContainer.php
For more info see https://blog.jetbrains.com/phpstorm/2013/11/phpstorm-7-1-eap-133-51/
> A way to document mixins: now PhpStorm interprets @mixin regardless of PHP version just the same way it interprets “use trait” (see WI-1730 for details)
> autocomplete PHPStorm for behaviors for Content's models [skip ci]

- protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
- deprecated `Codeception\TestCase\Test` replaced to `Codeception\Test\Unit`
Note: now you can mark file as text `protected/vendor/codeception/codeception/shim.php`
- optimize imports for default fixture. All fixtures with fullpath you can see in
`HumHubDbTestCase::getDefaultFixtures()`
- fix for `HumHubDbTestCase::assertHasNotification()`.
Method `Notification::find($conditions)` hasn't any arguments. Replaced to
`Notification::find()->where($conditions)`
- To autocomplete IDE added new `HumHubDbTestCase:getYiiModule()`
  instead `HumHubDbTestCase::getModule('Yii2')`
- `HumHubDbTestCase::assertMailSent` becomes deprecated.
Use `HumHubDbTestCase::assertSentEmail` instead
> Enhancement HumHubDbTestCase

- .travis.yml
- protected/humhub/commands/MessageController.php
- protected/humhub/components/ModuleManager.php
- protected/humhub/libs/LogoImage.php
- protected/humhub/libs/ProfileImage.php
- protected/humhub/modules/admin/libs/OnlineModuleManager.php
- protected/humhub/modules/file/components/StorageManager.php
- protected/humhub/modules/search/engine/ZendLuceneSearch.php
ToDo : switch `unlink()` to `FileHelper::unlink` (globaly), when ready to upgrade to **Yii 2.0.14**
This will be done in a separate PR (in the v1.3-dev branch)
https://github.com/yiisoft/yii2/blob/313be2a5d75951e48273c6dae04eba2ab879fba9/framework/helpers/BaseFileHelper.php#L402
**=>The latest commit https://github.com/humhub/humhub/pull/3041/commits/b9e11ec6bc12a116bdd966f88eb66adf730aca02 should fix Travis tests.**
Reviews welcome @danielkesselberg @buddh4
> Switch from mkdir() to FileHelper::createDirectory

- protected/humhub/modules/admin/controllers/UserController.php
- protected/humhub/modules/live/Module.php
- protected/humhub/modules/search/engine/ZendLuceneSearch.php
- protected/humhub/modules/space/Events.php
- protected/humhub/modules/space/models/Membership.php
- protected/humhub/modules/tour/controllers/TourController.php
- protected/humhub/modules/user/controllers/AccountController.php
- protected/humhub/modules/user/models/User.php
when limiting a search query to spaces, only the space IDs are necessary.
When a user is member in many spaces, loading all the spaces objects
consumes a lot of memory and in extreme cases can cause Humhub to crash
with out of memory error.
This problem is fixed by adding a new method
`Membership::GetUserSpaceIds()` a new private method is added to ensure
the query is the same for `GetUserSpaceIds()` and `GetUserSpaces()`.
> improve performance for search (avoid memory issues)

- composer.json
See http://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes/
> Upgrading Yii addresses the SQL injection but doesn't make findOne() and findAll() safe in general. Check all usages of findOne() and findAll() in your application. Also note, that where() and filterWhere() never escape column names, so if you need to pass a variable as a column name, make sure it is safe.
> Apply Yii security patch

- protected/humhub/modules/tour/widgets/views/guide_spaces.php
This PR removes the `debugger;` to prevent the starting of the dev tools then viewing the tour.
Closes #3182
> [BUGFIX] remove `debugger;` in javascript from spaces tour

- .codeclimate.yml
CodeClimate does not pickup our custom phpcs standard. Caused by bug in outdated phpcodesniffer.
> CodeClimate does not pickup phpcs.xml.dist

- protected/humhub/modules/user/tests/codeception/unit/UserPickerFieldTest.php
- protected/humhub/modules/user/widgets/UserPickerField.php
My code
```php
<?= $form->field($model, 'attribute')
->widget(\humhub\modules\user\widgets\UserPickerField::class); ?>
```
Before 1.3 , input value is `$model->attribute`
After 1.3 input value always null. Bug in https://github.com/humhub/humhub/commit/af85d33f5faf70c77f7f808d5ee89d2478dcd077#diff-b7487eb0708eec7dc191a72a89c1c131
> BC break for itemKey of UserPickerField

- protected/humhub/docs/guide/admin/installation-configuration.md
@mk314 suggested https://github.com/humhub/humhub/issues/3308#issuecomment-423819238 that `isolated` should be `isolate`. 
Looks correct for me when i look at yii2-queue: https://github.com/yiisoft/yii2-queue/blob/d291834dc3df44dd2f17b4222a3172102eb16a4a/src/cli/Command.php#L48-L51
> Change isolated to isolate

- protected/humhub/modules/installer/commands/InstallController.php
As I am using this code inside my docker container (https://github.com/mriedmann/humhub-docker) for quite a time now and it is working really well, I thought contributing it upstream would be a good thing to do. I wanted to provide the possibility to set all needed setup-information by using environment-variables and implementing this by patching the existing CLI controller was the easiest way I could think of. The original behavior is preserved, so I would assume …
> Enh: Added advanced options to installer CLI

- protected/humhub/modules/ui/view/components/View.php
Additionally, maybe this line can be removed also?
https://github.com/humhub/humhub/blob/185a21ef507c259c3e4277c36c86d466355a8b33/protected/humhub/modules/installer/views/layouts/main.php#L20
> Avoid CSRF cache by registering tags dynamically

- protected/humhub/components/mail/Mailer.php
- protected/humhub/components/mail/Message.php
Some certificate providers may have a long list of intermediate certificates that must be included in the signing process. Without these certificates, some email clients may fail to verify the signature of the email.
The two additional Module params relating to this would be:
- signingExtraCertsPath: Path to PEM file containing chain of Certificates 
- signingOptions: Bitwise operator options for openssl_pkcs7_sign
Issue: #3649
Based on PR: #3651
> Expose signingOptions and extraCerts params

- protected/humhub/modules/friendship/widgets/views/friendsPanel.php
The profile Friends panel was using the same div id as the Followers panel, causing it to collapse at the same time as the Followers panel, and preventing it from collapsing from its own widget panel menu. Fix this by correcting the div id to match the panel widget configuration.
> Fix profile Friends panel collapsibility

- protected/humhub/modules/content/components/behaviors/CompatModuleManager.php
- protected/humhub/modules/space/views/create/modules.php
_On space creation, only display those modules which:_
- is enabled and can be disabled
OR
- is disabled and can be enabled
Fixes #2456
> Fix #2456: Only display list of relevant modules on space creation

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/notification/controllers/ListController.php
> Fix #4031: Notifications with non existing base model breaks notifications

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/stream/resources/js/humhub.stream.StreamEntry.js
> Fix #4086: Maximum call stack size exceeded thrown on ActivityStreamEntry.remove

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/content/widgets/WallEntry.php
Implements #4061: Improved post context menu order:
- Edit
- Permalink
- Delete
> Enh #4061: Improved post context menu order

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/user/assets/PermissionGridModuleFilterAsset.php
- protected/humhub/modules/user/resources/js/humhub.user.PermissionGridModuleFilter.js
- protected/humhub/modules/user/widgets/PermissionGridEditor.php
- Fix #4034: Premission filter pagination shown without reason and broken
- Fix #4012: Permission filter dropdown shows module id instead of module name
> - Fix #4034 and #4012 permission filter view

- protected/humhub/docs/CHANGELOG_DEV.md
- static/less/form.less
Fixes https://github.com/humhub/humhub/issues/4182
> Fix #4182: Native edge password reveal icons interferes with custom one

- protected/humhub/widgets/Modal.php
- protected/humhub/widgets/ModalDialog.php
- static/js/humhub/humhub.ui.modal.js
This change will by default prevent modals from beeing closed by clicking on the modal backdrop or by escape. This will prevent accidental loss of form or other data.
One question is should we allow closing by escape by default. I think it would be better to block escape, since a modal
may include features as for example special richtext features which may suggest pressing escape will only affect this feature but eventually will close the modal. A modal is always closable by `x` button and should ideally inclue a `Cancel` button instead.
After this PR, closable Modals can be created by:
```php
<?php ModalDialog::begin(['closable' => false]) ?>
...
<?php ModalDialog::end() ?>
```
**Does this PR introduce a breaking …
> Enh: Disable close modal by click on backdrop or escape by default.

- protected/humhub/compat/HForm.php
- protected/humhub/docs/CHANGELOG.md
Fixes https://github.com/humhub/humhub/issues/4140
> Fix #4140: Profile field hint is double encoded

- protected/humhub/components/Controller.php
- protected/humhub/modules/activity/controllers/LinkController.php
- protected/humhub/modules/installer/controllers/ConfigController.php
- protected/humhub/modules/installer/controllers/IndexController.php
- protected/humhub/modules/installer/controllers/SetupController.php
- protected/humhub/modules/user/controllers/AuthController.php
- protected/humhub/modules/user/controllers/PasswordRecoveryController.php
- protected/humhub/modules/user/controllers/RegistrationController.php
- protected/humhub/modules/web/pwa/controllers/ManifestController.php
- protected/humhub/modules/web/pwa/controllers/OfflineController.php
- protected/humhub/modules/web/pwa/controllers/ServiceWorkerController.php
Implements: https://github.com/humhub/humhub/issues/3990
Controllers requiring guest access even though guest mode is not active need to explicitly configure:
```
public $access = ControllerAccess::class;
```
> Enh #3990: Use StrictAccess by default in humhub\components\Controller

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/space/models/Space.php
Fix: `Space::canAccessPrivateContent()` throws error for guest user if `globalAdminCanAccessPrivateContent` setting is true-
> Fix: `Space::canAccessPrivateContent()` may throws error for guest user

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/content/components/ContentActiveRecord.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/content/models/ContentContainer.php
- protected/humhub/modules/content/models/ContentContainerModuleState.php
- protected/humhub/modules/content/models/ContentType.php
- protected/humhub/modules/content/tests/codeception/_support/ContentModelTest.php
- protected/humhub/modules/content/tests/codeception/unit/TestContent.php
- protected/humhub/modules/content/tests/codeception/unit/models/ContentContainerTest.php
- protected/humhub/modules/content/tests/codeception/unit/models/ContentTest.php
- protected/humhub/modules/content/tests/codeception/unit/models/ContentTypeTest.php
- protected/humhub/modules/content/tests/codeception/unit/models/ContentVisibilityTest.php
Removed `humhub\modules\content\components\ContentActiveRecord:initContent`. This property was introduced due to https://github.com/humhub/humhub/issues/3110 and is not required anymore.
This PR also adds some additional content related unit tests as well as minor doc enhancements.
> Chg: Removed unnecessary ContentActiveRecord:initContent

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/web/Events.php
- protected/humhub/modules/web/config.php
By default the browser does not send any credential information with the `manifest.json` request. Which will create a
guest session if CSP with script nonce is active. 
- Related to https://github.com/humhub/humhub/issues/4181
This PR adds some additional checks to prevent CSP creation in those cases:
- `Yii::$app->response->format === 'html'` - should block other non html metadata requests
- `!(Yii::$app->controller instanceof ManifestController)` - blocks manifest.json request
- ` !(Yii::$app->controller instanceof OfflineController)`  - blocks offline page request
- `!(Yii::$app->controller instanceof ServiceWorkerController)` - blocks service worker js request 
**Does this PR introduce a breaking change?** (check …
> Fix: Metadata request creates new session if CSP nonce is enabled

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/web/security/helpers/Security.php
Fix: `humhub\modules\web\security\helpers\Security:setNonce()` does not remove nonce session value if nonce is null.
> Fix: Security:setNonce() does not remove nonce session value if nonce is null

- protected/humhub/modules/content/models/ContentTag.php
Adds second order by name sorting for ContentTags
Related to https://github.com/humhub/humhub/issues/4196
> Enh: Added second ContentTag default order by name

- static/js/humhub/humhub.action.js
This pr prevents an error being thrown when using `humhub.action.Component.instance()` with an invalid selector.
> Fix: Component.instance() throws error for invalid selectors

- protected/humhub/docs/CHANGELOG_DEV.md
- protected/humhub/modules/admin/views/user-profile/editField.php
- protected/humhub/modules/user/components/ActiveQueryUser.php
- protected/humhub/modules/user/models/ProfileField.php
- protected/humhub/modules/user/models/fieldtype/BaseType.php
- protected/humhub/modules/user/models/fieldtype/BaseTypeVirtual.php
Fix #4274: Force profile field attribute values of BaseTypeVirtual fields
- Forces specific field attribute values for BaseTypeVirtual
- Adds possibility to hide form fields per profile type
- Adds additional check to avoid #4274
> Fix #4274: Force profile field attribute values of BaseTypeVirtual fields

- protected/humhub/modules/admin/widgets/IncompleteSetupWarning.php
…\base\ErrorException: Undefined index: jobCount in /var/www/html/protected/humhub/modules/admin/widgets/IncompleteSetupWarning.php:100'
In the file:
> protected\humhub\modules\admin\widgets\IncompleteSetupWarning.php
This 100th line of code:
`if (is_array($counter) && $counter['jobCount'] > 0) {`
Replaced with:
`if (is_array($counter) && array_key_exists('jobCount', $counter) && $counter['jobCount'] > 0) {`
Because of the warning:
> Undefined index: jobCount in …
> checking if array_key_exists('jobCount', $counter) to avoid Undefined index: jobCount in

- composer.json
- composer.lock
- protected/humhub/docs/CHANGELOG.md
---
It seems that HumHub and the official marketplace modules are not affected by the Yii2 security bug CVE-2020-15148. 
Although we should provide an update for individual modules here. The Yii2 update does not sound critical.
```
Seems you have upgraded Yii Framework from version 2.0.36 to 2.0.38.
Please check the upgrade notes for possible incompatible changes
and adjust your application code accordingly.
Upgrade from Yii 2.0.37
-----------------------
* Resolving DI references inside of arrays in dependencies was made optional and turned off by default. In order
to turn it on, set `resolveArrays` of container instance to `true`.
Upgrade from Yii 2.0.36 …
```
> Upgrade to Yii 2.0.38

- protected/humhub/modules/comment/models/Comment.php
- protected/humhub/modules/comment/tests/codeception/unit/CommentEditTest.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/content/tests/codeception/unit/ContentEditTest.php
- protected/humhub/modules/content/tests/codeception/unit/ContentTest.php
Prior to this PR it was not obvious if a content entry has been edited or not. Its tempting to only check the `updated_at`
field, but this is also set on creation. The actual and rather complex check used in some views is:
```
$content->created_at !== $content->updated_at && !empty($content->updated_at) && is_string($content->updated_at);
```
which can now be replaced with:
```
$model->content->isEdited()
```
> Enh: Implementation of Content::isEdited()

- protected/humhub/modules/ui/icon/widgets/Icon.php
- protected/humhub/widgets/BootstrapComponent.php
Removed deprecated views:
- protected/humhub/modules/space/modules/manage/views/image/crop.php
- protected/humhub/modules/space/modules/manage/views/image/cropBanner.php 
- protected/humhub/modules/user/views/image/crop.php
Fixes Warning:
- Throwing exceptions from __toString() was not allowed prior to PHP 7.4
> Removed unused files + minor php compatibility fixes

- protected/humhub/modules/content/tests/codeception/unit/ContentContainerStreamTest.php
- protected/humhub/modules/dashboard/tests/codeception/unit/DashboardStreamTest.php
- protected/humhub/modules/notification/tests/codeception/unit/LoadNotificationTest.php
- Function `create_function()` is deprecated since PHP 7.2; Use an anonymous function instead
> Fixed usage of deprecated create_function in unit tests

- protected/humhub/libs/UrlOembedHttpClient.php
------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------
29 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4
------------------------------------------------------------------------------------------------
> Fix: removed deprecated safe_mode ini check in UrlOembedHttpClient

- CHANGELOG_DEV.md
- protected/humhub/modules/ui/view/helpers/LessHelper.php
Fixes https://github.com/humhub/humhub/issues/4456
> Fixed #4456 PHP8 deprecated warning for LessHelper::updateVariables()

- protected/humhub/modules/content/widgets/stream/views/wallStreamEntryHeader.php
This PR adds a middot between stream entry date and stream entry icons.
> Added middot between stream entry date and stream entry icons

- protected/humhub/modules/post/resources/js/humhub.post.js
Only apply `short-text-post` class on single paragraph without new lines.
> Fix: Ignore multi-line paragraphs when applying short-text-post class

- protected/humhub/modules/space/views/space/about.php
- protected/humhub/widgets/CoreJsConfig.php
Related to https://github.com/humhub/humhub/issues/4483#issuecomment-707829189
- Increases the read-more text limit in the about section from 380px to 600px.
- Changes the defaul text of read-more feature from "Read full post..." to "Read more"
> Increases about section text read-more text limit

- CHANGELOG_DEV.md
- protected/humhub/modules/notification/controllers/ListController.php
Fixes: https://github.com/humhub/humhub/issues/4493
> Fix #4493: Removed legacy ControllerAccess in notification ListController

- CHANGELOG_DEV.md
- protected/humhub/modules/like/permissions/CanLike.php
Shouldn't allow users to select `Not registered users` for likes as guests aren't allowed to like posts by default so this would confuse the user as well as contradict the CanLike permission. (Introduced in #4339)
> Fix: Allowing guest like permission

- protected/humhub/docs/CHANGELOG.md
- protected/humhub/modules/content/components/ContentContainerModule.php
- protected/humhub/modules/content/components/ContentContainerModuleManager.php
- protected/humhub/modules/content/components/behaviors/CompatModuleManager.php
- protected/humhub/modules/space/controllers/CreateController.php
- protected/humhub/modules/space/views/create/modules.php
…oller.php
This issue happened then all modules **set as default** and the system try to show a list of modules **to choose what to enable**, but the list is **empty** and it shows up an empty modal window.
The window is empty because in the view system check every module for **canEnableModule()**, but we can not enable the module which set as default.
To resolve the issue I added a check for modules not set as default. If all modules set as default we did not …
> Empty "Add Modules" modal on space creation #4494

- CHANGELOG_DEV.md
- protected/humhub/modules/file/resources/js/humhub.file.js
- protected/humhub/modules/file/widgets/FilePreview.php
File preview widget is not visible when rendered in the background e.g. a hidden tab. 
This issue was introduced in 1.7.
> Fix: File preview not visible if initialized in background

- CHANGELOG_DEV.md
- protected/humhub/modules/admin/controllers/UserController.php
- protected/humhub/modules/admin/models/forms/PasswordEditForm.php
Issue: https://github.com/humhub/humhub/issues/3414
> Allow to change user passwords by admin

- protected/humhub/modules/content/views/container-image/cropModal.php
Fixes image overflow in crop modal on mobile. The solution is not ideal since the image is just cut, but better than the current sate in which the image just overflows the modal. In order to implement a solution in which the image is not cut we probably need a more complex js based solution similar to https://stackoverflow.com/questions/13648162/using-jcrop-on-responsive-images.
> Fixes image crop modal overflow on mobile

- CHANGELOG.md
- static/less/file.less
- static/less/stream.less
Fixes an issue in which the jplayer overflows the stream entry on mobile.
> Fix: Jplayer overflow on mobile stream

- CHANGELOG.md
- protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php
This PR fixes an Issue in which multiple richtext files without title are not parsed correctly and therefore can not be attached to the model.
Related issue: https://github.com/humhub/humhub-modules-custom-pages/issues/155#issuecomment-734504073
> Fixes richtext attachment of multiple files without title

- .codeclimate.yml
- CHANGELOG.md
- protected/humhub/modules/content/tests/codeception/unit/RichtextExtensionTest.php
- protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php
Fixes an issue in which the richtext extension regex does not fully scan the title in case the title contains a `)`.
> Fix: Richtext extension scan cuts title if title contains `)`

- protected/humhub/modules/admin/tests/codeception/functional/ApprovalCest.php
- protected/humhub/modules/content/tests/codeception/unit/ContentCreatedTest.php
- protected/humhub/modules/user/tests/codeception/unit/models/UserFilterTest.php
- protected/humhub/modules/user/tests/codeception/unit/models/UserPickerTest.php
New user fixture was added here https://github.com/humhub/humhub/pull/4693/commits/aeb12517e9c2747d9d5856d2aa42a588bbfc4027#diff-93a0674f91dd888bcb0f290b085e786d90c2dc8e1690ea33216408e5d27f46ccR29 for issue https://github.com/humhub/tasks/issues/48#issuecomment-752645923
> Fix tests after new added user fixture “AdminNotMember”

- CHANGELOG_DEV.md
- protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php
Fixes an issue in which richtext extension events are ignored when using the deprecated `maxLength` option of the richtext.
Fixes https://github.com/humhub/humhub-modules-wiki/issues/160
> Fix issue when using deprecated richtext maxLength

- CHANGELOG_DEV.md
- protected/humhub/components/access/ControllerAccess.php
- protected/humhub/modules/admin/widgets/views/maintenanceModeWarning.php
Issue: https://community.humhub.com/s/announcements/?contentId=236860# comment started with "On the user side there are some issues too. (The user default idle time is set to 600 in this instance.) ...", point:
> 1. A permanent logged in user is still logged in after opening the site, which is already in maintenance mode.
> (To be clear, this browser was closed as the m mode was set and browser and site was opend afterwards.)
+ Issue: https://github.com/humhub/humhub/issues/4910
> Auto logout user on maintenance mode

- CHANGELOG_DEV.md
- protected/humhub/modules/comment/resources/js/humhub.comment.js
- Fixes https://github.com/humhub/humhub/issues/4918
> Fix #4918: Comment richtext gets focused when closing comment section

- CHANGELOG.md
- protected/humhub/modules/file/migrations/m210310_103412_fix_hash.php
Fix size of the column `file.hash_sha1` because php function `sha1_file()` returns 40 chars string.
> Fix file hash column length

- protected/humhub/modules/space/Module.php
- protected/humhub/modules/space/models/forms/InviteForm.php
- protected/humhub/modules/space/widgets/InviteModal.php
- protected/humhub/modules/space/widgets/views/inviteModal.php
It would be great to **allow users to add other users to space without an invitation**, but giving them the "ManageUsers" admin permission (where it is part of at the moment) is a huge deal. This would allow them to also edit and delete users, for example. I therefore **added a specific permission "Add Users to Spaces" as a sub-permission to it for just that purpose**. If you have "Manage Users" as permission, this will not introduce any changes. If you don't have "Manage Users" permission, this will neither introduce any changes, since the default for "Add Users to Spaces" is _deny_. So there is no harm done by giving the admin more freedom.
---
If yes, please describe the impact and …
> Implemented admin-permission to add users to spaces directly

- CHANGELOG.md
- protected/humhub/modules/space/modules/manage/controllers/SecurityController.php
- protected/humhub/modules/space/modules/manage/views/security/index.php
Don't show the "Private (Invisible)" space visibility option in the
space security settings for users who cannot create private spaces.
Move the logic for assembling the visibility options from the view to
the controller.
This fixes the problem where “Private (Invisible)” was showing as a space visibility option within the space security settings to users who don’t have permission to create private spaces. These users received an error if they tried to choose the …
> Fix space visibility options showing for users without permission

- protected/humhub/modules/space/modules/manage/widgets/MemberMenu.php
As change owner page is accessible to system admin, the tab menu should be shown to.
It will be useful for sys admin to to avoid the need to go through the administration page of the spaces to access to this space owner page.
Perhaps there is a nicer way to replace `($this->space->isSpaceOwner() || (!Yii::$app->user->isGuest && Yii::$app->user->identity->isSystemAdmin()))` but I didn't find.
> Space: Show "Owner" Tab also for SystemAdmins

- protected/humhub/modules/user/components/PeopleQuery.php
Issue: https://github.com/humhub/team_tasks/issues/123#issuecomment-856961594 - "If a user group is used as a filter, there is an internal error.".
> Fix people sorting by "Default" when filter "Group" is selected

- protected/humhub/modules/user/views/profile/about.php
RichText::output produces div. Syntactically, a div inside a p is invalid in HTML: https://www.w3.org/TR/html401/struct/text.html#h-9.3.1
> Fix incorrect <div> nesting in <p>

- protected/humhub/modules/file/models/File.php
The bug "Maximum function nesting level" was detected on deleting a file working on the task https://github.com/humhub/cfiles/issues/121#issuecomment-928106295.
We should exclude a deleting of the current File there in order to avoid infinite loop of the `$file->delete()`.
> Fix deleting of version files

- protected/humhub/modules/content/models/ContentContainerTagRelation.php
The bug detected during work on this https://github.com/humhub/humhub/issues/564#issuecomment-929015264.
The field `contentcontainer.tags_cached` was not cleared when all tags are deleted from container.
> Clear cached container tags

- CHANGELOG_DEV.md
- protected/humhub/modules/file/models/File.php
Request: https://github.com/humhub/spd-otf/issues/2#issuecomment-957745957:
> **Please note** currently impossible to remove the attached image from the Topic Forum because the `Upload` was developed to works only with Content Active Records, but the `TopicForum` is a simple `ActiveRecord`. It would be good to modify the core `\humhub\modules\file\models\File->canDelete()`(https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/models/File.php#L197-L221) to allow to check `$object->canEdit($userId);` even the `$object` is a simple `ActiveRecord`.
> Allow to detach file from simple ActiveRecord

- protected/humhub/modules/space/widgets/views/membershipButton.php
Currently the membership buttons displays the owner title for members and member title for owners.
> Fix mixed up title for membership button

- CHANGELOG_DEV.md
- protected/humhub/modules/user/resources/js/humhub.user.login.js
When resolving this [issue](https://github.com/humhub/team_tasks/issues/62) I faced a problem, that when the "remember me" checkbox is checked, the script breaks pretty url `/user/auth/microsoft`, that is required for [auth-microsoft module](https://github.com/humhub-contrib/auth-microsoft)
> Microsoft Auth Remember me checkbox fix

- CHANGELOG.md
- protected/humhub/components/rendering/DefaultViewPathRenderer.php
`null` value for the function `file_exists` is deprecated on PHP 8.1
> Fix deprecated null value for `file_exists()` on PHP 8.1

- protected/humhub/libs/DbDateValidator.php
> Fix deprecated null for DateTime in PHP 8.1

- CHANGELOG-DEV.md
- protected/humhub/modules/admin/models/forms/LogFilterForm.php
Issue: https://github.com/humhub/humhub/issues/5850
> Display all levels by default on info logging page

- .github/workflows/php-test.yml
Description
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows.
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes.
Here is an example of the permissions in one of the workflow runs:
https://github.com/humhub/humhub/runs/8059673755?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflow:
- php-test.yml
The following workflow file already has the least privileged token permission set:
- support.yml
Motivation and Context
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- GitHub recommends defining …
> ci: add minimum GitHub token permissions for workflows

- protected/humhub/modules/user/views/registration/byLink.php
About https://github.com/humhub/humhub/issues/5699
The bug was:
1. get an invitation link from a space
2. go to this URL
3. If the Humhub instance gives the possibility to connect with an SSO, a button was shown
4. If we click on this button, the account is created, but the email was not verified and the user was not added to the space where he was invited
This fix removes the SSO button. Now:
1. get an invitation link from a space
2. go to this URL
3. you need to enter your email
4. An email is sent, you need to click on the button to confirm that your email is valid
5. you can now register with the SSO
6. you are added to the space
If yes, please describe the …
> Fix registration by link with SSO

- CHANGELOG.md
- protected/humhub/modules/user/models/fieldtype/Date.php
- protected/humhub/modules/user/models/fieldtype/DateTime.php
For PHP 8.1+: Fix the "About" profile page when fields Date or Dateime is not filled.
> Fix Date and Datetime profile field type with null values on PHP 8.1+

- CHANGELOG.md
- protected/humhub/components/ModuleManager.php
https://docs.humhub.org/docs/admin/requirements lists php 7.4 as minimum requirement. Hence, the array properties should actually be arrays.
This caused log targets to be disabled due to the `ModuleManager::getModules()` throwing an error when `ModuleManager::$modules` would be null.
- Bugfix
- No, as there is no class that extends `ModuleManager`. Otherwise, the type `array` could be left away but just initializing the `$modules = []`
Do you want me to create an issue for this and adding a changelog entry?
> Fix error when no modules set

- CHANGELOG.md
- protected/humhub/modules/content/components/ContentActiveRecord.php
- protected/humhub/modules/content/models/Content.php
Issue: https://github.com/humhub/humhub-internal/issues/31#issuecomment-1519610001:
> I see we already have the event `Content::EVENT_STATE_CHANGED` here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/Content.php#L248-L252, but I think the condition for calling of this event is not correct, because we should call it on every changing of a state and not only when a record is published as it works now.
https://github.com/humhub/humhub-internal/issues/31#issuecomment-1520049130:
> Then let go with the method `afterStateChange(int $newState, int $previousState): void` and keep the existing `Content::EVENT_STATE_CHANGED` to …
> Fix event trigger for `Content::EVENT_STATE_CHANGED`; Implement new `ContentActiveRecord->afterStateChange()`

- CHANGELOG-DEV.md
- protected/humhub/modules/user/models/Group.php
- protected/humhub/modules/user/tests/codeception/unit/models/GroupTest.php
- Bugfix
- Refactor
**Does this PR introduce a breaking change?**
- Yes, potentially for external module developers who extended `\humhub\modules\user\models\Group`
- No for this repository
- Fix #6192 
- New/updated tests are included
- Changelog was modified
> Fix #6192: Where Group::getAdminGroupId() would sometimes return int, sometimes string

- protected/humhub/modules/user/models/forms/AccountRecoverPassword.php
Issue: https://github.com/humhub/wording/issues/128
> Update wording of password recovery

- CHANGELOG-DEV.md
- static/js/humhub/humhub.log.js
Fix #6423 `log.fata` in frontend logging is redirected to `log.fatal`, which did not work.
- Bugfix
- No
- It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- All tests are passing
- No new/updated tests are included
- Changelog was modified
> Fix log.fata in frontend logging

- CHANGELOG-DEV.md
- protected/humhub/libs/Html.php
Detected during checking tests here https://github.com/humhub/team_tasks/issues/284#issuecomment-1627735453.
Missed input for add new task list on creating a Task in the module "Tasks":
Expected input:
> Fix default dropdown select2 options

- CHANGELOG-DEV.md
- index-test.php
- protected/humhub/components/Request.php
- Bugfix
- No
- No new/updated tests are included
During tests, the virtual files `/manifest.json,` `/sw.js`, & `/offline.pwa.html` from the module `web` where not served. This patch allows the test web server to serve them, too.
> Fix: Test server support to serve `web` module's `/manifest.json`, `/sw.js`, & `/offline.pwa.html`

- CHANGELOG-DEV.md
- MIGRATE-DEV.md
- protected/humhub/interfaces/ArchiveableInterface.php
- protected/humhub/interfaces/DeletableInterface.php
- protected/humhub/interfaces/EditableInterface.php
- protected/humhub/interfaces/ReadableInterface.php
- protected/humhub/interfaces/ViewableInterface.php
- protected/humhub/modules/comment/models/Comment.php
- protected/humhub/modules/content/components/ContentAddonActiveRecord.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/file/models/File.php
- Feature
- Refactor
The PR is an attempt to standardize a number of functions to get information about a specific record as [been suggested in the code](https://github.com/metaworx/humhub/blob/1b0700deedde89b5dd3faed4920830f796834c2e/protected/humhub/modules/content/models/Content.php#L898).
- `canArchive($user = null): bool`
- `canEdit($user = null): bool`
- `canDelete($user = null): bool`
- `canRead($user = null): bool`
- `canView($user = null): bool`
A prerequisite for PR #6408
- Potentially. Not in the core. But yes, modules which derive from affected classes and do implement one of the above methods, need to adhere to the new interface
- …
> [Enh] Introduce Archiveable, Deletable, Editable, Readable, & Viewable Interfaces

- CHANGELOG-DEV.md
- protected/humhub/modules/live/tests/codeception/unit/LegitimationTest.php
- protected/humhub/modules/space/behaviors/SpaceModelMembership.php
- protected/humhub/modules/space/models/Membership.php
- protected/humhub/modules/space/models/forms/InviteForm.php
- protected/humhub/modules/space/modules/manage/controllers/MemberController.php
- protected/humhub/modules/space/tests/codeception/unit/InviteTest.php
- protected/humhub/modules/space/tests/codeception/unit/MembershipTest.php
- Bugfix for regression introduced in [Performance Improvements](https://github.com/humhub/humhub/commit/9fabc0e2d40b580527a57eb32f3a4a29903ca3f2#diff-784788c31ac7b8ee4174e073efbfc818d7791d600260533363a35a5548670685R233-R235)  (#6375)
Requesting space membership does work, but the buttons on the space list are not updated. Therefore, the issue only happens in case the space membership is requested from the spaces list
http://humhub.local/index.php?r=space%2Fspaces
- No
- All tests are passing -> **This regression is not covered by a test**
- **to be done:** testing the request to …
> Fix regression with Membership cache

- CHANGELOG-DEV.md
- protected/humhub/modules/admin/resources/js/humhub.admin.js
- static/js/humhub/humhub.client.js
- static/js/humhub/humhub.ui.modal.js
Issue: https://github.com/humhub/humhub/issues/6492
> Fix module form "Set as default"

- CHANGELOG-DEV.md
- protected/humhub/modules/space/notifications/ApprovalRequest.php
- Bugfix
**Does this PR introduce a breaking change?**
- No
The produced URL was:
```
index.php?r=space%2Fspace&cguid=5396d499-20d6-4233-800b-c6c86e5fa34aspace/manage/member/pending-approvals
```
rather than
```
/index.php?r=space%2Fmanage%2Fmember%2Fpending-approvals&cguid=5396d499-20d6-4233-800b-c6c86e5fa34a
```
> Fix: Link notification for pending space approval to manage page

- CHANGELOG-DEV.md
- protected/humhub/components/ModuleManager.php
- Feature
**Does this PR introduce a breaking change?**
- No
This change allows additional data to be provided to the event handler based on the configuration of the event.
From an efficiency stand point, the following lines should be moved into the `if` block, with the exception of the extraction of the `$eventHandler`, of course:
https://github.com/humhub/humhub/commit/4a5951988969a0d2b9765867df7f4cdf088c3e82#diff-46a3b644fa0848e9b9ff89b55e78b267182b69d39cea2f61870c54d37d0a78a5R218-R222
I've not done that, however, in order to keep the …
> Enh: allow event data from config

- CHANGELOG-DEV.md
- protected/humhub/tests/codeception/unit/LoadDbTest.php
**What kind of change does this PR introduce?** 
- Other, please describe:
Create an easy way to populate the database with the standard test data set, without clearing it afterwards.
Normal use will not do anything other than succeed and hence not consume any time
```
php $HUMHUB_VENDOR_BIN/codecept run unit LoadDbTest
```
However, if run with the environment variable HUMHUB_DB_INITIALIZE set, then the default fixtures will be loaded and not unloaded after the test.
```
HUMHUB_DB_INITIALIZE= php $HUMHUB_VENDOR_BIN/codecept run unit LoadDbTest
```
This class could also be extended and then the data only loaded for certain tests within the class. But for now it helps to test the codebase from the web-interface easily.
- No
**The PR …
> Add pseudo test class to allow population of DB with standard test data

- CHANGELOG-DEV.md
- index.php
- protected/humhub/commands/MigrateController.php
- protected/humhub/components/console/Application.php
- protected/humhub/helpers/DatabaseHelper.php
- protected/humhub/libs/BaseSettingsManager.php
- protected/humhub/modules/installer/commands/InstallController.php
- protected/yii
- Bugfix
- No
When the connection information is wrong, or the database server name resolution fails, there are misleading error messages as there is actually no error handling of that situation so far.
This PR is a poor man's attempt to give the user some sort of helpful information. Yes, it does not look pretty and styled, but that's partly because the theming tries to access the db itself...
Particularly un-informative is the error when you try to run migrations with an invalid connection configuration.
> Enh: Attempt to show better error messages when DB-Connection is invalid

- CHANGELOG-DEV.md
- protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
- protected/humhub/tests/codeception/_support/HumHubHelper.php
- protected/humhub/tests/codeception/_support/HumHubHelperTrait.php
When a test is annotated with `@skip` (e.g. [`testCreatePublicContentOnPrivateSpace`](https://github.com/humhub/humhub/blob/e7c61781786a6184508681984f4f6e47bac99d9c/protected/humhub/modules/content/tests/codeception/unit/models/ContentVisibilityTest.php#L114) without adding a reason, or [`testConvertTableWithoutBodyAtEnd`](https://github.com/humhub/humhub/blob/e7c61781786a6184508681984f4f6e47bac99d9c/protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextHtmlConverterTest.php#L629)) the Application is not started (`Yii::$app` will be empty), yet the test itself is not skipped (the `@skip` annotation is a [feature of Codeception](url), but [not of PhpUnit](https://github.com/sebastianbergmann/phpunit/issues/3220)).
Hence, tests which are intended to be skipped can (and …
> Fix humhub test case would fail on skipped tests

- CHANGELOG-DEV.md
- protected/humhub/components/Application.php
- protected/humhub/components/ApplicationTrait.php
- protected/humhub/components/console/Application.php
- protected/humhub/components/mail/Mailer.php
- protected/humhub/config/__autocomplete.php
- protected/humhub/interfaces/ApplicationInterface.php
- protected/humhub/interfaces/MailerInterface.php
- protected/humhub/modules/notification/targets/MailTarget.php
- protected/humhub/tests/codeception/_support/TestMailer.php
- protected/humhub/tests/codeception/config/config.php
Depending on the mailer used, the `From`-address of an e-mail would not be set (e.g. when using the test mailer from the testing framework).
Using a helper function to compose the message ensures that the sender is _always_ set.
- Bugfix
- No
> Fix: Ensure e-mails would always have a sender address set

- CHANGELOG-DEV.md
- protected/humhub/components/Migration.php
In migrations, it would be helpful to know if the underlying `*safe*` method did actually do the thing, or not, without having to re-code the function.
This PR simply adds a `bool` return type. This, however, is not enforced for backwards-compatibility, as previously the return type was `void`. By removing the type declaration, child classes are still valid if the use `void`.
Also, for reasons of consistency and readability, the code in the methods have all been re-arranged, so that first is always done the action that is supposed to happen, and second the logging if not.
- Feature
- Code style update
- Grammar corrections in comments
- No
> Enh: Add boolean return type to *safe* methods in migrations

- CHANGELOG-DEV.md
- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
- protected/humhub/modules/content/widgets/richtext/converter/BaseRichTextConverter.php
- protected/humhub/modules/content/widgets/richtext/converter/RichTextToShortTextConverter.php
> Fix Avoid PHP 8.1+ deprecated null parameter on preg_replace in richtext converters

- CHANGELOG-DEV.md
- protected/humhub/modules/user/models/Profile.php
- Bugfix
- No
The error has repeatedly happened in `\humhub\modules\user\models\Profile::rules()`. Not sure what caused the issue. Something to do with initial data or migrations failed. However, the error that a property on null value was accessed is not very helpful. Now, in `YII_DEBUG` a more meaningful exception is thrown, while without debug the field is ignored, issuing an error log entry.
> Fix empty profile field type causing an unspecific error

- CHANGELOG-DEV.md
- protected/humhub/tests/codeception/_support/ArrayTarget.php
- protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
- protected/humhub/tests/codeception/_support/HumHubHelperTrait.php
- protected/humhub/tests/codeception/_support/Logger.php
- protected/humhub/tests/codeception/_support/TraversableContainsRegex.php
- protected/humhub/tests/codeception/unit/LogAssertionsSelfTest.php
So far, there is no possibility to easily check in a test if a specific log entry has been issued.
This PR allows a test to assert that
- a specific message by providing
- log level
- category (includes and excludes)
- message text or message regex
- a given message has _not_ been issued
- Feature
- No
-  ~~#6564~~
- #6562
> Enh: Support log assertions

- protected/humhub/exceptions/InvalidArgumentExceptionTrait.php
- protected/humhub/exceptions/InvalidArgumentTypeException.php
- protected/humhub/exceptions/InvalidArgumentValueException.php
- protected/humhub/exceptions/InvalidConfigTypeException.php
- protected/humhub/libs/BaseSettingsManager.php
- protected/humhub/libs/Helpers.php
- protected/humhub/tests/codeception/unit/exceptions/InvalidArgumentExceptionTest.php
- simplify constructor arguments
- make it compatible with `yii\base\InvalidArgumentException` or `\Exception` for that matter
- Reduce usage of Traits in `\humhub\exceptions\*`
See https://github.com/humhub/humhub/pull/6548#discussion_r1325425500 and following
- Refactor
###Does this PR introduce a breaking change?
- Yes, but only for v1.15 code, which is addressed in this PR.
> Fix: invalid argument exceptions

- CHANGELOG-DEV.md
- protected/humhub/modules/file/migrations/m230618_135508_file_add_sorting_column.php
- protected/humhub/modules/file/models/File.php
Adds `sort_order` field to `File` table/model.
- Feature
- No
Depends on/includes:
- #6590
> Enh: `file` fields: `sort_order`

- CHANGELOG-DEV.md
- CHANGELOG.md
- protected/humhub/modules/file/actions/DownloadAction.php
- protected/humhub/modules/file/migrations/m230618_135508_file_add_sorting_column.php
- protected/humhub/modules/file/models/File.php
- protected/humhub/tests/codeception/_support/ArrayTarget.php
- protected/humhub/tests/codeception/_support/HumHubDbTestCase.php
- protected/humhub/tests/codeception/_support/HumHubHelper.php
- protected/humhub/tests/codeception/_support/HumHubHelperTrait.php
- protected/humhub/tests/codeception/_support/Logger.php
- protected/humhub/tests/codeception/_support/TraversableContainsRegex.php
- protected/humhub/tests/codeception/unit/LoadDbTest.php
Resolving merge conflicts due to my recent PRs ...
> Merge develop into next

- CHANGELOG-DEV.md
- MIGRATE-DEV.md
- protected/humhub/components/behaviors/PolymorphicRelation.php
- protected/humhub/exceptions/InvalidArgumentClassException.php
- protected/humhub/libs/Helpers.php
- protected/humhub/modules/comment/controllers/CommentController.php
- protected/humhub/modules/content/components/ContentAddonController.php
- protected/humhub/modules/file/actions/UploadAction.php
- protected/humhub/modules/user/models/ProfileField.php
- protected/humhub/modules/user/models/fieldtype/BaseType.php
- protected/humhub/tests/codeception/unit/libs/HelpersTest.php
Besides fixing #6547, this version of `\humhub\libs\Helpers::checkClassType()` allows
- providing an object instance, rather than a class name, to be tested
- allows to return a negative result, rather than throwing an exception
- allows to distinguish between an invalid parameter `$className` and an invalid parameter `$type` (different code in Exception)
Depends and includes
- #6566
- Bugfix (Fix #6547)
- Feature
- Code style update
- Yes
The current version of the function throws a `\yii\base\Exception` if the type is not met.
The new version of the function throws a `\humhub\exceptions\InvalidArgumentException`, which derives from `\yii\base\InvalidArgumentException` and `\yii\base\InvalidParamException`, but not `\yii\base\Exception`.
As such, if the calling code is handling the …
> Fix #6547 Invalid class name validated as valid and improve validation

- CHANGELOG-DEV.md
- protected/humhub/modules/file/actions/DownloadAction.php
Avoid PHP error when trying to download a file without guid in the URL params (return 404 exception instead)
> Avoid PHP error when trying to download a file without guid in the URL params

- CHANGELOG-DEV.md
- protected/humhub/components/ModuleManager.php
- protected/humhub/tests/codeception/_support/HumHubHelperTrait.php
- protected/humhub/tests/codeception/unit/components/ModuleManagerTest.php
> Fix: Module Manager test

- CHANGELOG.md
- protected/humhub/modules/file/Events.php
- protected/humhub/modules/post/Events.php
Fix similar issue as https://github.com/humhub/cfiles/issues/198
> Fix memory usage on integrity check

- CHANGELOG-DEV.md
- protected/humhub/interfaces/ArchiveableInterface.php
- protected/humhub/interfaces/DeletableInterface.php
- protected/humhub/interfaces/EditableInterface.php
- protected/humhub/interfaces/MailerInterface.php
- protected/humhub/interfaces/ReadableInterface.php
- protected/humhub/interfaces/ViewableInterface.php
- protected/humhub/modules/content/components/ContentAddonActiveRecord.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/file/models/File.php
Related to: https://github.com/humhub/custom-pages/issues/308#issuecomment-1807947711
> Allow view file when owner object provides this

- CHANGELOG.md
- protected/humhub/components/behaviors/PolymorphicRelation.php
- protected/humhub/modules/content/components/ContentActiveRecord.php
- protected/humhub/modules/content/services/ContentStateService.php
This PR addresses the circumstance, where the cached record in the polymorphic relationship of a content model does not correspond to the instance of the `ContentActiveRecord` that is accessing it's `content` property.
Furthermore, it address the fact, that the `ContentStateService::set()` method is calling a deprecated `setState()` method on it's content object, which then in turn again calls `ContentStateService::set()`. The endless loop is only prevented thanks to PHP avoiding calling the same `__set($name)` call recursively. So the loop happens only once.
Also v1.14 is affected by this.
Could this still be added to v1.15 or even 1.14? Happy to rebase, if yes.
- Bugfix
- No
###The PR fulfills these requirements
> Fix: Content relations

- CHANGELOG-DEV.md
- protected/humhub/modules/content/widgets/StateBadge.php
Currently, the `\humhub\modules\content\widgets\StateBadge` does require the `StateBadge::$model` to be a ContentActiveRecord. However, states may also be used on other records.
This PR allows to override where the widget gets the state from. Two steps are required:
1. Extend the StateBadge class, overriding the `getState()` method returning the value from the custom source, e.g.
```php
public function getState(): ?int
{
return $this->model->state;
}
```
4. Register an event to overwrite the class, e.g. in `config.php` add
````php
[
'class' => \humhub\modules\content\widgets\StateBadge::class,
'event' => \humhub\components\Widget::EVENT_CREATE,
'callback' => [
MyStateBadge::class,
'onWidgetCreate',
]
]
```
A full example of the class, including additional states would be:
```php
<?php
/** …
```
> Enh: Make state badge customizable

- CHANGELOG-DEV.md
- MIGRATE-DEV.md
- protected/humhub/commands/MigrateController.php
`MigrateController::$migrationPathMap` would store the sum of the migrations encountered so far while collecting the migrations of the different migration paths. This makes no sense at all. :-)
This PR fixes that only the migrations of a given `$path` are stored under `MigrateController::$migrationPathMap[$path]`.
In addition, type cleanup is applied.
- Bugfix
- Refactor
- Yes
Type restrictions as documented in `MIGRATE-DEV.md`. However, there's no inheritance of the class in the core and unlikely in modules. So risk is low.
> Fix `MigrateController::$migrationPathMap`

- CHANGELOG-DEV.md
- MIGRATE-DEV.md
- protected/humhub/components/ApplicationTrait.php
- protected/humhub/components/Controller.php
- protected/humhub/components/Migration.php
- protected/humhub/components/ModuleManager.php
- protected/humhub/components/Request.php
- protected/humhub/components/behaviors/AccessControl.php
- protected/humhub/components/console/Application.php
- protected/humhub/components/console/UrlManager.php
- protected/humhub/components/i18n/Formatter.php
- protected/humhub/components/i18n/I18N.php
- protected/humhub/libs/BaseSettingsManager.php
- protected/humhub/libs/SelfTest.php
- protected/humhub/migrations/m201228_064513_default_group.php
- protected/humhub/models/Setting.php
- protected/humhub/modules/installer/Module.php
- protected/humhub/modules/installer/commands/InstallController.php
- protected/humhub/modules/installer/controllers/SetupController.php
- protected/humhub/modules/notification/targets/MailTarget.php
- protected/humhub/modules/ui/view/bootstrap/ThemeLoader.php
- protected/humhub/modules/ui/view/components/Theme.php
- protected/humhub/modules/ui/view/components/ThemeVariables.php
- protected/humhub/modules/ui/view/components/View.php
- protected/humhub/modules/web/Events.php
- protected/humhub/modules/web/security/helpers/Security.php
- protected/humhub/tests/codeception/unit/components/BaseSettingsManagerTest.php
- protected/humhub/tests/codeception/unit/components/ModuleManagerTest.php
- protected/humhub/widgets/LayoutAddons.php
- Code de-duplication
- move code away from `Settings`, that has nothing to do with `Settings`
- move it to `BaseSettingsManager` where also `isDatabaseInstalled()` resides
- Refactor
- No
> Enh: Consolidate `(is|set)(Database)Installed()` to `ApplicationTrait`

- protected/humhub/components/ApplicationTrait.php
- protected/humhub/config/common.php
- protected/humhub/tests/codeception/unit/ApplicationBaseTest.php
Since `protected/humhub/config/common.php` defined `Yii::$app->params['databaseInstalled']` to be false, `Yii::$app->isDatabaseInstalled()` would return false, unless the value is overwritten by `@config/dynamic.php`.
During tests, `@config/dynamic.php` does not set the paramter to true.
The current solution is to remove the paramter alltogether from the default set of config. As such, the value remains undefined unless set in `@config/dynamic.php`.
`Yii::$app->isDatabaseInstalled()` will now check the real database connection not only if the `$checkConnection` parameter is set to true, but also if the parameter has not yet been defined.
- Bugfix
- No
>  Fix #6720 Regression re isDatabaseInstalled

- CHANGELOG-DEV.md
- MIGRATE-DEV.md
- protected/humhub/components/behaviors/PolymorphicRelation.php
- protected/humhub/libs/UUIDValidator.php
- protected/humhub/modules/content/components/ContentContainerActiveRecord.php
- protected/humhub/modules/content/models/Content.php
- protected/humhub/modules/content/models/ContentContainer.php
- protected/humhub/modules/content/tests/codeception/unit/models/ContentContainerTest.php
- protected/humhub/modules/file/migrations/m230618_135512_file_add_guid_unique_index.php
- protected/humhub/modules/file/models/File.php
- protected/humhub/modules/space/models/Space.php
- protected/humhub/modules/user/models/User.php
- Refactor
- Yes
UUID (e.g. used in `guid` columns) must actually be valid UUIDs, meaning
- valid format and characters
- unique at least within any given table
Applied to
- `contentcontainer.guid`
- `content.guid`
- `file.guid`
- `space.guid`
- `user.guid` 
> Enh: Apply UUID validator

- CHANGELOG-DEV.md
- protected/humhub/commands/MigrateController.php
- protected/humhub/modules/admin/controllers/InformationController.php
- protected/humhub/modules/admin/controllers/SettingController.php
- protected/humhub/modules/admin/views/information/database.php
Currently, when navigating to Administration -> Information -> Database, any pending migration is applied immediately and leaves the administrator no choice of whether to actually apply them now.
- This PR loads and displays the pending migration and gives the user the option to apply them.
- Once migrations are applied, the user can reload the migration info (useful, if some migrations failed) and apply them again.
- If no migration is applied, no option to apply them is offered.
- If migrations are applied, cache is automatically cleared as well.
- Feature
- No
> Enh: run migrations manually

- CHANGELOG-DEV.md
- MIGRATE-DEV.md
- protected/humhub/commands/MigrateController.php
- protected/humhub/components/Module.php
- protected/humhub/components/ModuleManager.php
- protected/humhub/components/SettingActiveRecord.php
- protected/humhub/components/bootstrap/ModuleAutoLoader.php
- protected/humhub/events/MigrationEvent.php
- protected/humhub/modules/admin/controllers/InformationController.php
- protected/humhub/modules/content/components/ContentContainerModule.php
- protected/humhub/modules/installer/commands/InstallController.php
- protected/humhub/modules/installer/controllers/SetupController.php
- protected/humhub/modules/marketplace/components/OnlineModuleManager.php
- protected/humhub/services/MigrationService.php
- protected/humhub/tests/codeception/_data/ModuleConfig/moduleWithMigration/Module.php
- protected/humhub/tests/codeception/_data/ModuleConfig/moduleWithMigration/config.php
- protected/humhub/tests/codeception/_data/ModuleConfig/moduleWithMigration/migrations/m230911_000100_create_test_table.php
- protected/humhub/tests/codeception/_data/ModuleConfig/moduleWithMigration/migrations/uninstall.php
- protected/humhub/tests/codeception/_data/ModuleConfig/moduleWithMigration/module.json
- protected/humhub/tests/codeception/unit/components/ModuleManagerTest.php
Currently, any error that happens during the migration when enabling, updating, or disabling a module, go unnoticed. There is no exception thrown, nor a log entry added nor is the migration result nor its output available to any calling code.
With this PR does
- `enable,` `update()`, or `disable()` methods return
- `true` on success
- `false` on error
- `null` if the `enable,` `update()`, or `disable()` method was cancelled due to the `before*` method.
- migration output is logged, if available
- `$module->migrationResult` holds the result of the migration action:
- `ExitCode::OK = 0` for success, 
- `ExitCode::UNSPECIFIED_ERROR = 1` for error, or
- `null` if no migration was executed
- `$module->migrationOutput` holds the output of the migration. Can also be `null` on error or if no …
> Enh improve module migrations

- CHANGELOG.md
- protected/humhub/libs/BasePermission.php
- protected/humhub/modules/user/components/PermissionManager.php
`PermissionManager` caches the permission's state solely identified by it's `id`. However, the `id` is not required to be unique in the system, but only unique within a module (see primary keys of permission tables). Hence, two modules providing the same identifier in one of their permissions, may collide here.
The applied solution is to get a unique cache key from the permission. This also gives the permission to disable caching by returning `null` - either categorically or based on the parameters used in the `can()` call.
- Bugfix
- Feature
- No
> Fix non-unique key used for permission caching

- CHANGELOG-DEV.md
- protected/humhub/modules/admin/controllers/PendingRegistrationsController.php
Users admin and pending approvals already are allowed for non sys admins.
And access rules are defined for ManageUsers or ManageGroups, so no need to restrict to only sys admins.
> Allow access to pending registrations to non system admins

- CHANGELOG-DEV.md
- protected/humhub/modules/space/behaviors/SpaceModelMembership.php
`SpaceModelMembership::removeMember()` should always return a boolean value (returns void if success)
> SpaceModelMembership::removeMember() should return bool

- CHANGELOG.md
- protected/humhub/modules/content/resources/js/humhub.content.container.js
- protected/humhub/modules/content/widgets/views/notificationSwitchLink.php
This switcher doesn't work correctly:
> Fix notification switcher in wall stream entry context menu

- CHANGELOG-DEV.md
- static/js/humhub/humhub.ui.navigation.js
> If a top menu entry opens a modal box, don't mark it as active when clicked

- CHANGELOG-DEV.md
- protected/humhub/modules/comment/controllers/PermaController.php
Issue: https://github.com/humhub/humhub-internal/issues/174
> Implement new method `getCommentUrl` for permanent comment URL

- CHANGELOG-DEV.md
- protected/humhub/modules/content/controllers/SearchController.php
- protected/humhub/modules/content/search/ResultSet.php
- protected/humhub/modules/content/search/SearchRequest.php
- protected/humhub/modules/content/search/driver/AbstractDriver.php
- protected/humhub/modules/content/search/driver/MysqlDriver.php
- protected/humhub/modules/content/search/driver/ZendLucenceDriver.php
- protected/humhub/modules/content/views/search/results.php
- protected/humhub/modules/content/widgets/SearchFilters.php
- protected/humhub/modules/stream/resources/js/humhub.stream.SimpleStream.js
- protected/humhub/modules/stream/resources/js/humhub.stream.Stream.js
Issue: https://github.com/humhub/humhub-internal/issues/207
> Auto load pages on content search

- CHANGELOG.md
- MIGRATE-DEV.md
- protected/humhub/modules/ui/form/widgets/BasePicker.php
- protected/humhub/modules/ui/form/widgets/MultiSelect.php
Currently, the `BasePicker` and the `MultiSelect` widgets try to get the value from the module, if `$config['selection']` is `empty` (which includes an empty array!).
To avoid such a lookup by the widget, one would expect to provide an empty array (which may actually constitute the current selection). However, this will be ignored due to the above.
This PR does treat an empty array as a valid selection list. Thus, avoiding looking up the value.
Additionally, if the field value is an `ArrayAccess` instance, rather than an `array`, the current code fails with a fatal error. Using `ArrayHelper::keyExists()` rather than `in_array()` solves this issue.
- Bugfix
- Maybe Yes
- Probably No
Not sure if there are use …
> Fix MultiSelect when empty selection is given

- CHANGELOG.md
- protected/humhub/modules/user/migrations/m240419_095931_fix_user_profile_country_code.php
https://github.com/humhub/humhub/issues/6919
> Fix #6919: Migration to revert user profile country names to Iso 3166 codes

- CHANGELOG.md
- protected/humhub/modules/admin/controllers/UserController.php
- protected/humhub/modules/user/views/invite/index.php
https://github.com/humhub/humhub-internal/issues/225
> Make "Invite new people" always possible for Admins

- CHANGELOG-DEV.md
- protected/humhub/modules/content/search/ContentSearchProvider.php
- protected/humhub/modules/content/search/SearchRequest.php
https://github.com/humhub/humhub-internal/issues/228
> Use same order for meta searching that is used for content page searching by default

- protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php
> Fix: Attempt to read property "jsWidget" on null

- protected/humhub/modules/content/Events.php
Bug produced from https://github.com/humhub/humhub/pull/6971 on run install new site:
> Register `ContentHighlightAsset` only when app is installed

- protected/humhub/modules/notification/migrations/m240422_162959_new_is_untouched_settings.php
https://github.com/humhub/humhub-internal/issues/246
> Fix migration on added duplicated container settings

- protected/humhub/modules/content/assets/ContentHighlightAsset.php
https://github.com/humhub/humhub-internal/issues/250
> Exclude content highlighting on console request

- protected/humhub/modules/admin/views/information/database.php
- protected/humhub/services/MigrationService.php
https://github.com/humhub/humhub-internal/issues/246#issuecomment-2104795918
> Restrict double call migration with button loader

- CHANGELOG-DEV.md
- protected/humhub/modules/user/widgets/PeopleFilters.php
https://github.com/humhub/humhub/issues/6962#issuecomment-2113740229
> Fix people filter by group

- CHANGELOG-DEV.md
- protected/humhub/modules/content/search/ResultSet.php
https://github.com/humhub/humhub-internal/issues/259
> Fix content search order after restoring from cache

- protected/humhub/modules/content/search/driver/MysqlDriver.php
- protected/humhub/modules/content/tests/codeception/unit/search/AbstractDriverTestSuite.php
- protected/humhub/modules/content/tests/codeception/unit/search/MysqlDriverTest.php
- static/js/humhub/humhub.ui.additions.js
https://github.com/humhub/humhub-internal/issues/230#issuecomment-2126689045
> Improve content search

- CHANGELOG-DEV.md
Mention of the fix for https://github.com/humhub/humhub/issues/7065 in the changelog
> Fix #7065: Space members manager crashes on HumHub 1.16.0-beta.3

- protected/humhub/modules/post/permissions/CreatePost.php
I was trying to configure my HumHub instance so that non-members could post in into Spaces without first joining the space. This is vital for the way my instance is used. As it stood, it was only possible for instance Admins to create posts in Spaces they were not members of.
The change from this PR will make it so that in a Space's permission settings the option "Create Posts" will become available to configure, and setting it to "Allow" will result in letting …
> Enable option for non-member users of a space to create posts

- CHANGELOG.md
- protected/humhub/modules/comment/widgets/views/comment.php
- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
- protected/humhub/modules/post/widgets/views/wallEntry.php
https://github.com/humhub/translator/issues/52#issuecomment-2334600960
> Remove obsolete property `AbstractRichText::$record`

- CHANGELOG.md
- protected/humhub/modules/user/models/Invite.php
https://github.com/humhub/humhub-internal/issues/390
> Refresh the updated_at timestamp of invitation after resend it

- CHANGELOG.md
- protected/humhub/modules/comment/widgets/views/comment.php
- protected/humhub/modules/content/widgets/richtext/AbstractRichText.php
- protected/humhub/modules/post/widgets/views/wallEntry.php
https://github.com/humhub/humhub-internal/issues/424#issuecomment-2428754154
Revert PR https://github.com/humhub/humhub/pull/7211
> Revert removed property `AbstractRichText::$record` from PR #7211

- CHANGELOG.md
- protected/humhub/libs/SelfTest.php
> Fix #7281: SelfTest for DynamicConfig broken when not exist yet

- CHANGELOG.md
- protected/humhub/modules/topic/widgets/TopicLabel.php
https://github.com/humhub/humhub-internal/issues/433
> Disable link in `TopicLabel` when contentContainer is not present

- CHANGELOG.md
- MIGRATE-DEV.md
- protected/humhub/modules/content/models/Content.php
Issue https://github.com/humhub/humhub-internal/issues/523
This PR allows system admins, in all cases (even when `enableManageAllContentPermission` is disabled), to edit and delete content in other Profile streams (User container).
But the view behaviour remains identical (by default, if not a friend, admins don't see User's private content).
> Fix: Always allow admins to edit/delete content in the other Profile stream

- protected/humhub/migrations/m250405_072758_1_18_switch_to_humhub_theme_and_disable_themes.php
Fix the error on install new site when no theme in system yet:
> Fix theme migration on install new site
